//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package chart ;import (_d "fmt";_f "github.com/unidoc/unioffice/v2";_ec "github.com/unidoc/unioffice/v2/color";_ea "github.com/unidoc/unioffice/v2/drawing";_e "github.com/unidoc/unioffice/v2/measurement";_db "github.com/unidoc/unioffice/v2/schema/soo/dml";
_af "github.com/unidoc/unioffice/v2/schema/soo/dml/chart";_ac "math/rand";);func (_fff ScatterChartSeries )InitializeDefaults (){_fff .Properties ().LineProperties ().SetNoFill ();_fff .Marker ().SetSymbol (_af .ST_MarkerStyleAuto );_fff .Labels ().SetShowLegendKey (false );
_fff .Labels ().SetShowValue (true );_fff .Labels ().SetShowPercent (false );_fff .Labels ().SetShowCategoryName (false );_fff .Labels ().SetShowSeriesName (false );_fff .Labels ().SetShowLeaderLines (false );};type SurfaceChartSeries struct{_edgg *_af .CT_SurfaceSer };


// InitializeDefaults the bar chart to its defaults
func (_ca BarChart )InitializeDefaults (){_ca .SetDirection (_af .ST_BarDirCol )};

// MakeAxisDataSource constructs an AxisDataSource wrapper.
func MakeAxisDataSource (x *_af .CT_AxDataSource )CategoryAxisDataSource {return CategoryAxisDataSource {x };};

// AddSeries adds a default series to an area chart.
func (_b Area3DChart )AddSeries ()AreaChartSeries {_ede :=_b .nextColor (len (_b ._ed .Ser ));_be :=_af .NewCT_AreaSer ();_b ._ed .Ser =append (_b ._ed .Ser ,_be );_be .Idx .ValAttr =uint32 (len (_b ._ed .Ser )-1);_be .Order .ValAttr =uint32 (len (_b ._ed .Ser )-1);
_eae :=AreaChartSeries {_be };_eae .InitializeDefaults ();_eae .Properties ().SetSolidFill (_ede );return _eae ;};

// Order returns the order of the series
func (_acd LineChartSeries )Order ()uint32 {return _acd ._agb .Order .ValAttr };

// InitializeDefaults the Bubble chart to its defaults
func (_ebf BubbleChart )InitializeDefaults (){};func (_aa Area3DChart )AddAxis (axis Axis ){_df :=_af .NewCT_UnsignedInt ();_df .ValAttr =axis .AxisID ();_aa ._ed .AxId =append (_aa ._ed .AxId ,_df );};

// InitializeDefaults the bar chart to its defaults
func (_fb AreaChart )InitializeDefaults (){};

// X returns the inner wrapped XML type.
func (_cgcc ScatterChart )X ()*_af .CT_ScatterChart {return _cgcc ._ceff };

// CategoryAxis returns the category data source.
func (_cbd BarChartSeries )CategoryAxis ()CategoryAxisDataSource {if _cbd ._fa .Cat ==nil {_cbd ._fa .Cat =_af .NewCT_AxDataSource ();};return MakeAxisDataSource (_cbd ._fa .Cat );};

// SetOrder sets the order of the series
func (_deab LineChartSeries )SetOrder (idx uint32 ){_deab ._agb .Order .ValAttr =idx };

// Order returns the order of the series
func (_ffecf ScatterChartSeries )Order ()uint32 {return _ffecf ._gfec .Order .ValAttr };

// Values returns the value data source.
func (_ga BarChartSeries )Values ()NumberDataSource {if _ga ._fa .Val ==nil {_ga ._fa .Val =_af .NewCT_NumDataSource ();};return MakeNumberDataSource (_ga ._fa .Val );};

// AddAreaChart adds a new area chart to a chart.
func (_aeg Chart )AddAreaChart ()AreaChart {_gfg :=_af .NewCT_PlotAreaChoice ();_aeg ._gdb .Chart .PlotArea .PlotAreaChoice =append (_aeg ._gdb .Chart .PlotArea .PlotAreaChoice ,_gfg );_gfg .AreaChart =_af .NewCT_AreaChart ();_ega :=AreaChart {_c :_gfg .AreaChart };
_ega .InitializeDefaults ();return _ega ;};

// Labels returns the data label properties.
func (_cag LineChartSeries )Labels ()DataLabels {if _cag ._agb .DLbls ==nil {_cag ._agb .DLbls =_af .NewCT_DLbls ();};return MakeDataLabels (_cag ._agb .DLbls );};

// Properties returns the Bubble chart series shape properties.
func (_cbea BubbleChartSeries )Properties ()_ea .ShapeProperties {if _cbea ._fe .SpPr ==nil {_cbea ._fe .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_cbea ._fe .SpPr );};func (_aecc Legend )Properties ()_ea .ShapeProperties {if _aecc ._feab .SpPr ==nil {_aecc ._feab .SpPr =_db .NewCT_ShapeProperties ();
};return _ea .MakeShapeProperties (_aecc ._feab .SpPr );};func MakeLegend (l *_af .CT_Legend )Legend {return Legend {l }};

// AddSeries adds a default series to an area chart.
func (_ce AreaChart )AddSeries ()AreaChartSeries {_cb :=_ce .nextColor (len (_ce ._c .Ser ));_g :=_af .NewCT_AreaSer ();_ce ._c .Ser =append (_ce ._c .Ser ,_g );_g .Idx .ValAttr =uint32 (len (_ce ._c .Ser )-1);_g .Order .ValAttr =uint32 (len (_ce ._c .Ser )-1);
_afb :=AreaChartSeries {_g };_afb .InitializeDefaults ();_afb .Properties ().SetSolidFill (_cb );return _afb ;};

// AddPieChart adds a new pie chart to a chart.
func (_dbec Chart )AddPieChart ()PieChart {_bc :=_af .NewCT_PlotAreaChoice ();_dbec ._gdb .Chart .PlotArea .PlotAreaChoice =append (_dbec ._gdb .Chart .PlotArea .PlotAreaChoice ,_bc );_bc .PieChart =_af .NewCT_PieChart ();_dfaa :=PieChart {_bad :_bc .PieChart };
_dfaa .InitializeDefaults ();return _dfaa ;};func MakeMarker (x *_af .CT_Marker )Marker {return Marker {x }};func _aaa (_bab *_af .CT_Chart ){_bab .View3D =_af .NewCT_View3D ();_bab .View3D .RotX =_af .NewCT_RotX ();_bab .View3D .RotX .ValAttr =_f .Int8 (15);
_bab .View3D .RotY =_af .NewCT_RotY ();_bab .View3D .RotY .ValAttr =_f .Uint16 (20);_bab .View3D .RAngAx =_af .NewCT_Boolean ();_bab .View3D .RAngAx .ValAttr =_f .Bool (false );_bab .Floor =_af .NewCT_Surface ();_bab .Floor .Thickness =_af .NewCT_Thickness ();
_bab .Floor .Thickness .ValAttr .Uint32 =_f .Uint32 (0);_bab .SideWall =_af .NewCT_Surface ();_bab .SideWall .Thickness =_af .NewCT_Thickness ();_bab .SideWall .Thickness .ValAttr .Uint32 =_f .Uint32 (0);_bab .BackWall =_af .NewCT_Surface ();_bab .BackWall .Thickness =_af .NewCT_Thickness ();
_bab .BackWall .Thickness .ValAttr .Uint32 =_f .Uint32 (0);};func (_ceb ValueAxis )Properties ()_ea .ShapeProperties {if _ceb ._agda .SpPr ==nil {_ceb ._agda .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_ceb ._agda .SpPr );};


// X returns the inner wrapped XML type.
func (_ecb BubbleChart )X ()*_af .CT_BubbleChart {return _ecb ._gfe };func (_fge CategoryAxis )AxisID ()uint32 {return _fge ._cf .AxId .ValAttr };

// X returns the inner wrapped XML type.
func (_fbb StockChart )X ()*_af .CT_StockChart {return _fbb ._ccda };

// AddSeries adds a default series to an Pie chart.
func (_bgdd PieOfPieChart )AddSeries ()PieChartSeries {_fcfa :=_af .NewCT_PieSer ();_bgdd ._adc .Ser =append (_bgdd ._adc .Ser ,_fcfa );_fcfa .Idx .ValAttr =uint32 (len (_bgdd ._adc .Ser )-1);_fcfa .Order .ValAttr =uint32 (len (_bgdd ._adc .Ser )-1);_bag :=PieChartSeries {_fcfa };
_bag .InitializeDefaults ();return _bag ;};

// X returns the inner wrapped XML type.
func (_abee ValueAxis )X ()*_af .CT_ValAx {return _abee ._agda };func (_ffb CategoryAxis )Properties ()_ea .ShapeProperties {if _ffb ._cf .SpPr ==nil {_ffb ._cf .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_ffb ._cf .SpPr );};


// AddPie3DChart adds a new pie chart to a chart.
func (_eagf Chart )AddPie3DChart ()Pie3DChart {_aaa (_eagf ._gdb .Chart );_cdc :=_af .NewCT_PlotAreaChoice ();_eagf ._gdb .Chart .PlotArea .PlotAreaChoice =append (_eagf ._gdb .Chart .PlotArea .PlotAreaChoice ,_cdc );_cdc .Pie3DChart =_af .NewCT_Pie3DChart ();
_fcd :=Pie3DChart {_bafg :_cdc .Pie3DChart };_fcd .InitializeDefaults ();return _fcd ;};var NullAxis Axis =nullAxis (0);func (_ffde SurfaceChartSeries )InitializeDefaults (){_ffde .Properties ().LineProperties ().SetWidth (1*_e .Point );_ffde .Properties ().LineProperties ().SetSolidFill (_ec .Black );
_ffde .Properties ().LineProperties ().SetJoin (_ea .LineJoinRound );};

// SurfaceChart is a 3D surface chart, viewed from the top-down.
type SurfaceChart struct{chartBase ;_ddd *_af .CT_SurfaceChart ;};

// SetDirection changes the direction of the bar chart (bar or column).
func (_ff Bar3DChart )SetDirection (d _af .ST_BarDir ){_ff ._ag .BarDir .ValAttr =d };

// RemoveLegend removes the legend if the chart has one.
func (_cdd Chart )RemoveLegend (){_cdd ._gdb .Chart .Legend =nil };func (_ggf DateAxis )SetPosition (p _af .ST_AxPos ){_ggf ._ddf .AxPos =_af .NewCT_AxPos ();_ggf ._ddf .AxPos .ValAttr =p ;};

// SetIndex sets the index of the series
func (_decf LineChartSeries )SetIndex (idx uint32 ){_decf ._agb .Idx .ValAttr =idx };

// AddSeries adds a default series to an Radar chart.
func (_eed RadarChart )AddSeries ()RadarChartSeries {_dcag :=_eed .nextColor (len (_eed ._gce .Ser ));_cbbe :=_af .NewCT_RadarSer ();_eed ._gce .Ser =append (_eed ._gce .Ser ,_cbbe );_cbbe .Idx .ValAttr =uint32 (len (_eed ._gce .Ser )-1);_cbbe .Order .ValAttr =uint32 (len (_eed ._gce .Ser )-1);
_gcce :=RadarChartSeries {_cbbe };_gcce .InitializeDefaults ();_gcce .Properties ().SetSolidFill (_dcag );return _gcce ;};

// InitializeDefaults the bar chart to its defaults
func (_cccb PieOfPieChart )InitializeDefaults (){_cccb ._adc .VaryColors =_af .NewCT_Boolean ();_cccb ._adc .VaryColors .ValAttr =_f .Bool (true );_cccb .SetType (_af .ST_OfPieTypePie );_cccb ._adc .SecondPieSize =_af .NewCT_SecondPieSize ();_cccb ._adc .SecondPieSize .ValAttr =&_af .ST_SecondPieSize {};
_cccb ._adc .SecondPieSize .ValAttr .ST_SecondPieSizeUShort =_f .Uint16 (75);_afcd :=_af .NewCT_ChartLines ();_afcd .SpPr =_db .NewCT_ShapeProperties ();_acc :=_ea .MakeShapeProperties (_afcd .SpPr );_acc .LineProperties ().SetSolidFill (_ec .Auto );_cccb ._adc .SerLines =append (_cccb ._adc .SerLines ,_afcd );
};

// RadarChart is an Radar chart that has a shaded Radar underneath a curve.
type RadarChart struct{chartBase ;_gce *_af .CT_RadarChart ;};

// AddSeries adds a default series to a bar chart.
func (_ae BarChart )AddSeries ()BarChartSeries {_ebb :=_ae .nextColor (len (_ae ._dfg .Ser ));_bfe :=_af .NewCT_BarSer ();_ae ._dfg .Ser =append (_ae ._dfg .Ser ,_bfe );_bfe .Idx .ValAttr =uint32 (len (_ae ._dfg .Ser )-1);_bfe .Order .ValAttr =uint32 (len (_ae ._dfg .Ser )-1);
_cef :=BarChartSeries {_bfe };_cef .InitializeDefaults ();_cef .Properties ().SetSolidFill (_ebb );return _cef ;};func MakeNumberDataSource (x *_af .CT_NumDataSource )NumberDataSource {return NumberDataSource {x }};func (_eeada StockChart )AddAxis (axis Axis ){_cdg :=_af .NewCT_UnsignedInt ();
_cdg .ValAttr =axis .AxisID ();_eeada ._ccda .AxId =append (_eeada ._ccda .AxId ,_cdg );};func (_bbd SeriesAxis )InitializeDefaults (){};

// Values returns the value data source.
func (_ace RadarChartSeries )Values ()NumberDataSource {if _ace ._dgaf .Val ==nil {_ace ._dgaf .Val =_af .NewCT_NumDataSource ();};return MakeNumberDataSource (_ace ._dgaf .Val );};

// SetText sets the series text.
func (_ffe BarChartSeries )SetText (s string ){_ffe ._fa .Tx =_af .NewCT_SerTx ();_ffe ._fa .Tx .SerTxChoice .V =&s ;};

// Chart is a generic chart.
type Chart struct{_gdb *_af .ChartSpace };func (_fcaa ValueAxis )AxisID ()uint32 {return _fcaa ._agda .AxId .ValAttr };func (_efg CategoryAxis )SetMajorTickMark (m _af .ST_TickMark ){if m ==_af .ST_TickMarkUnset {_efg ._cf .MajorTickMark =nil ;}else {_efg ._cf .MajorTickMark =_af .NewCT_TickMark ();
_efg ._cf .MajorTickMark .ValAttr =m ;};};

// AddBar3DChart adds a new 3D bar chart to a chart.
func (_deca Chart )AddBar3DChart ()Bar3DChart {_aaa (_deca ._gdb .Chart );_gcb :=_af .NewCT_PlotAreaChoice ();_deca ._gdb .Chart .PlotArea .PlotAreaChoice =append (_deca ._gdb .Chart .PlotArea .PlotAreaChoice ,_gcb );_gcb .Bar3DChart =_af .NewCT_Bar3DChart ();
_gcb .Bar3DChart .Grouping =_af .NewCT_BarGrouping ();_gcb .Bar3DChart .Grouping .ValAttr =_af .ST_BarGroupingStandard ;_fad :=Bar3DChart {_ag :_gcb .Bar3DChart };_fad .InitializeDefaults ();return _fad ;};func (_fffc ValueAxis )SetMajorTickMark (m _af .ST_TickMark ){if m ==_af .ST_TickMarkUnset {_fffc ._agda .MajorTickMark =nil ;
}else {_fffc ._agda .MajorTickMark =_af .NewCT_TickMark ();_fffc ._agda .MajorTickMark .ValAttr =m ;};};

// SetDisplayBlanksAs controls how missing values are displayed.
func (_defe Chart )SetDisplayBlanksAs (v _af .ST_DispBlanksAs ){_defe ._gdb .Chart .DispBlanksAs =_af .NewCT_DispBlanksAs ();_defe ._gdb .Chart .DispBlanksAs .ValAttr =v ;};func (_aba chartBase )nextColor (_bac int )_ec .Color {return _ccd [_bac %len (_ccd )]};


// X returns the inner wrapped XML type.
func (_baf Chart )X ()*_af .ChartSpace {return _baf ._gdb };

// AddAxis adds an axis to a line chart.
func (_efc LineChart )AddAxis (axis Axis ){_egea :=_af .NewCT_UnsignedInt ();_egea .ValAttr =axis .AxisID ();_efc ._geg .AxId =append (_efc ._geg .AxId ,_egea );};

// Surface3DChart is a 3D view of a surface chart.
type Surface3DChart struct{chartBase ;_eaa *_af .CT_Surface3DChart ;};type Marker struct{_cac *_af .CT_Marker };

// X returns the inner wrapped XML type.
func (_dgg LineChart )X ()*_af .CT_LineChart {return _dgg ._geg };func (_ded SurfaceChart )InitializeDefaults (){_ded ._ddd .Wireframe =_af .NewCT_Boolean ();_ded ._ddd .Wireframe .ValAttr =_f .Bool (false );_ded ._ddd .BandFmts =_af .NewCT_BandFmts ();
for _agdd :=0;_agdd < 15;_agdd ++{_cdcg :=_af .NewCT_BandFmt ();_cdcg .Idx .ValAttr =uint32 (_agdd );_cdcg .SpPr =_db .NewCT_ShapeProperties ();_ffce :=_ea .MakeShapeProperties (_cdcg .SpPr );_ffce .SetSolidFill (_ded .nextColor (_agdd ));_ded ._ddd .BandFmts .BandFmt =append (_ded ._ddd .BandFmts .BandFmt ,_cdcg );
};};func MakeSeriesAxis (x *_af .CT_SerAx )SeriesAxis {return SeriesAxis {x }};

// InitializeDefaults the bar chart to its defaults
func (_cfed DoughnutChart )InitializeDefaults (){_cfed ._ffec .VaryColors =_af .NewCT_Boolean ();_cfed ._ffec .VaryColors .ValAttr =_f .Bool (true );_cfed ._ffec .HoleSize =_af .NewCT_HoleSize ();_cfed ._ffec .HoleSize .ValAttr =&_af .ST_HoleSize {};_cfed ._ffec .HoleSize .ValAttr .ST_HoleSizeUByte =_f .Uint8 (50);
};func (_bbc Chart )AddSeriesAxis ()SeriesAxis {_bcf :=_af .NewCT_SerAx ();if _bbc ._gdb .Chart .PlotArea .PlotAreaChoice1 ==nil {_bbc ._gdb .Chart .PlotArea .PlotAreaChoice1 =[]*_af .CT_PlotAreaChoice1 {};};_bcf .AxId =_af .NewCT_UnsignedInt ();_bcf .AxId .ValAttr =0x7FFFFFFF&_ac .Uint32 ();
_bbc ._gdb .Chart .PlotArea .PlotAreaChoice1 =append (_bbc ._gdb .Chart .PlotArea .PlotAreaChoice1 ,&_af .CT_PlotAreaChoice1 {SerAx :_bcf });_bcf .Delete =_af .NewCT_Boolean ();_bcf .Delete .ValAttr =_f .Bool (false );_gaa :=MakeSeriesAxis (_bcf );_gaa .InitializeDefaults ();
return _gaa ;};func (_bcc SurfaceChartSeries )Values ()NumberDataSource {if _bcc ._edgg .Val ==nil {_bcc ._edgg .Val =_af .NewCT_NumDataSource ();};_gge :=MakeNumberDataSource (_bcc ._edgg .Val );_gge .CreateEmptyNumberCache ();return _gge ;};

// SetNumberReference is used to set the source data to a range of cells containing
// numbers.
func (_efd CategoryAxisDataSource )SetNumberReference (s string ){_efd ._agg .AxDataSourceChoice =_af .NewCT_AxDataSourceChoice ();_efd ._agg .AxDataSourceChoice .NumRef =_af .NewCT_NumRef ();_efd ._agg .AxDataSourceChoice .NumRef .F =s ;};

// SetDirection changes the direction of the bar chart (bar or column).
func (_dba BarChart )SetDirection (d _af .ST_BarDir ){_dba ._dfg .BarDir .ValAttr =d };func (_egf DateAxis )AxisID ()uint32 {return _egf ._ddf .AxId .ValAttr };

// X returns the inner wrapped XML type.
func (_ccc Line3DChart )X ()*_af .CT_Line3DChart {return _ccc ._fca };func (_da BubbleChart )AddAxis (axis Axis ){_dcf :=_af .NewCT_UnsignedInt ();_dcf .ValAttr =axis .AxisID ();_da ._gfe .AxId =append (_da ._gfe .AxId ,_dcf );};

// X returns the inner wrapped XML type.
func (_efda RadarChartSeries )X ()*_af .CT_RadarSer {return _efda ._dgaf };

// X returns the inner wrapped XML type.
func (_bcb Legend )X ()*_af .CT_Legend {return _bcb ._feab };

// AddSeries adds a default series to an Pie3D chart.
func (_dfd Pie3DChart )AddSeries ()PieChartSeries {_dbfbc :=_af .NewCT_PieSer ();_dfd ._bafg .Ser =append (_dfd ._bafg .Ser ,_dbfbc );_dbfbc .Idx .ValAttr =uint32 (len (_dfd ._bafg .Ser )-1);_dbfbc .Order .ValAttr =uint32 (len (_dfd ._bafg .Ser )-1);_dcb :=PieChartSeries {_dbfbc };
_dcb .InitializeDefaults ();return _dcb ;};

// ScatterChartSeries is the data series for a scatter chart.
type ScatterChartSeries struct{_gfec *_af .CT_ScatterSer };

// AddSeries adds a default series to a Stock chart.
func (_fde StockChart )AddSeries ()LineChartSeries {_daf :=_af .NewCT_LineSer ();_fde ._ccda .Ser =append (_fde ._ccda .Ser ,_daf );_daf .Idx .ValAttr =uint32 (len (_fde ._ccda .Ser )-1);_daf .Order .ValAttr =uint32 (len (_fde ._ccda .Ser )-1);_cagc :=LineChartSeries {_daf };
_cagc .Values ().CreateEmptyNumberCache ();_cagc .Properties ().LineProperties ().SetNoFill ();return _cagc ;};type GridLines struct{_gdd *_af .CT_ChartLines };

// Properties returns the bar chart series shape properties.
func (_ggg PieChartSeries )Properties ()_ea .ShapeProperties {if _ggg ._bfd .SpPr ==nil {_ggg ._bfd .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_ggg ._bfd .SpPr );};func (_abdc RadarChart )AddAxis (axis Axis ){_fbcg :=_af .NewCT_UnsignedInt ();
_fbcg .ValAttr =axis .AxisID ();_abdc ._gce .AxId =append (_abdc ._gce .AxId ,_fbcg );};

// CategoryAxisDataSource specifies the data for an axis.  It's commonly used with
// SetReference to set the axis data to a range of cells.
type CategoryAxisDataSource struct{_agg *_af .CT_AxDataSource };

// X returns the inner wrapped XML type.
func (_abf Marker )X ()*_af .CT_Marker {return _abf ._cac };func (_beee LineChartSeries )CategoryAxis ()CategoryAxisDataSource {if _beee ._agb .Cat ==nil {_beee ._agb .Cat =_af .NewCT_AxDataSource ();};return MakeAxisDataSource (_beee ._agb .Cat );};func (_cfa DateAxis )SetTickLabelPosition (p _af .ST_TickLblPos ){if p ==_af .ST_TickLblPosUnset {_cfa ._ddf .TickLblPos =nil ;
}else {_cfa ._ddf .TickLblPos =_af .NewCT_TickLblPos ();_cfa ._ddf .TickLblPos .ValAttr =p ;};};type chartBase struct{};

// Marker returns the marker properties.
func (_aecd ScatterChartSeries )Marker ()Marker {if _aecd ._gfec .Marker ==nil {_aecd ._gfec .Marker =_af .NewCT_Marker ();};return MakeMarker (_aecd ._gfec .Marker );};func (_cgf DateAxis )MajorGridLines ()GridLines {if _cgf ._ddf .MajorGridlines ==nil {_cgf ._ddf .MajorGridlines =_af .NewCT_ChartLines ();
};return GridLines {_cgf ._ddf .MajorGridlines };};

// X returns the inner wrapped XML type.
func (_bgc DoughnutChart )X ()*_af .CT_DoughnutChart {return _bgc ._ffec };

// AddLegend adds a legend to a chart, replacing any existing legend.
func (_edee Chart )AddLegend ()Legend {_edee ._gdb .Chart .Legend =_af .NewCT_Legend ();_aea :=MakeLegend (_edee ._gdb .Chart .Legend );_aea .InitializeDefaults ();return _aea ;};type ValueAxis struct{_agda *_af .CT_ValAx };func (_fdd Marker )SetSize (sz uint8 ){_fdd ._cac .Size =_af .NewCT_MarkerSize ();
_fdd ._cac .Size .ValAttr =&sz ;};

// InitializeDefaults the bar chart to its defaults
func (_abad PieChart )InitializeDefaults (){_abad ._bad .VaryColors =_af .NewCT_Boolean ();_abad ._bad .VaryColors .ValAttr =_f .Bool (true );};func (_egee Surface3DChart )InitializeDefaults (){_egee ._eaa .Wireframe =_af .NewCT_Boolean ();_egee ._eaa .Wireframe .ValAttr =_f .Bool (false );
_egee ._eaa .BandFmts =_af .NewCT_BandFmts ();for _bba :=0;_bba < 15;_bba ++{_gebf :=_af .NewCT_BandFmt ();_gebf .Idx .ValAttr =uint32 (_bba );_gebf .SpPr =_db .NewCT_ShapeProperties ();_gbe :=_ea .MakeShapeProperties (_gebf .SpPr );_gbe .SetSolidFill (_egee .nextColor (_bba ));
_egee ._eaa .BandFmts .BandFmt =append (_egee ._eaa .BandFmts .BandFmt ,_gebf );};};

// BubbleChartSeries is a series to be used on a Bubble chart.
type BubbleChartSeries struct{_fe *_af .CT_BubbleSer };type DateAxis struct{_ddf *_af .CT_DateAx };func (_ecg LineChartSeries )SetSmooth (b bool ){_ecg ._agb .Smooth =_af .NewCT_Boolean ();_ecg ._agb .Smooth .ValAttr =&b ;};

// X returns the inner wrapped XML type.
func (_aag BarChart )X ()*_af .CT_BarChart {return _aag ._dfg };func (_dge NumberDataSource )ensureChoice (){if _dge ._aga .NumDataSourceChoice ==nil {_dge ._aga .NumDataSourceChoice =_af .NewCT_NumDataSourceChoice ();};};

// AddSeries adds a default series to a Surface chart.
func (_bda SurfaceChart )AddSeries ()SurfaceChartSeries {_ebed :=_bda .nextColor (len (_bda ._ddd .Ser ));_bgb :=_af .NewCT_SurfaceSer ();_bda ._ddd .Ser =append (_bda ._ddd .Ser ,_bgb );_bgb .Idx .ValAttr =uint32 (len (_bda ._ddd .Ser )-1);_bgb .Order .ValAttr =uint32 (len (_bda ._ddd .Ser )-1);
_aecb :=SurfaceChartSeries {_bgb };_aecb .InitializeDefaults ();_aecb .Properties ().LineProperties ().SetSolidFill (_ebed );return _aecb ;};func (_eeb ValueAxis )SetTickLabelPosition (p _af .ST_TickLblPos ){if p ==_af .ST_TickLblPosUnset {_eeb ._agda .TickLblPos =nil ;
}else {_eeb ._agda .TickLblPos =_af .NewCT_TickLblPos ();_eeb ._agda .TickLblPos .ValAttr =p ;};};

// AreaChart is an area chart that has a shaded area underneath a curve.
type AreaChart struct{chartBase ;_c *_af .CT_AreaChart ;};func (_eaf DataLabels )SetShowCategoryName (b bool ){_eaf .ensureChoice ();for _ ,_dad :=range _eaf ._ege .DLblsChoice {if _dad .ShowCatName !=nil {_dad .ShowCatName .ValAttr =_f .Bool (b );return ;
};};_aaf :=&_af .CT_DLblsChoice {};_aaf .ShowCatName =_af .NewCT_Boolean ();_aaf .ShowCatName .ValAttr =_f .Bool (b );_eaf ._ege .DLblsChoice =append (_eaf ._ege .DLblsChoice ,_aaf );};

// X returns the inner wrapped XML type.
func (_edb BarChartSeries )X ()*_af .CT_BarSer {return _edb ._fa };

// AddRadarChart adds a new radar chart to a chart.
func (_dga Chart )AddRadarChart ()RadarChart {_afc :=_af .NewCT_PlotAreaChoice ();_dga ._gdb .Chart .PlotArea .PlotAreaChoice =append (_dga ._gdb .Chart .PlotArea .PlotAreaChoice ,_afc );_afc .RadarChart =_af .NewCT_RadarChart ();_cde :=RadarChart {_gce :_afc .RadarChart };
_cde .InitializeDefaults ();return _cde ;};

// PieOfPieChart is a Pie chart with an extra Pie chart.
type PieOfPieChart struct{chartBase ;_adc *_af .CT_OfPieChart ;};

// SetText sets the series text
func (_aaab LineChartSeries )SetText (s string ){_aaab ._agb .Tx =_af .NewCT_SerTx ();_aaab ._agb .Tx .SerTxChoice .V =&s ;};

// BarChart is a 2D bar chart.
type BarChart struct{chartBase ;_dfg *_af .CT_BarChart ;};

// AddArea3DChart adds a new area chart to a chart.
func (_dbf Chart )AddArea3DChart ()Area3DChart {_aaa (_dbf ._gdb .Chart );_cec :=_af .NewCT_PlotAreaChoice ();_dbf ._gdb .Chart .PlotArea .PlotAreaChoice =append (_dbf ._gdb .Chart .PlotArea .PlotAreaChoice ,_cec );_cec .Area3DChart =_af .NewCT_Area3DChart ();
_ddc :=Area3DChart {_ed :_cec .Area3DChart };_ddc .InitializeDefaults ();return _ddc ;};

// Values returns the bubble size data source.
func (_dg BubbleChartSeries )BubbleSizes ()NumberDataSource {if _dg ._fe .BubbleSize ==nil {_dg ._fe .BubbleSize =_af .NewCT_NumDataSource ();};return MakeNumberDataSource (_dg ._fe .BubbleSize );};func MakeCategoryAxis (x *_af .CT_CatAx )CategoryAxis {return CategoryAxis {x }};


// AddBubbleChart adds a new bubble chart.
func (_cgc Chart )AddBubbleChart ()BubbleChart {_afad :=_af .NewCT_PlotAreaChoice ();_cgc ._gdb .Chart .PlotArea .PlotAreaChoice =append (_cgc ._gdb .Chart .PlotArea .PlotAreaChoice ,_afad );_afad .BubbleChart =_af .NewCT_BubbleChart ();_bg :=BubbleChart {_gfe :_afad .BubbleChart };
_bg .InitializeDefaults ();return _bg ;};

// X returns the inner wrapped XML type.
func (_bfc SurfaceChartSeries )X ()*_af .CT_SurfaceSer {return _bfc ._edgg };

// CategoryAxis returns the category data source.
func (_ebg PieChartSeries )CategoryAxis ()CategoryAxisDataSource {if _ebg ._bfd .Cat ==nil {_ebg ._bfd .Cat =_af .NewCT_AxDataSource ();};return MakeAxisDataSource (_ebg ._bfd .Cat );};

// X returns the inner wrapped XML type.
func (_adcg Title )X ()*_af .CT_Title {return _adcg ._dda };

// SetExplosion sets the value that the segements of the pie are 'exploded' by
func (_eaea PieChartSeries )SetExplosion (v uint32 ){_eaea ._bfd .Explosion =_af .NewCT_UnsignedInt ();_eaea ._bfd .Explosion .ValAttr =v ;};

// PieChart is a Pie chart.
type PieChart struct{chartBase ;_bad *_af .CT_PieChart ;};

// SetText sets the series text
func (_bgf SurfaceChartSeries )SetText (s string ){_bgf ._edgg .Tx =_af .NewCT_SerTx ();_bgf ._edgg .Tx .SerTxChoice .V =&s ;};func (_dgf ValueAxis )MajorGridLines ()GridLines {if _dgf ._agda .MajorGridlines ==nil {_dgf ._agda .MajorGridlines =_af .NewCT_ChartLines ();
};return GridLines {_dgf ._agda .MajorGridlines };};

// SetIndex sets the index of the series
func (_cgca ScatterChartSeries )SetIndex (idx uint32 ){_cgca ._gfec .Idx .ValAttr =idx };

// SetText sets the series text
func (_gcg ScatterChartSeries )SetText (s string ){_gcg ._gfec .Tx =_af .NewCT_SerTx ();_gcg ._gfec .Tx .SerTxChoice .V =&s ;};

// AddSurface3DChart adds a new 3D surface chart to a chart.
func (_gfc Chart )AddSurface3DChart ()Surface3DChart {_eea :=_af .NewCT_PlotAreaChoice ();_gfc ._gdb .Chart .PlotArea .PlotAreaChoice =append (_gfc ._gdb .Chart .PlotArea .PlotAreaChoice ,_eea );_eea .Surface3DChart =_af .NewCT_Surface3DChart ();_aaa (_gfc ._gdb .Chart );
_afaf :=Surface3DChart {_eaa :_eea .Surface3DChart };_afaf .InitializeDefaults ();return _afaf ;};func (_dbfb Legend )SetPosition (p _af .ST_LegendPos ){if p ==_af .ST_LegendPosUnset {_dbfb ._feab .LegendPos =nil ;}else {_dbfb ._feab .LegendPos =_af .NewCT_LegendPos ();
_dbfb ._feab .LegendPos .ValAttr =p ;};};func (_dac Marker )Properties ()_ea .ShapeProperties {if _dac ._cac .SpPr ==nil {_dac ._cac .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_dac ._cac .SpPr );};func (_dag DataLabels )ensureChoice (){if _dag ._ege .DLblsChoice ==nil {_dag ._ege .DLblsChoice =[]*_af .CT_DLblsChoice {};
};};func (_eccd DateAxis )Properties ()_ea .ShapeProperties {if _eccd ._ddf .SpPr ==nil {_eccd ._ddf .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_eccd ._ddf .SpPr );};

// Area3DChart is an area chart that has a shaded area underneath a curve.
type Area3DChart struct{chartBase ;_ed *_af .CT_Area3DChart ;};func (_fcb DataLabels )SetShowLegendKey (b bool ){_fcb .ensureChoice ();for _ ,_cgd :=range _fcb ._ege .DLblsChoice {if _cgd .ShowLegendKey !=nil {_cgd .ShowLegendKey .ValAttr =_f .Bool (b );
return ;};};_gfcb :=&_af .CT_DLblsChoice {};_gfcb .ShowLegendKey =_af .NewCT_Boolean ();_gfcb .ShowLegendKey .ValAttr =_f .Bool (b );_fcb ._ege .DLblsChoice =append (_fcb ._ege .DLblsChoice ,_gfcb );};func (_dbg DateAxis )SetCrosses (axis Axis ){_dbg ._ddf .CrossAx .ValAttr =axis .AxisID ()};
func MakeValueAxis (x *_af .CT_ValAx )ValueAxis {return ValueAxis {x }};func (_cab Legend )SetOverlay (b bool ){_cab ._feab .Overlay =_af .NewCT_Boolean ();_cab ._feab .Overlay .ValAttr =_f .Bool (b );};type SeriesAxis struct{_dcfd *_af .CT_SerAx };

// Marker returns the marker properties.
func (_fda LineChartSeries )Marker ()Marker {if _fda ._agb .Marker ==nil {_fda ._agb .Marker =_af .NewCT_Marker ();};return MakeMarker (_fda ._agb .Marker );};

// InitializeDefaults initializes a bar chart series to the default values.
func (_cg BarChartSeries )InitializeDefaults (){};func (_bd CategoryAxis )SetMinorTickMark (m _af .ST_TickMark ){if m ==_af .ST_TickMarkUnset {_bd ._cf .MinorTickMark =nil ;}else {_bd ._cf .MinorTickMark =_af .NewCT_TickMark ();_bd ._cf .MinorTickMark .ValAttr =m ;
};};

// AddSeries adds a default series to a Bubble chart.
func (_fg BubbleChart )AddSeries ()BubbleChartSeries {_de :=_fg .nextColor (len (_fg ._gfe .Ser ));_dfa :=_af .NewCT_BubbleSer ();_fg ._gfe .Ser =append (_fg ._gfe .Ser ,_dfa );_dfa .Idx .ValAttr =uint32 (len (_fg ._gfe .Ser )-1);_dfa .Order .ValAttr =uint32 (len (_fg ._gfe .Ser )-1);
_agd :=BubbleChartSeries {_dfa };_agd .InitializeDefaults ();_agd .Properties ().SetSolidFill (_de );return _agd ;};

// BarChartSeries is a series to be used on a bar chart.
type BarChartSeries struct{_fa *_af .CT_BarSer };

// X returns the inner wrapped XML type.
func (_eafb LineChartSeries )X ()*_af .CT_LineSer {return _eafb ._agb };

// AddStockChart adds a new stock chart.
func (_def Chart )AddStockChart ()StockChart {_cfc :=_af .NewCT_PlotAreaChoice ();_def ._gdb .Chart .PlotArea .PlotAreaChoice =append (_def ._gdb .Chart .PlotArea .PlotAreaChoice ,_cfc );_cfc .StockChart =_af .NewCT_StockChart ();_dbd :=StockChart {_ccda :_cfc .StockChart };
_dbd .InitializeDefaults ();return _dbd ;};func (_gbbg Title )ParagraphProperties ()_ea .ParagraphProperties {if _gbbg ._dda .Tx ==nil {_gbbg .SetText ("");};if _gbbg ._dda .Tx .TxChoice .Rich .P [0].PPr ==nil {_gbbg ._dda .Tx .TxChoice .Rich .P [0].PPr =_db .NewCT_TextParagraphProperties ();
};return _ea .MakeParagraphProperties (_gbbg ._dda .Tx .TxChoice .Rich .P [0].PPr );};

// PieChartSeries is a series to be used on an Pie chart.
type PieChartSeries struct{_bfd *_af .CT_PieSer };func (_bdc ScatterChart )InitializeDefaults (){_bdc ._ceff .ScatterStyle .ValAttr =_af .ST_ScatterStyleMarker ;};

// Order returns the order of the series
func (_aeae SurfaceChartSeries )Order ()uint32 {return _aeae ._edgg .Order .ValAttr };func (_aec CategoryAxis )MajorGridLines ()GridLines {if _aec ._cf .MajorGridlines ==nil {_aec ._cf .MajorGridlines =_af .NewCT_ChartLines ();};return GridLines {_aec ._cf .MajorGridlines };
};

// AddValueAxis adds a value axis to the chart.
func (_cba Chart )AddValueAxis ()ValueAxis {_gab :=_af .NewCT_ValAx ();if _cba ._gdb .Chart .PlotArea .PlotAreaChoice1 ==nil {_cba ._gdb .Chart .PlotArea .PlotAreaChoice1 =[]*_af .CT_PlotAreaChoice1 {};};_gab .AxId =_af .NewCT_UnsignedInt ();_gab .AxId .ValAttr =0x7FFFFFFF&_ac .Uint32 ();
_cba ._gdb .Chart .PlotArea .PlotAreaChoice1 =append (_cba ._gdb .Chart .PlotArea .PlotAreaChoice1 ,&_af .CT_PlotAreaChoice1 {ValAx :_gab });_gab .Delete =_af .NewCT_Boolean ();_gab .Delete .ValAttr =_f .Bool (false );_gab .Scaling =_af .NewCT_Scaling ();
_gab .Scaling .Orientation =_af .NewCT_Orientation ();_gab .Scaling .Orientation .ValAttr =_af .ST_OrientationMinMax ;_gab .AxSharedChoice =&_af .EG_AxSharedChoice {};_gab .AxSharedChoice .Crosses =_af .NewCT_Crosses ();_gab .AxSharedChoice .Crosses .ValAttr =_af .ST_CrossesAutoZero ;
_gab .CrossBetween =_af .NewCT_CrossBetween ();_gab .CrossBetween .ValAttr =_af .ST_CrossBetweenBetween ;_bdb :=MakeValueAxis (_gab );_bdb .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_ec .LightGray );_bdb .SetMajorTickMark (_af .ST_TickMarkOut );
_bdb .SetMinorTickMark (_af .ST_TickMarkIn );_bdb .SetTickLabelPosition (_af .ST_TickLblPosNextTo );_bdb .Properties ().LineProperties ().SetSolidFill (_ec .Black );_bdb .SetPosition (_af .ST_AxPosL );return _bdb ;};func (_ebbc SeriesAxis )AxisID ()uint32 {return _ebbc ._dcfd .AxId .ValAttr };


// AddLineChart adds a new line chart to a chart.
func (_dfe Chart )AddLineChart ()LineChart {_gc :=_af .NewCT_PlotAreaChoice ();_dfe ._gdb .Chart .PlotArea .PlotAreaChoice =append (_dfe ._gdb .Chart .PlotArea .PlotAreaChoice ,_gc );_gc .LineChart =_af .NewCT_LineChart ();_gc .LineChart .Grouping =_af .NewCT_Grouping ();
_gc .LineChart .Grouping .ValAttr =_af .ST_GroupingStandard ;return LineChart {_geg :_gc .LineChart };};func (_fbg ScatterChartSeries )SetSmooth (b bool ){_fbg ._gfec .Smooth =_af .NewCT_Boolean ();_fbg ._gfec .Smooth .ValAttr =&b ;};

// AddScatterChart adds a scatter (X/Y) chart.
func (_ccg Chart )AddScatterChart ()ScatterChart {_ggb :=_af .NewCT_PlotAreaChoice ();_ccg ._gdb .Chart .PlotArea .PlotAreaChoice =append (_ccg ._gdb .Chart .PlotArea .PlotAreaChoice ,_ggb );_ggb .ScatterChart =_af .NewCT_ScatterChart ();_abc :=ScatterChart {_ceff :_ggb .ScatterChart };
_abc .InitializeDefaults ();return _abc ;};type NumberDataSource struct{_aga *_af .CT_NumDataSource };func (_fbc AreaChart )AddAxis (axis Axis ){_bf :=_af .NewCT_UnsignedInt ();_bf .ValAttr =axis .AxisID ();_fbc ._c .AxId =append (_fbc ._c .AxId ,_bf );
};

// X returns the inner wrapped XML type.
func (_ecd AreaChart )X ()*_af .CT_AreaChart {return _ecd ._c };

// SetType sets the type the secone pie to either pie or bar
func (_ggge PieOfPieChart )SetType (t _af .ST_OfPieType ){_ggge ._adc .OfPieType .ValAttr =t };

// AddSeries adds a default series to a line chart.
func (_bee Line3DChart )AddSeries ()LineChartSeries {_bce :=_bee .nextColor (len (_bee ._fca .Ser ));_fba :=_af .NewCT_LineSer ();_bee ._fca .Ser =append (_bee ._fca .Ser ,_fba );_fba .Idx .ValAttr =uint32 (len (_bee ._fca .Ser )-1);_fba .Order .ValAttr =uint32 (len (_bee ._fca .Ser )-1);
_aed :=LineChartSeries {_fba };_aed .InitializeDefaults ();_aed .Properties ().LineProperties ().SetSolidFill (_bce );_aed .Properties ().SetSolidFill (_bce );return _aed ;};

// Labels returns the data label properties.
func (_bcfa ScatterChartSeries )Labels ()DataLabels {if _bcfa ._gfec .DLbls ==nil {_bcfa ._gfec .DLbls =_af .NewCT_DLbls ();};return MakeDataLabels (_bcfa ._gfec .DLbls );};

// Properties returns the chart's shape properties.
func (_cbba Chart )Properties ()_ea .ShapeProperties {if _cbba ._gdb .SpPr ==nil {_cbba ._gdb .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_cbba ._gdb .SpPr );};

// InitializeDefaults the bar chart to its defaults
func (_ggga RadarChart )InitializeDefaults (){_ggga ._gce .RadarStyle .ValAttr =_af .ST_RadarStyleMarker };

// X returns the inner wrapped XML type.
func (_egb SeriesAxis )X ()*_af .CT_SerAx {return _egb ._dcfd };

// Values returns the value data source.
func (_gd AreaChartSeries )Values ()NumberDataSource {if _gd ._fc .Val ==nil {_gd ._fc .Val =_af .NewCT_NumDataSource ();};return MakeNumberDataSource (_gd ._fc .Val );};

// AddSeries adds a default series to a line chart.
func (_fcc LineChart )AddSeries ()LineChartSeries {_dee :=_fcc .nextColor (len (_fcc ._geg .Ser ));_bafe :=_af .NewCT_LineSer ();_fcc ._geg .Ser =append (_fcc ._geg .Ser ,_bafe );_bafe .Idx .ValAttr =uint32 (len (_fcc ._geg .Ser )-1);_bafe .Order .ValAttr =uint32 (len (_fcc ._geg .Ser )-1);
_fbfa :=LineChartSeries {_bafe };_fbfa .InitializeDefaults ();_fbfa .Properties ().LineProperties ().SetSolidFill (_dee );return _fbfa ;};

// SetOrder sets the order of the series
func (_eabf ScatterChartSeries )SetOrder (idx uint32 ){_eabf ._gfec .Order .ValAttr =idx };

// RemoveTitle removes any existing title from the chart.
func (_ecaf Chart )RemoveTitle (){_ecaf ._gdb .Chart .Title =nil ;_ecaf ._gdb .Chart .AutoTitleDeleted =_af .NewCT_Boolean ();_ecaf ._gdb .Chart .AutoTitleDeleted .ValAttr =_f .Bool (true );};func (_gdfc ValueAxis )SetPosition (p _af .ST_AxPos ){_gdfc ._agda .AxPos =_af .NewCT_AxPos ();
_gdfc ._agda .AxPos .ValAttr =p ;};

// InitializeDefaults the bar chart to its defaults
func (_ecf Bar3DChart )InitializeDefaults (){_ecf .SetDirection (_af .ST_BarDirCol )};

// Bar3DChart is a 3D bar chart.
type Bar3DChart struct{chartBase ;_ag *_af .CT_Bar3DChart ;};

// SetHoleSize controls the hole size in the pie chart and is measured in percent.
func (_fgf DoughnutChart )SetHoleSize (pct uint8 ){if _fgf ._ffec .HoleSize ==nil {_fgf ._ffec .HoleSize =_af .NewCT_HoleSize ();};if _fgf ._ffec .HoleSize .ValAttr ==nil {_fgf ._ffec .HoleSize .ValAttr =&_af .ST_HoleSize {};};_fgf ._ffec .HoleSize .ValAttr .ST_HoleSizeUByte =&pct ;
};

// X returns the inner wrapped XML type.
func (_afa AreaChartSeries )X ()*_af .CT_AreaSer {return _afa ._fc };

// Properties returns the bar chart series shape properties.
func (_gg AreaChartSeries )Properties ()_ea .ShapeProperties {if _gg ._fc .SpPr ==nil {_gg ._fc .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_gg ._fc .SpPr );};

// AddSeries adds a default series to an Pie chart.
func (_ddce PieChart )AddSeries ()PieChartSeries {_fbe :=_af .NewCT_PieSer ();_ddce ._bad .Ser =append (_ddce ._bad .Ser ,_fbe );_fbe .Idx .ValAttr =uint32 (len (_ddce ._bad .Ser )-1);_fbe .Order .ValAttr =uint32 (len (_ddce ._bad .Ser )-1);_gbba :=PieChartSeries {_fbe };
_gbba .InitializeDefaults ();return _gbba ;};

// SetValues sets values directly on a source.
func (_agc NumberDataSource )SetValues (v []float64 ){_agc .ensureChoice ();_agc ._aga .NumDataSourceChoice .NumRef =nil ;_agc ._aga .NumDataSourceChoice .NumLit =_af .NewCT_NumData ();_agc ._aga .NumDataSourceChoice .NumLit .PtCount =_af .NewCT_UnsignedInt ();
_agc ._aga .NumDataSourceChoice .NumLit .PtCount .ValAttr =uint32 (len (v ));for _egeg ,_efec :=range v {_agc ._aga .NumDataSourceChoice .NumLit .Pt =append (_agc ._aga .NumDataSourceChoice .NumLit .Pt ,&_af .CT_NumVal {IdxAttr :uint32 (_egeg ),V :_d .Sprintf ("\u0025\u0067",_efec )});
};};

// Index returns the index of the series
func (_aagc SurfaceChartSeries )Index ()uint32 {return _aagc ._edgg .Idx .ValAttr };func MakeTitle (x *_af .CT_Title )Title {return Title {x }};

// AddSeries adds a default series to a Scatter chart.
func (_gda ScatterChart )AddSeries ()ScatterChartSeries {_cgg :=_gda .nextColor (len (_gda ._ceff .Ser ));_bagb :=_af .NewCT_ScatterSer ();_gda ._ceff .Ser =append (_gda ._ceff .Ser ,_bagb );_bagb .Idx .ValAttr =uint32 (len (_gda ._ceff .Ser )-1);_bagb .Order .ValAttr =uint32 (len (_gda ._ceff .Ser )-1);
_fgb :=ScatterChartSeries {_bagb };_fgb .InitializeDefaults ();_fgb .Marker ().Properties ().LineProperties ().SetSolidFill (_cgg );_fgb .Marker ().Properties ().SetSolidFill (_cgg );return _fgb ;};

// AddPieOfPieChart adds a new pie chart to a chart.
func (_eead Chart )AddPieOfPieChart ()PieOfPieChart {_dcg :=_af .NewCT_PlotAreaChoice ();_eead ._gdb .Chart .PlotArea .PlotAreaChoice =append (_eead ._gdb .Chart .PlotArea .PlotAreaChoice ,_dcg );_dcg .OfPieChart =_af .NewCT_OfPieChart ();_gff :=PieOfPieChart {_adc :_dcg .OfPieChart };
_gff .InitializeDefaults ();return _gff ;};func (_bedd Title )RunProperties ()_ea .RunProperties {if _bedd ._dda .Tx ==nil {_bedd .SetText ("");};if _bedd ._dda .Tx .TxChoice .Rich .P [0].EG_TextRun [0].TextRunChoice .R .RPr ==nil {_bedd ._dda .Tx .TxChoice .Rich .P [0].EG_TextRun [0].TextRunChoice .R .RPr =_db .NewCT_TextCharacterProperties ();
};return _ea .MakeRunProperties (_bedd ._dda .Tx .TxChoice .Rich .P [0].EG_TextRun [0].TextRunChoice .R .RPr );};

// Properties returns the line chart series shape properties.
func (_geb ScatterChartSeries )Properties ()_ea .ShapeProperties {if _geb ._gfec .SpPr ==nil {_geb ._gfec .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_geb ._gfec .SpPr );};

// X returns the inner wrapped XML type.
func (_ccce PieChartSeries )X ()*_af .CT_PieSer {return _ccce ._bfd };func (_edf LineChartSeries )Values ()NumberDataSource {if _edf ._agb .Val ==nil {_edf ._agb .Val =_af .NewCT_NumDataSource ();};return MakeNumberDataSource (_edf ._agb .Val );};

// SetIndex sets the index of the series
func (_gece SurfaceChartSeries )SetIndex (idx uint32 ){_gece ._edgg .Idx .ValAttr =idx };

// DoughnutChart is a Doughnut chart.
type DoughnutChart struct{chartBase ;_ffec *_af .CT_DoughnutChart ;};

// SetLabelReference is used to set the source data to a range of cells
// containing strings.
func (_dec CategoryAxisDataSource )SetLabelReference (s string ){_dec ._agg .AxDataSourceChoice =_af .NewCT_AxDataSourceChoice ();_dec ._agg .AxDataSourceChoice .StrRef =_af .NewCT_StrRef ();_dec ._agg .AxDataSourceChoice .StrRef .F =s ;};type Title struct{_dda *_af .CT_Title };


// BubbleChart is a 2D Bubble chart.
type BubbleChart struct{chartBase ;_gfe *_af .CT_BubbleChart ;};

// CategoryAxis returns the category data source.
func (_add RadarChartSeries )CategoryAxis ()CategoryAxisDataSource {if _add ._dgaf .Cat ==nil {_add ._dgaf .Cat =_af .NewCT_AxDataSource ();};return MakeAxisDataSource (_add ._dgaf .Cat );};func (_aad CategoryAxis )SetTickLabelPosition (p _af .ST_TickLblPos ){if p ==_af .ST_TickLblPosUnset {_aad ._cf .TickLblPos =nil ;
}else {_aad ._cf .TickLblPos =_af .NewCT_TickLblPos ();_aad ._cf .TickLblPos .ValAttr =p ;};};

// AddSeries adds a default series to a bar chart.
func (_eca Bar3DChart )AddSeries ()BarChartSeries {_bed :=_eca .nextColor (len (_eca ._ag .Ser ));_ge :=_af .NewCT_BarSer ();_eca ._ag .Ser =append (_eca ._ag .Ser ,_ge );_ge .Idx .ValAttr =uint32 (len (_eca ._ag .Ser )-1);_ge .Order .ValAttr =uint32 (len (_eca ._ag .Ser )-1);
_gf :=BarChartSeries {_ge };_gf .InitializeDefaults ();_gf .Properties ().SetSolidFill (_bed );return _gf ;};

// Properties returns the bar chart series shape properties.
func (_cbe BarChartSeries )Properties ()_ea .ShapeProperties {if _cbe ._fa .SpPr ==nil {_cbe ._fa .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_cbe ._fa .SpPr );};

// X returns the inner wrapped XML type.
func (_dd Area3DChart )X ()*_af .CT_Area3DChart {return _dd ._ed };func (_ece Marker )SetSymbol (s _af .ST_MarkerStyle ){if s ==_af .ST_MarkerStyleUnset {_ece ._cac .Symbol =nil ;}else {_ece ._cac .Symbol =_af .NewCT_MarkerStyle ();_ece ._cac .Symbol .ValAttr =s ;
};};type LineChart struct{chartBase ;_geg *_af .CT_LineChart ;};

// InitializeDefaults initializes a Bubble chart series to the default values.
func (_gb BubbleChartSeries )InitializeDefaults (){};

// AddCategoryAxis adds a category axis.
func (_bgd Chart )AddCategoryAxis ()CategoryAxis {_agdb :=_af .NewCT_CatAx ();if _bgd ._gdb .Chart .PlotArea .PlotAreaChoice1 ==nil {_bgd ._gdb .Chart .PlotArea .PlotAreaChoice1 =[]*_af .CT_PlotAreaChoice1 {};};_agdb .AxId =_af .NewCT_UnsignedInt ();_agdb .AxId .ValAttr =0x7FFFFFFF&_ac .Uint32 ();
_bgd ._gdb .Chart .PlotArea .PlotAreaChoice1 =append (_bgd ._gdb .Chart .PlotArea .PlotAreaChoice1 ,&_af .CT_PlotAreaChoice1 {CatAx :_agdb });_agdb .Auto =_af .NewCT_Boolean ();_agdb .Auto .ValAttr =_f .Bool (true );_agdb .Delete =_af .NewCT_Boolean ();
_agdb .Delete .ValAttr =_f .Bool (false );_gcc :=MakeCategoryAxis (_agdb );_gcc .InitializeDefaults ();return _gcc ;};

// SetValues is used to set the source data to a set of values.
func (_cd CategoryAxisDataSource )SetValues (v []string ){_cd ._agg .AxDataSourceChoice =_af .NewCT_AxDataSourceChoice ();_cd ._agg .AxDataSourceChoice .StrLit =_af .NewCT_StrData ();_cd ._agg .AxDataSourceChoice .StrLit .PtCount =_af .NewCT_UnsignedInt ();
_cd ._agg .AxDataSourceChoice .StrLit .PtCount .ValAttr =uint32 (len (v ));for _cc ,_ffbc :=range v {_cd ._agg .AxDataSourceChoice .StrLit .Pt =append (_cd ._agg .AxDataSourceChoice .StrLit .Pt ,&_af .CT_StrVal {IdxAttr :uint32 (_cc ),V :_ffbc });};};func (_bceg NumberDataSource )SetReference (s string ){_bceg .ensureChoice ();
if _bceg ._aga .NumDataSourceChoice .NumRef ==nil {_bceg ._aga .NumDataSourceChoice .NumRef =_af .NewCT_NumRef ();};_bceg ._aga .NumDataSourceChoice .NumRef .F =s ;};

// CategoryAxis returns the category data source.
func (_cad BubbleChartSeries )CategoryAxis ()CategoryAxisDataSource {if _cad ._fe .XVal ==nil {_cad ._fe .XVal =_af .NewCT_AxDataSource ();};return MakeAxisDataSource (_cad ._fe .XVal );};

// CreateEmptyNumberCache creates an empty number cache, which is used sometimes
// to increase file format compatibility.  It should actually contain the
// computed cell data, but just creating an empty one is good enough.
func (_aggg NumberDataSource )CreateEmptyNumberCache (){_aggg .ensureChoice ();if _aggg ._aga .NumDataSourceChoice .NumRef ==nil {_aggg ._aga .NumDataSourceChoice .NumRef =_af .NewCT_NumRef ();};_aggg ._aga .NumDataSourceChoice .NumLit =nil ;_aggg ._aga .NumDataSourceChoice .NumRef .NumCache =_af .NewCT_NumData ();
_aggg ._aga .NumDataSourceChoice .NumRef .NumCache .PtCount =_af .NewCT_UnsignedInt ();_aggg ._aga .NumDataSourceChoice .NumRef .NumCache .PtCount .ValAttr =0;};func MakeDataLabels (x *_af .CT_DLbls )DataLabels {return DataLabels {x }};

// SetText sets the series text.
func (_ad BubbleChartSeries )SetText (s string ){_ad ._fe .Tx =_af .NewCT_SerTx ();_ad ._fe .Tx .SerTxChoice .V =&s ;};func (_fbf CategoryAxis )SetCrosses (axis Axis ){_fbf ._cf .AxSharedChoice =_af .NewEG_AxSharedChoice ();_fbf ._cf .AxSharedChoice .Crosses =_af .NewCT_Crosses ();
_fbf ._cf .AxSharedChoice .Crosses .ValAttr =_af .ST_CrossesAutoZero ;_fbf ._cf .CrossAx .ValAttr =axis .AxisID ();};

// Index returns the index of the series
func (_caca ScatterChartSeries )Index ()uint32 {return _caca ._gfec .Idx .ValAttr };

// SetOrder sets the order of the series
func (_aff SurfaceChartSeries )SetOrder (idx uint32 ){_aff ._edgg .Order .ValAttr =idx };

// Properties returns the bar chart series shape properties.
func (_bgg RadarChartSeries )Properties ()_ea .ShapeProperties {if _bgg ._dgaf .SpPr ==nil {_bgg ._dgaf .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_bgg ._dgaf .SpPr );};

// X returns the inner wrapped XML type.
func (_ggfd RadarChart )X ()*_af .CT_RadarChart {return _ggfd ._gce };type CategoryAxis struct{_cf *_af .CT_CatAx };func (_faf Legend )InitializeDefaults (){_faf .SetPosition (_af .ST_LegendPosR );_faf .SetOverlay (false );_faf .Properties ().SetNoFill ();
_faf .Properties ().LineProperties ().SetNoFill ();};

// RadarChartSeries is a series to be used on an Radar chart.
type RadarChartSeries struct{_dgaf *_af .CT_RadarSer };

// AddBarChart adds a new bar chart to a chart.
func (_eccb Chart )AddBarChart ()BarChart {_eag :=_af .NewCT_PlotAreaChoice ();_eccb ._gdb .Chart .PlotArea .PlotAreaChoice =append (_eccb ._gdb .Chart .PlotArea .PlotAreaChoice ,_eag );_eag .BarChart =_af .NewCT_BarChart ();_eag .BarChart .Grouping =_af .NewCT_BarGrouping ();
_eag .BarChart .Grouping .ValAttr =_af .ST_BarGroupingStandard ;_ebfa :=BarChart {_dfg :_eag .BarChart };_ebfa .InitializeDefaults ();return _ebfa ;};

// SetText sets the series text.
func (_eada PieChartSeries )SetText (s string ){_eada ._bfd .Tx =_af .NewCT_SerTx ();_eada ._bfd .Tx .SerTxChoice .V =&s ;};type ScatterChart struct{chartBase ;_ceff *_af .CT_ScatterChart ;};func (_ccb GridLines )Properties ()_ea .ShapeProperties {if _ccb ._gdd .SpPr ==nil {_ccb ._gdd .SpPr =_db .NewCT_ShapeProperties ();
};return _ea .MakeShapeProperties (_ccb ._gdd .SpPr );};

// AddAxis adds an axis to a Surface chart.
func (_addd Surface3DChart )AddAxis (axis Axis ){_eaga :=_af .NewCT_UnsignedInt ();_eaga .ValAttr =axis .AxisID ();_addd ._eaa .AxId =append (_addd ._eaa .AxId ,_eaga );};

// X returns the inner wrapped XML type.
func (_bb BubbleChartSeries )X ()*_af .CT_BubbleSer {return _bb ._fe };

// LineChartSeries is the data series for a line chart.
type LineChartSeries struct{_agb *_af .CT_LineSer };

// X returns the inner wrapped XML type.
func (_ecbf Pie3DChart )X ()*_af .CT_Pie3DChart {return _ecbf ._bafg };

// Properties returns the line chart series shape properties.
func (_dcc SurfaceChartSeries )Properties ()_ea .ShapeProperties {if _dcc ._edgg .SpPr ==nil {_dcc ._edgg .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_dcc ._edgg .SpPr );};

// AddDateAxis adds a value axis to the chart.
func (_efe Chart )AddDateAxis ()DateAxis {_gec :=_af .NewCT_DateAx ();if _efe ._gdb .Chart .PlotArea .PlotAreaChoice1 ==nil {_efe ._gdb .Chart .PlotArea .PlotAreaChoice1 =[]*_af .CT_PlotAreaChoice1 {};};_gec .AxId =_af .NewCT_UnsignedInt ();_gec .AxId .ValAttr =0x7FFFFFFF&_ac .Uint32 ();
_efe ._gdb .Chart .PlotArea .PlotAreaChoice1 =append (_efe ._gdb .Chart .PlotArea .PlotAreaChoice1 ,&_af .CT_PlotAreaChoice1 {DateAx :_gec });_gec .Delete =_af .NewCT_Boolean ();_gec .Delete .ValAttr =_f .Bool (false );_gec .Scaling =_af .NewCT_Scaling ();
_gec .Scaling .Orientation =_af .NewCT_Orientation ();_gec .Scaling .Orientation .ValAttr =_af .ST_OrientationMinMax ;_gec .AxSharedChoice =&_af .EG_AxSharedChoice {};_gec .AxSharedChoice .Crosses =_af .NewCT_Crosses ();_gec .AxSharedChoice .Crosses .ValAttr =_af .ST_CrossesAutoZero ;
_cbdc :=DateAxis {_gec };_cbdc .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_ec .LightGray );_cbdc .SetMajorTickMark (_af .ST_TickMarkOut );_cbdc .SetMinorTickMark (_af .ST_TickMarkIn );_cbdc .SetTickLabelPosition (_af .ST_TickLblPosNextTo );
_cbdc .Properties ().LineProperties ().SetSolidFill (_ec .Black );_cbdc .SetPosition (_af .ST_AxPosL );return _cbdc ;};type nullAxis byte ;

// AddAxis adds an axis to a Scatter chart.
func (_fbab ScatterChart )AddAxis (axis Axis ){_fbfe :=_af .NewCT_UnsignedInt ();_fbfe .ValAttr =axis .AxisID ();_fbab ._ceff .AxId =append (_fbab ._ceff .AxId ,_fbfe );};

// AddAxis adds an axis to a Surface chart.
func (_gcbg SurfaceChart )AddAxis (axis Axis ){_efa :=_af .NewCT_UnsignedInt ();_efa .ValAttr =axis .AxisID ();_gcbg ._ddd .AxId =append (_gcbg ._ddd .AxId ,_efa );};func (_adg ScatterChartSeries )CategoryAxis ()CategoryAxisDataSource {if _adg ._gfec .XVal ==nil {_adg ._gfec .XVal =_af .NewCT_AxDataSource ();
};return MakeAxisDataSource (_adg ._gfec .XVal );};

// SetText sets the series text.
func (_cbb AreaChartSeries )SetText (s string ){_cbb ._fc .Tx =_af .NewCT_SerTx ();_cbb ._fc .Tx .SerTxChoice .V =&s ;};

// X returns the inner wrapped XML type.
func (_fgc PieChart )X ()*_af .CT_PieChart {return _fgc ._bad };func (_fd DataLabels )SetPosition (p _af .ST_DLblPos ){_fd .ensureChoice ();for _ ,_gfd :=range _fd ._ege .DLblsChoice {if _gfd .DLblPos !=nil {_gfd .DLblPos .ValAttr =p ;return ;};};_egg :=&_af .CT_DLblsChoice {};
_egg .DLblPos =_af .NewCT_DLblPos ();_egg .DLblPos .ValAttr =p ;_fd ._ege .DLblsChoice =append (_fd ._ege .DLblsChoice ,_egg );};

// Pie3DChart is a Pie3D chart.
type Pie3DChart struct{chartBase ;_bafg *_af .CT_Pie3DChart ;};

// SetText sets the series text.
func (_fafc RadarChartSeries )SetText (s string ){_fafc ._dgaf .Tx =_af .NewCT_SerTx ();_fafc ._dgaf .Tx .SerTxChoice .V =&s ;};func (_ecc nullAxis )AxisID ()uint32 {return 0};func (_aca DataLabels )SetShowPercent (b bool ){_aca .ensureChoice ();for _ ,_aeab :=range _aca ._ege .DLblsChoice {if _aeab .ShowPercent !=nil {_aeab .ShowPercent .ValAttr =_f .Bool (b );
return ;};};_gbb :=&_af .CT_DLblsChoice {};_gbb .ShowPercent =_af .NewCT_Boolean ();_gbb .ShowPercent .ValAttr =_f .Bool (b );_aca ._ege .DLblsChoice =append (_aca ._ege .DLblsChoice ,_gbb );};

// InitializeDefaults initializes an Radar series to the default values.
func (_deb RadarChartSeries )InitializeDefaults (){};

// Properties returns the line chart series shape properties.
func (_bdbe LineChartSeries )Properties ()_ea .ShapeProperties {if _bdbe ._agb .SpPr ==nil {_bdbe ._agb .SpPr =_db .NewCT_ShapeProperties ();};return _ea .MakeShapeProperties (_bdbe ._agb .SpPr );};type Line3DChart struct{chartBase ;_fca *_af .CT_Line3DChart ;
};

// X returns the inner wrapped XML type.
func (_dbcg SurfaceChart )X ()*_af .CT_SurfaceChart {return _dbcg ._ddd };

// X returns the inner wrapped XML type.
func (_cbaa ScatterChartSeries )X ()*_af .CT_ScatterSer {return _cbaa ._gfec };func (_aege SurfaceChartSeries )CategoryAxis ()CategoryAxisDataSource {if _aege ._edgg .Cat ==nil {_aege ._edgg .Cat =_af .NewCT_AxDataSource ();};return MakeAxisDataSource (_aege ._edgg .Cat );
};type DataLabels struct{_ege *_af .CT_DLbls };

// AddTitle sets a new title on the chart.
func (_ffc Chart )AddTitle ()Title {_ffc ._gdb .Chart .Title =_af .NewCT_Title ();_ffc ._gdb .Chart .Title .Overlay =_af .NewCT_Boolean ();_ffc ._gdb .Chart .Title .Overlay .ValAttr =_f .Bool (false );_ffc ._gdb .Chart .AutoTitleDeleted =_af .NewCT_Boolean ();
_ffc ._gdb .Chart .AutoTitleDeleted .ValAttr =_f .Bool (false );_dbc :=MakeTitle (_ffc ._gdb .Chart .Title );_dbc .InitializeDefaults ();return _dbc ;};

// AddSeries adds a default series to a Surface chart.
func (_fffe Surface3DChart )AddSeries ()SurfaceChartSeries {_fdg :=_fffe .nextColor (len (_fffe ._eaa .Ser ));_cgfa :=_af .NewCT_SurfaceSer ();_fffe ._eaa .Ser =append (_fffe ._eaa .Ser ,_cgfa );_cgfa .Idx .ValAttr =uint32 (len (_fffe ._eaa .Ser )-1);_cgfa .Order .ValAttr =uint32 (len (_fffe ._eaa .Ser )-1);
_dae :=SurfaceChartSeries {_cgfa };_dae .InitializeDefaults ();_dae .Properties ().LineProperties ().SetSolidFill (_fdg );return _dae ;};

// InitializeDefaults the bar chart to its defaults
func (_dc Area3DChart )InitializeDefaults (){};func (_abe SeriesAxis )SetCrosses (axis Axis ){_abe ._dcfd .CrossAx .ValAttr =axis .AxisID ()};

// AreaChartSeries is a series to be used on an area chart.
type AreaChartSeries struct{_fc *_af .CT_AreaSer };

// InitializeDefaults initializes an area series to the default values.
func (_ab AreaChartSeries )InitializeDefaults (){};

// InitializeDefaults the Stock chart to its defaults
func (_fee StockChart )InitializeDefaults (){_fee ._ccda .HiLowLines =_af .NewCT_ChartLines ();_fee ._ccda .UpDownBars =_af .NewCT_UpDownBars ();_fee ._ccda .UpDownBars .GapWidth =_af .NewCT_GapAmount ();_fee ._ccda .UpDownBars .GapWidth .ValAttr =&_af .ST_GapAmount {};
_fee ._ccda .UpDownBars .GapWidth .ValAttr .ST_GapAmountUShort =_f .Uint16 (150);_fee ._ccda .UpDownBars .UpBars =_af .NewCT_UpDownBar ();_fee ._ccda .UpDownBars .DownBars =_af .NewCT_UpDownBar ();};

// AddSurfaceChart adds a new surface chart to a chart.
func (_ead Chart )AddSurfaceChart ()SurfaceChart {_fadd :=_af .NewCT_PlotAreaChoice ();_ead ._gdb .Chart .PlotArea .PlotAreaChoice =append (_ead ._gdb .Chart .PlotArea .PlotAreaChoice ,_fadd );_fadd .SurfaceChart =_af .NewCT_SurfaceChart ();_aaa (_ead ._gdb .Chart );
_ead ._gdb .Chart .View3D .RotX .ValAttr =_f .Int8 (90);_ead ._gdb .Chart .View3D .RotY .ValAttr =_f .Uint16 (0);_ead ._gdb .Chart .View3D .Perspective =_af .NewCT_Perspective ();_ead ._gdb .Chart .View3D .Perspective .ValAttr =_f .Uint8 (0);_gfee :=SurfaceChart {_ddd :_fadd .SurfaceChart };
_gfee .InitializeDefaults ();return _gfee ;};

// Axis is the interface implemented by different axes when assigning to a
// chart.
type Axis interface{AxisID ()uint32 ;};func (_ecdg Title )SetText (s string ){if _ecdg ._dda .Tx ==nil {_ecdg ._dda .Tx =_af .NewCT_Tx ();};if _ecdg ._dda .Tx .TxChoice .Rich ==nil {_ecdg ._dda .Tx .TxChoice .Rich =_db .NewCT_TextBody ();};var _ccgg *_db .CT_TextParagraph ;
if len (_ecdg ._dda .Tx .TxChoice .Rich .P )==0{_ccgg =_db .NewCT_TextParagraph ();_ecdg ._dda .Tx .TxChoice .Rich .P =[]*_db .CT_TextParagraph {_ccgg };}else {_ccgg =_ecdg ._dda .Tx .TxChoice .Rich .P [0];};var _bcg *_db .EG_TextRun ;if len (_ccgg .EG_TextRun )==0{_bcg =_db .NewEG_TextRun ();
_ccgg .EG_TextRun =[]*_db .EG_TextRun {_bcg };}else {_bcg =_ccgg .EG_TextRun [0];};if _bcg .TextRunChoice .R ==nil {_bcg .TextRunChoice .R =_db .NewCT_RegularTextRun ();};_bcg .TextRunChoice .R .T =s ;};func (_dfae Title )InitializeDefaults (){_dfae .SetText ("\u0054\u0069\u0074l\u0065");
_dfae .RunProperties ().SetSize (16*_e .Point );_dfae .RunProperties ().SetSolidFill (_ec .Black );_dfae .RunProperties ().SetFont ("\u0043\u0061\u006c\u0069\u0062\u0020\u0072\u0069");_dfae .RunProperties ().SetBold (false );};func (_ffd DataLabels )SetShowValue (b bool ){_ffd .ensureChoice ();
for _ ,_cfb :=range _ffd ._ege .DLblsChoice {if _cfb .ShowVal !=nil {_cfb .ShowVal .ValAttr =_f .Bool (b );return ;};};_ffbg :=&_af .CT_DLblsChoice {};_ffbg .ShowVal =_af .NewCT_Boolean ();_ffbg .ShowVal .ValAttr =_f .Bool (b );_ffd ._ege .DLblsChoice =append (_ffd ._ege .DLblsChoice ,_ffbg );
};func (_ef CategoryAxis )InitializeDefaults (){_ef .SetPosition (_af .ST_AxPosB );_ef .SetMajorTickMark (_af .ST_TickMarkOut );_ef .SetMinorTickMark (_af .ST_TickMarkIn );_ef .SetTickLabelPosition (_af .ST_TickLblPosNextTo );_ef .MajorGridLines ().Properties ().LineProperties ().SetSolidFill (_ec .LightGray );
_ef .Properties ().LineProperties ().SetSolidFill (_ec .Black );};

// AddAxis adds an axis to a line chart.
func (_abd Line3DChart )AddAxis (axis Axis ){_efdg :=_af .NewCT_UnsignedInt ();_efdg .ValAttr =axis .AxisID ();_abd ._fca .AxId =append (_abd ._fca .AxId ,_efdg );};var _ccd =[]_ec .Color {_ec .RGB (0x33,0x66,0xcc),_ec .RGB (0xDC,0x39,0x12),_ec .RGB (0xFF,0x99,0x00),_ec .RGB (0x10,0x96,0x18),_ec .RGB (0x99,0x00,0x99),_ec .RGB (0x3B,0x3E,0xAC),_ec .RGB (0x00,0x99,0xC6),_ec .RGB (0xDD,0x44,0x77),_ec .RGB (0x66,0xAA,0x00),_ec .RGB (0xB8,0x2E,0x2E),_ec .RGB (0x31,0x63,0x95),_ec .RGB (0x99,0x44,0x99),_ec .RGB (0x22,0xAA,0x99),_ec .RGB (0xAA,0xAA,0x11),_ec .RGB (0x66,0x33,0xCC),_ec .RGB (0xE6,0x73,0x00),_ec .RGB (0x8B,0x07,0x07),_ec .RGB (0x32,0x92,0x62),_ec .RGB (0x55,0x74,0xA6),_ec .RGB (0x3B,0x3E,0xAC)};
func (_dff DateAxis )SetMajorTickMark (m _af .ST_TickMark ){if m ==_af .ST_TickMarkUnset {_dff ._ddf .MajorTickMark =nil ;}else {_dff ._ddf .MajorTickMark =_af .NewCT_TickMark ();_dff ._ddf .MajorTickMark .ValAttr =m ;};};func (_efca ValueAxis )SetMinorTickMark (m _af .ST_TickMark ){if m ==_af .ST_TickMarkUnset {_efca ._agda .MinorTickMark =nil ;
}else {_efca ._agda .MinorTickMark =_af .NewCT_TickMark ();_efca ._agda .MinorTickMark .ValAttr =m ;};};

// InitializeDefaults the bar chart to its defaults
func (_feb Pie3DChart )InitializeDefaults (){_feb ._bafg .VaryColors =_af .NewCT_Boolean ();_feb ._bafg .VaryColors .ValAttr =_f .Bool (true );};

// AddDoughnutChart adds a new doughnut (pie with a hole in the center) chart to a chart.
func (_cefb Chart )AddDoughnutChart ()DoughnutChart {_eab :=_af .NewCT_PlotAreaChoice ();_cefb ._gdb .Chart .PlotArea .PlotAreaChoice =append (_cefb ._gdb .Chart .PlotArea .PlotAreaChoice ,_eab );_eab .DoughnutChart =_af .NewCT_DoughnutChart ();_baa :=DoughnutChart {_ffec :_eab .DoughnutChart };
_baa .InitializeDefaults ();return _baa ;};func (_eg BarChart )AddAxis (axis Axis ){_ba :=_af .NewCT_UnsignedInt ();_ba .ValAttr =axis .AxisID ();_eg ._dfg .AxId =append (_eg ._dfg .AxId ,_ba );};func (_cbab DateAxis )SetMinorTickMark (m _af .ST_TickMark ){if m ==_af .ST_TickMarkUnset {_cbab ._ddf .MinorTickMark =nil ;
}else {_cbab ._ddf .MinorTickMark =_af .NewCT_TickMark ();_cbab ._ddf .MinorTickMark .ValAttr =m ;};};func (_gaaa ValueAxis )SetCrosses (axis Axis ){_gaaa ._agda .CrossAx .ValAttr =axis .AxisID ()};func (_cca LineChartSeries )InitializeDefaults (){_cca .Properties ().LineProperties ().SetWidth (1*_e .Point );
_cca .Properties ().LineProperties ().SetSolidFill (_ec .Black );_cca .Properties ().LineProperties ().SetJoin (_ea .LineJoinRound );_cca .Marker ().SetSymbol (_af .ST_MarkerStyleNone );_cca .Labels ().SetShowLegendKey (false );_cca .Labels ().SetShowValue (false );
_cca .Labels ().SetShowPercent (false );_cca .Labels ().SetShowCategoryName (false );_cca .Labels ().SetShowSeriesName (false );_cca .Labels ().SetShowLeaderLines (false );};

// Values returns the value data source.
func (_fccc PieChartSeries )Values ()NumberDataSource {if _fccc ._bfd .Val ==nil {_fccc ._bfd .Val =_af .NewCT_NumDataSource ();};return MakeNumberDataSource (_fccc ._bfd .Val );};

// X returns the inner wrapped XML type.
func (_cddb DateAxis )X ()*_af .CT_DateAx {return _cddb ._ddf };func (_aac DataLabels )SetShowSeriesName (b bool ){_aac .ensureChoice ();for _ ,_egd :=range _aac ._ege .DLblsChoice {if _egd .ShowSerName !=nil {_egd .ShowSerName .ValAttr =_f .Bool (b );
return ;};};_afbf :=&_af .CT_DLblsChoice {};_afbf .ShowSerName =_af .NewCT_Boolean ();_afbf .ShowSerName .ValAttr =_f .Bool (b );_aac ._ege .DLblsChoice =append (_aac ._ege .DLblsChoice ,_afbf );};func (_cbde DataLabels )SetShowLeaderLines (b bool ){_cbde .ensureChoice ();
for _ ,_aef :=range _cbde ._ege .DLblsChoice {if _aef .ShowLeaderLines !=nil {_aef .ShowLeaderLines .ValAttr =_f .Bool (b );return ;};};_dea :=&_af .CT_DLblsChoice {};_dea .ShowLeaderLines =_af .NewCT_Boolean ();_dea .ShowLeaderLines .ValAttr =_f .Bool (b );
_cbde ._ege .DLblsChoice =append (_cbde ._ege .DLblsChoice ,_dea );};func (_gdg ScatterChartSeries )Values ()NumberDataSource {if _gdg ._gfec .YVal ==nil {_gdg ._gfec .YVal =_af .NewCT_NumDataSource ();};return MakeNumberDataSource (_gdg ._gfec .YVal );
};

// AddSeries adds a default series to an Doughnut chart.
func (_dca DoughnutChart )AddSeries ()PieChartSeries {_cbdcd :=_af .NewCT_PieSer ();_dca ._ffec .Ser =append (_dca ._ffec .Ser ,_cbdcd );_cbdcd .Idx .ValAttr =uint32 (len (_dca ._ffec .Ser )-1);_cbdcd .Order .ValAttr =uint32 (len (_dca ._ffec .Ser )-1);
_egdd :=PieChartSeries {_cbdcd };_egdd .InitializeDefaults ();return _egdd ;};

// X returns the inner wrapped XML type.
func (_eb Bar3DChart )X ()*_af .CT_Bar3DChart {return _eb ._ag };func (_fea CategoryAxis )SetPosition (p _af .ST_AxPos ){_fea ._cf .AxPos =_af .NewCT_AxPos ();_fea ._cf .AxPos .ValAttr =p ;};

// CategoryAxis returns the category data source.
func (_dbe AreaChartSeries )CategoryAxis ()CategoryAxisDataSource {if _dbe ._fc .Cat ==nil {_dbe ._fc .Cat =_af .NewCT_AxDataSource ();};return MakeAxisDataSource (_dbe ._fc .Cat );};

// Values returns the value data source.
func (_gbf BubbleChartSeries )Values ()NumberDataSource {if _gbf ._fe .YVal ==nil {_gbf ._fe .YVal =_af .NewCT_NumDataSource ();};return MakeNumberDataSource (_gbf ._fe .YVal );};

// Index returns the index of the series
func (_fcf LineChartSeries )Index ()uint32 {return _fcf ._agb .Idx .ValAttr };func (_ee Bar3DChart )AddAxis (axis Axis ){_cea :=_af .NewCT_UnsignedInt ();_cea .ValAttr =axis .AxisID ();_ee ._ag .AxId =append (_ee ._ag .AxId ,_cea );};

// AddLine3DChart adds a new 3D line chart to a chart.
func (_fbff Chart )AddLine3DChart ()Line3DChart {_aaa (_fbff ._gdb .Chart );_dbeg :=_af .NewCT_PlotAreaChoice ();_fbff ._gdb .Chart .PlotArea .PlotAreaChoice =append (_fbff ._gdb .Chart .PlotArea .PlotAreaChoice ,_dbeg );_dbeg .Line3DChart =_af .NewCT_Line3DChart ();
_dbeg .Line3DChart .Grouping =_af .NewCT_Grouping ();_dbeg .Line3DChart .Grouping .ValAttr =_af .ST_GroupingStandard ;return Line3DChart {_fca :_dbeg .Line3DChart };};type Legend struct{_feab *_af .CT_Legend };func MakeChart (x *_af .ChartSpace )Chart {return Chart {x }};


// X returns the inner wrapped XML type.
func (_ebe Surface3DChart )X ()*_af .CT_Surface3DChart {return _ebe ._eaa };

// InitializeDefaults initializes an Pie series to the default values.
func (_gbfa PieChartSeries )InitializeDefaults (){};

// X returns the inner wrapped XML type.
func (_cbg GridLines )X ()*_af .CT_ChartLines {return _cbg ._gdd };

// X returns the inner wrapped XML type.
func (_edg PieOfPieChart )X ()*_af .CT_OfPieChart {return _edg ._adc };

// StockChart is a 2D Stock chart.
type StockChart struct{chartBase ;_ccda *_af .CT_StockChart ;};