//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package axcontrol ;import (_f "bytes";_b "encoding/binary";_eg "errors";_e "fmt";_be "github.com/unidoc/unioffice/v2/common/tempstorage";_ac "github.com/unidoc/unioffice/v2/internal/mscfb";_bc "github.com/unidoc/unioffice/v2/internal/mscfb/rw";_a "github.com/unidoc/unioffice/v2/schema/schemas.microsoft.com/office/activeX";
_cb "io";);func (_gge *CommandButtonControl )readPropMask (_faf *_bc .Reader )error {var _agf uint32 ;if _ebed :=_b .Read (_faf ,_b .LittleEndian ,&_agf );_ebed !=nil {return _ebed ;};_gge ._bb =&commandButtonPropMask {};_gge ._bb ._dbb ,_agf =_bc .PopRightUI32 (_agf );
_gge ._bb ._daf ,_agf =_bc .PopRightUI32 (_agf );_gge ._bb ._fed ,_agf =_bc .PopRightUI32 (_agf );_gge ._bb ._feg ,_agf =_bc .PopRightUI32 (_agf );_gge ._bb ._efb ,_agf =_bc .PopRightUI32 (_agf );_gge ._bb ._ebe ,_agf =_bc .PopRightUI32 (_agf );_gge ._bb ._gbb ,_agf =_bc .PopRightUI32 (_agf );
_gge ._bb ._geb ,_agf =_bc .PopRightUI32 (_agf );_gge ._bb ._aegc ,_agf =_bc .PopRightUI32 (_agf );_gge ._bb ._aaf ,_agf =_bc .PopRightUI32 (_agf );_gge ._bb ._eecc ,_agf =_bc .PopRightUI32 (_agf );return nil ;};

// ImageControl is a representation of an image ActiveX form.
type ImageControl struct{controlBase ;_gdc *imagePropMask ;_bgcc *imageDataBlock ;_baed *imageExtraDataBlock ;_fg *streamData ;};func (_bbdc *ImageControl )writeExtraDataBlock (_cea *_bc .Writer )error {if _bbdc ._gdc ._cgd {_dfbdg :=uint64 (_bbdc ._baed ._dea )<<32|uint64 (_bbdc ._baed ._bbe );
if _cbgd :=_cea .WritePropertyNoAlign (_dfbdg );_cbgd !=nil {return _cbgd ;};};return nil ;};type guidAndPicture struct{_aaa []byte ;_caga *stdPicture ;};

// GetWidth returns width of the CommandButton in HIMETRIC (0.01mm)
func (_fagb *CommandButtonControl )GetWidth ()uint32 {return _fagb ._dce ._gdb };func (_ggaf *CommandButtonControl )readDataBlock (_beb *_bc .Reader )error {_ggaf ._dec =&commandButtonDataBlock {};if _ggaf ._bb ._dbb {if _fda :=_beb .ReadProperty (&_ggaf ._dec ._ceg );
_fda !=nil {return _fda ;};};if _ggaf ._bb ._daf {if _ccf :=_beb .ReadProperty (&_ggaf ._dec ._cbd );_ccf !=nil {return _ccf ;};};if _ggaf ._bb ._fed {if _cbff :=_beb .ReadProperty (&_ggaf ._dec ._bag );_cbff !=nil {return _cbff ;};};if _ggaf ._bb ._feg {var _eff uint32 ;
if _cecc :=_beb .ReadProperty (&_eff );_cecc !=nil {return _cecc ;};_ggaf ._dec ._cec ,_ggaf ._dec ._aed =_gd (_eff );};if _ggaf ._bb ._efb {if _bbce :=_beb .ReadProperty (&_ggaf ._dec ._gaf );_bbce !=nil {return _bbce ;};};if _ggaf ._bb ._gbb {if _gde :=_beb .ReadProperty (&_ggaf ._dec ._gff );
_gde !=nil {return _gde ;};};if _ggaf ._bb ._geb {if _egce :=_beb .ReadProperty (&_ggaf ._dec ._gfg );_egce !=nil {return _egce ;};};if _ggaf ._bb ._aegc {if _age :=_beb .ReadProperty (&_ggaf ._dec ._ade );_age !=nil {return _age ;};};if _ggaf ._bb ._eecc {if _efbg :=_beb .ReadProperty (&_ggaf ._dec ._dcb );
_efbg !=nil {return _efbg ;};};return nil ;};type imageExtraDataBlock struct{_dea uint32 ;_bbe uint32 ;};

// GetCaption gets a caption string from a morph control.
func (_egcd *morphDataControl )GetCaption ()string {if _egcd ._aee &&_egcd ._facb ._dbbc {return _egcd ._eaf ._ffcc ;};return "";};

// GetForeColor gets a button text color value for a system palette from a scrollBar control.
func (_aagd *ScrollBarControl )GetForeColor ()uint32 {return _aagd ._gfcff ._gfgd };

// GetMin gets a button min value.
func (_cfge *ScrollBarControl )GetMin ()int32 {return _cfge ._gfcff ._cgga };const _degg =6;

// GetValue gets a value from a control which value can be represented as a string.
func (_cefb *morphDataControlStringValue )GetValue ()string {return _cefb .getValueString ()};func (_gcda *SpinButtonControl )writeDataBlock (_acff *_bc .Writer )error {if _gcda ._dged ._gcea {if _deffe :=_acff .WriteProperty (_gcda ._cgf ._caab );_deffe !=nil {return _deffe ;
};};if _gcda ._dged ._aafb {if _cfdc :=_acff .WriteProperty (_gcda ._cgf ._cbb );_cfdc !=nil {return _cfdc ;};};if _gcda ._dged ._cdge {if _cgege :=_acff .WriteProperty (_gcda ._cgf ._egdcc );_cgege !=nil {return _cgege ;};};if _gcda ._dged ._cfde {if _dcece :=_acff .WriteProperty (_gcda ._cgf ._deeb );
_dcece !=nil {return _dcece ;};};if _gcda ._dged ._ccae {if _ebbf :=_acff .WriteProperty (_gcda ._cgf ._ecca );_ebbf !=nil {return _ebbf ;};};if _gcda ._dged ._accf {if _dfgb :=_acff .WriteProperty (_gcda ._cgf ._gef );_dfgb !=nil {return _dfgb ;};};if _gcda ._dged ._bfegb {if _gbgc :=_acff .WriteProperty (_gcda ._cgf ._dbfe );
_gbgc !=nil {return _gbgc ;};};if _gcda ._dged ._beaf {if _baaa :=_acff .WriteProperty (_gcda ._cgf ._gcac );_baaa !=nil {return _baaa ;};};if _gcda ._dged ._acd {if _aaff :=_acff .WriteProperty (_gcda ._cgf ._aaaf );_aaff !=nil {return _aaff ;};};if _gcda ._dged ._bdbd {if _aggf :=_acff .WriteProperty (_gcda ._cgf ._edcf );
_aggf !=nil {return _aggf ;};};if _gcda ._dged ._ffcd {if _abaa :=_acff .WriteProperty (_gcda ._cgf ._egcc );_abaa !=nil {return _abaa ;};};if _gcda ._dged ._cdfgg {if _dgaa :=_acff .WriteProperty (_gcda ._cgf ._bgee );_dgaa !=nil {return _dgaa ;};};if _gcda ._dged ._egad {if _fbd :=_acff .WriteProperty (_gcda ._cgf ._bfd );
_fbd !=nil {return _fbd ;};};return _acff .AlignLength (4);};

// SetWidth sets width of the SpinButton in HIMETRIC (0.01mm)
func (_cdga *SpinButtonControl )SetWidth (width uint32 ){_cdga ._dged ._aedd =true ;_cdga ._faee ._bceb =width ;};type morphDataControlBoolValue struct{*morphDataControl };

// GetHeight returns height of the morphDataControl in HIMETRIC (0.01mm)
func (_egbcg *morphDataControl )GetHeight ()uint32 {return _egbcg ._eaf ._ceee };

// SetBackColor sets a button text color value from a system palette for a spinButton control.
func (_bddd *SpinButtonControl )SetBackColor (backColor uint32 ){_bddd ._dged ._aafb =true ;_bddd ._cgf ._cbb =backColor ;};func (_eecg *morphDataControl )writeDataBlock (_aggc *_bc .Writer )error {if _eecg ._facb ._effb {if _cdgg :=_aggc .WriteProperty (_eecg ._cdb ._gcabc );
_cdgg !=nil {return _cdgg ;};};if _eecg ._facb ._feb {if _cadad :=_aggc .WriteProperty (_eecg ._cdb ._eabb );_cadad !=nil {return _cadad ;};};if _eecg ._facb ._dbd {if _dcac :=_aggc .WriteProperty (_eecg ._cdb ._aaed );_dcac !=nil {return _dcac ;};};if _eecg ._facb ._aggd {if _feaa :=_aggc .WriteProperty (_eecg ._cdb ._efd );
_feaa !=nil {return _feaa ;};};if _eecg ._facb ._afa {if _eccc :=_aggc .WriteProperty (_eecg ._cdb ._ccbf );_eccc !=nil {return _eccc ;};};if _eecg ._facb ._abf {if _dfbc :=_aggc .WriteProperty (_eecg ._cdb ._adbb );_dfbc !=nil {return _dfbc ;};};if _eecg ._facb ._dafa {if _gcdc :=_aggc .WriteProperty (_eecg ._cdb ._fad );
_gcdc !=nil {return _gcdc ;};};if _eecg ._facb ._fce {if _gfcf :=_aggc .WriteProperty (_eecg ._cdb ._cecd );_gfcf !=nil {return _gfcf ;};};if _eecg ._facb ._dggb {if _aaaa :=_aggc .WriteProperty (_eecg ._cdb ._bgec );_aaaa !=nil {return _aaaa ;};};if _eecg ._facb ._dbbb {if _ggfdc :=_aggc .WriteProperty (_eecg ._cdb ._caba );
_ggfdc !=nil {return _ggfdc ;};};if _eecg ._facb ._aacb {if _efg :=_aggc .WriteProperty (_eecg ._cdb ._fgbe );_efg !=nil {return _efg ;};};if _eecg ._facb ._cfc {if _bbg :=_aggc .WriteProperty (_eecg ._cdb ._gdda );_bbg !=nil {return _bbg ;};};if _eecg ._facb ._ebge {if _bbbb :=_aggc .WriteProperty (_eecg ._cdb ._fcdd );
_bbbb !=nil {return _bbbb ;};};if _eecg ._facb ._beag {if _bcf :=_aggc .WriteProperty (_eecg ._cdb ._gbcd );_bcf !=nil {return _bcf ;};};if _eecg ._facb ._ace {if _ebgg :=_aggc .WriteProperty (_eecg ._cdb ._daac );_ebgg !=nil {return _ebgg ;};};if _eecg ._facb ._cdgb {if _eac :=_aggc .WriteProperty (_eecg ._cdb ._bdda );
_eac !=nil {return _eac ;};};if _eecg ._facb ._bdba {if _acc :=_aggc .WriteProperty (_eecg ._cdb ._ccea );_acc !=nil {return _acc ;};};if _eecg ._facb ._ccdc {if _dff :=_aggc .WriteProperty (_eecg ._cdb ._gddb );_dff !=nil {return _dff ;};};if _eecg ._facb ._fdff {if _ddcd :=_aggc .WriteProperty (_eecg ._cdb ._cga );
_ddcd !=nil {return _ddcd ;};};if _eecg ._facb ._dcg {if _gddc :=_aggc .WriteProperty (_eecg ._cdb ._bfg );_gddc !=nil {return _gddc ;};};if _eecg ._facb ._adgg {_gcg :=_ff (_eecg ._cdb ._bdcf ,_eecg ._cdb ._cfg );if _bgeb :=_aggc .WriteProperty (_gcg );
_bgeb !=nil {return _bgeb ;};};if _eecg ._facb ._dbbc {_cdaf :=_ff (_eecg ._cdb ._fbfd ,_eecg ._cdb ._baae );if _dfc :=_aggc .WriteProperty (_cdaf );_dfc !=nil {return _dfc ;};};if _eecg ._facb ._cce {if _gec :=_aggc .WriteProperty (_eecg ._cdb ._adf );
_gec !=nil {return _gec ;};};if _eecg ._facb ._gage {if _efdb :=_aggc .WriteProperty (_eecg ._cdb ._efdd );_efdb !=nil {return _efdb ;};};if _eecg ._facb ._cfbd {if _dfaa :=_aggc .WriteProperty (_eecg ._cdb ._bdgg );_dfaa !=nil {return _dfaa ;};};if _eecg ._facb ._gbga {if _gda :=_aggc .WriteProperty (_eecg ._cdb ._bggg );
_gda !=nil {return _gda ;};};if _eecg ._facb ._bdbff {if _dfcb :=_aggc .WriteProperty (_eecg ._cdb ._dfgf );_dfcb !=nil {return _dfcb ;};};if _eecg ._facb ._efag {if _dcca :=_aggc .WriteProperty (_eecg ._cdb ._egdf );_dcca !=nil {return _dcca ;};};if _eecg ._facb ._fff {_befa :=_ff (_eecg ._cdb ._ebdg ,_eecg ._cdb ._gce );
if _beagc :=_aggc .WriteProperty (_befa );_beagc !=nil {return _beagc ;};};return _aggc .AlignLength (4);};

// GetMin gets a button min value.
func (_gedc *SpinButtonControl )GetMin ()int32 {return _gedc ._cgf ._deeb };const _gfb =2;

// GetForeColor gets a button text color value for a system palette from a label control.
func (_agbg *LabelControl )GetForeColor ()uint32 {return _agbg ._egf ._bdbf };

// ListBoxDataControl is a representation of a list box ActiveX form.
type ListBoxDataControl struct{*morphDataControlStringValue };func (_ecf *CommandButtonControl )writeExtraDataBlock (_daa *_bc .Writer )error {if _ecf ._dec ._aed > 0{if _adg :=_daa .WriteStringProperty (_ecf ._dce ._gddg );_adg !=nil {return _adg ;};};
if _ecf ._bb ._ebe {_ccc :=uint64 (_ecf ._dce ._gdb )<<32|uint64 (_ecf ._dce ._ega );if _egb :=_daa .WritePropertyNoAlign (_ccc );_egb !=nil {return _egb ;};};return nil ;};func (_bgf *morphDataControl )setValueString (_fba string ){_bgf ._facb ._adgg =true ;
_bgf ._cdb ._bdcf =uint32 (len (_fba ));_bgf ._eaf ._fcae =_fba ;};

// LabelControl is a representation of a label ActiveX form.
type LabelControl struct{controlBase ;_gbg *labelPropMask ;_egf *labelDataBlock ;_afb *labelExtraDataBlock ;_geg *streamData ;};func (_ggd *ScrollBarControl )writeDataBlock (_afac *_bc .Writer )error {if _ggd ._cgbf ._baef {if _egdb :=_afac .WriteProperty (_ggd ._gfcff ._gfgd );
_egdb !=nil {return _egdb ;};};if _ggd ._cgbf ._acef {if _gfgdb :=_afac .WriteProperty (_ggd ._gfcff ._fbc );_gfgdb !=nil {return _gfgdb ;};};if _ggd ._cgbf ._gad {if _eafe :=_afac .WriteProperty (_ggd ._gfcff ._bbef );_eafe !=nil {return _eafe ;};};if _ggd ._cgbf ._fgef {if _efbf :=_afac .WriteProperty (_ggd ._gfcff ._edc );
_efbf !=nil {return _efbf ;};};if _ggd ._cgbf ._fbgf {if _eacd :=_afac .WriteProperty (_ggd ._gfcff ._cgga );_eacd !=nil {return _eacd ;};};if _ggd ._cgbf ._fdd {if _dcaa :=_afac .WriteProperty (_ggd ._gfcff ._aade );_dcaa !=nil {return _dcaa ;};};if _ggd ._cgbf ._ebefe {if _cccg :=_afac .WriteProperty (_ggd ._gfcff ._fcbg );
_cccg !=nil {return _cccg ;};};if _ggd ._cgbf ._eddd {if _fbce :=_afac .WriteProperty (_ggd ._gfcff ._dge );_fbce !=nil {return _fbce ;};};if _ggd ._cgbf ._bab {if _fffg :=_afac .WriteProperty (_ggd ._gfcff ._cecb );_fffg !=nil {return _fffg ;};};if _ggd ._cgbf ._eebg {if _cfee :=_afac .WriteProperty (_ggd ._gfcff ._dbg );
_cfee !=nil {return _cfee ;};};if _ggd ._cgbf ._efgc {if _efaag :=_afac .WriteProperty (_ggd ._gfcff ._gbcde );_efaag !=nil {return _efaag ;};};if _ggd ._cgbf ._eca {if _egcg :=_afac .WriteProperty (_ggd ._gfcff ._dbag );_egcg !=nil {return _egcg ;};};
if _ggd ._cgbf ._bece {if _eecb :=_afac .WriteProperty (_ggd ._gfcff ._fbgge );_eecb !=nil {return _eecb ;};};if _ggd ._cgbf ._bcdb {if _dfdfc :=_afac .WriteProperty (_ggd ._gfcff ._dccab );_dfdfc !=nil {return _dfdfc ;};};if _ggd ._cgbf ._faaa {if _dfbf :=_afac .WriteProperty (_ggd ._gfcff ._ebb );
_dfbf !=nil {return _dfbf ;};};return _afac .AlignLength (4);};

// GetForeColor gets a button text color value for a system palette from a commandButton control.
func (_cagg *CommandButtonControl )GetForeColor ()uint32 {return _cagg ._dec ._ceg };func (_dfge *morphDataControl )getValueBool ()bool {return _dfge ._facb ._adgg &&_dfge ._eaf ._fcae =="\u0031";};func (_adbcb *controlBase )writeStreamDataM (_cbag *_bc .Writer )error {if _adbcb ._caa !=nil {if _adbcb ._caa ._cdac !=nil {if _acffd :=_adbcb ._caa ._cdac .export (_cbag );
_acffd !=nil {return _acffd ;};};};return nil ;};

// GetBackColor gets a button text color value for a system palette from a label control.
func (_bgg *LabelControl )GetBackColor ()uint32 {return _bgg ._egf ._dbe };func (_ged *ImageControl )export (_dcaf *_bc .Writer )error {if _gbc :=_ged .writePropMask (_dcaf );_gbc !=nil {return _gbc ;};if _daad :=_ged .writeDataBlock (_dcaf );_daad !=nil {return _daad ;
};if _acgab :=_ged .writeExtraDataBlock (_dcaf );_acgab !=nil {return _acgab ;};_ged ._eecd =uint16 (_dcaf .Len ()-4);if _ffb :=_ged .writeStreamDataPM (_dcaf );_ffb !=nil {return _ffb ;};return _ged .writeTheRest (_dcaf );};

// SetMax sets a button max value.
func (_bbeb *SpinButtonControl )SetMax (max int32 ){_bbeb ._dged ._ccae =true ;_bbeb ._cgf ._ecca =max };func (_dbbe *controlBase )writeStreamDataPM (_cfdf *_bc .Writer )error {if _dbbe ._caa !=nil {if _dbbe ._caa ._befc !=nil {if _gcb :=_dbbe ._caa ._befc .export (_cfdf );
_gcb !=nil {return _gcb ;};};if _dbbe ._caa ._cdac !=nil {if _eeg :=_dbbe ._caa ._cdac .export (_cfdf );_eeg !=nil {return _eeg ;};};};return nil ;};func (_beff *ImageControl )readPropMask (_ege *_bc .Reader )error {var _abdf uint32 ;if _fcg :=_b .Read (_ege ,_b .LittleEndian ,&_abdf );
_fcg !=nil {return _fcg ;};_beff ._gdc =&imagePropMask {};_abdf >>=2;_beff ._gdc ._ccfg ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._abd ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._cad ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._gfd ,_abdf =_bc .PopRightUI32 (_abdf );
_beff ._gdc ._bdc ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._fcfa ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._acac ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._cgd ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._cagae ,_abdf =_bc .PopRightUI32 (_abdf );
_beff ._gdc ._fbe ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._bbfb ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._afef ,_abdf =_bc .PopRightUI32 (_abdf );_beff ._gdc ._cccc ,_abdf =_bc .PopRightUI32 (_abdf );return nil ;};func (_ebg *morphDataControl )export (_egff *_bc .Writer )error {if _fgb :=_ebg .writePropMask (_egff );
_fgb !=nil {return _fgb ;};if _faeb :=_ebg .writeDataBlock (_egff );_faeb !=nil {return _faeb ;};if _bcef :=_ebg .writeExtraDataBlock (_egff );_bcef !=nil {return _bcef ;};_ebg ._eecd =uint16 (_egff .Len ()-4);if _abab :=_ebg .writeStreamDataMP (_egff );
_abab !=nil {return _abab ;};return _ebg .writeTheRest (_egff );};func (_dfd *CommandButtonControl )readExtraDataBlock (_aca *_bc .Reader )error {_dfd ._dce =&commandButtonExtraDataBlock {};if _dfd ._dec ._aed > 0{_dbf ,_bad :=_aca .ReadStringProperty (_dfd ._dec ._aed );
if _bad !=nil {return _bad ;};_dfd ._dce ._gddg =_dbf ;};if _dfd ._bb ._ebe {var _af uint64 ;if _dfa :=_aca .ReadPairProperty (&_af );_dfa !=nil {return _dfa ;};_dfd ._dce ._ega =uint32 (_af );_dfd ._dce ._gdb =uint32 (_af >>32);};return nil ;};const _bdgd =4;
const _eab =3;func (_baac *LabelControl )writePropMask (_ddc *_bc .Writer )error {_ccccb :=uint32 (0);_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._fdc );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._fac );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._fabf );
_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._cegg );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._dcf );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._gfa );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._gaga );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._afbg );
_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._dcff );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._agbf );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._aad );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._bacg );_ccccb =_bc .PushLeftUI32 (_ccccb ,_baac ._gbg ._fgde );
_ccccb >>=19;return _b .Write (_ddc ,_b .LittleEndian ,_ccccb );};

// GetHeight returns height of the Label in HIMETRIC (0.01mm)
func (_affe *LabelControl )GetHeight ()uint32 {return _affe ._afb ._cfd };func (_fcdg *morphDataControl )readExtraDataBlock (_dcag *_bc .Reader )error {_fcdg ._eaf =&morphDataExtraDataBlock {};if _fcdg ._facb ._fdac {var _ffaf uint64 ;if _dbef :=_dcag .ReadPairProperty (&_ffaf );
_dbef !=nil {return _dbef ;};_fcdg ._eaf ._ceee =uint32 (_ffaf );_fcdg ._eaf ._dcfa =uint32 (_ffaf >>32);};if _fcdg ._cdb ._bdcf > 0{_cdad ,_dgge :=_dcag .ReadStringProperty (_fcdg ._cdb ._bdcf );if _dgge !=nil {return _dgge ;};_fcdg ._eaf ._fcae =_cdad ;
};if _fcdg ._cdb ._fbfd > 0{_cgeg ,_dgc :=_dcag .ReadStringProperty (_fcdg ._cdb ._fbfd );if _dgc !=nil {return _dgc ;};_fcdg ._eaf ._ffcc =_cgeg ;};if _fcdg ._cdb ._ebdg > 0{_aceb ,_cggd :=_dcag .ReadStringProperty (_fcdg ._cdb ._ebdg );if _cggd !=nil {return _cggd ;
};_fcdg ._eaf ._cfcc =_aceb ;};return nil ;};

// SetCaption sets a caption string for a commandButton control.
func (_feab *CommandButtonControl )SetCaption (caption string ){_feab ._bb ._feg =true ;_feab ._dec ._aed =uint32 (len (caption ));_feab ._dce ._gddg =caption ;};func (_fbdf *controlBase )writeStreamDataMP (_bgccb *_bc .Writer )error {if _fbdf ._caa !=nil {if _fbdf ._caa ._cdac !=nil {if _feaba :=_fbdf ._caa ._cdac .export (_bgccb );
_feaba !=nil {return _feaba ;};};if _fbdf ._caa ._befc !=nil {if _ebbfa :=_fbdf ._caa ._befc .export (_bgccb );_ebbfa !=nil {return _ebbfa ;};};};return nil ;};

// GetForeColor gets a button text color value for a system palette from a spinButton control.
func (_bdcc *SpinButtonControl )GetForeColor ()uint32 {return _bdcc ._cgf ._caab };type commandButtonPropMask struct{_dbb bool ;_daf bool ;_fed bool ;_feg bool ;_efb bool ;_ebe bool ;_gbb bool ;_geb bool ;_aegc bool ;_aaf bool ;_eecc bool ;};

// SetValue sets a value for a control which value can be represented as a string.
func (_cbda *morphDataControlStringValue )SetValue (value string ){_cbda .setValueString (value )};

// SetWidth sets width of the CommandButton in HIMETRIC (0.01mm)
func (_gag *CommandButtonControl )SetWidth (width uint32 ){_gag ._bb ._ebe =true ;_gag ._dce ._gdb =width ;};type morphDataControl struct{controlBase ;_facb *morphDataPropMask ;_cdb *morphDataDataBlock ;_eaf *morphDataExtraDataBlock ;_cbdc *streamData ;
_bge *morphDataColumnInfo ;_fabg *morphDataColumnInfoPropMask ;_ebfg *morphDataColumnInfoDataBlock ;};func (_edf *controlBase )writeTheRest (_egdc *_bc .Writer )error {_ ,_dg :=_egdc .Write (_edf ._cefd );return _dg ;};func (_aegbc *ScrollBarControl )readExtraDataBlock (_fgbea *_bc .Reader )error {_aegbc ._bega =&scrollBarExtraDataBlock {};
if _aegbc ._cgbf ._bddf {var _dbfa uint64 ;if _efcg :=_fgbea .ReadPairProperty (&_dbfa );_efcg !=nil {return _efcg ;};_aegbc ._bega ._cadb =uint32 (_dbfa );_aegbc ._bega ._bcfg =uint32 (_dbfa >>32);};return nil ;};func (_bdd *CommandButtonControl )export (_cab *_bc .Writer )error {if _eec :=_bdd .writePropMask (_cab );
_eec !=nil {return _eec ;};if _dfb :=_bdd .writeDataBlock (_cab );_dfb !=nil {return _dfb ;};if _bbf :=_bdd .writeExtraDataBlock (_cab );_bbf !=nil {return _bbf ;};_bdd ._eecd =uint16 (_cab .Len ()-4);if _ffe :=_bdd .writeStreamDataPM (_cab );_ffe !=nil {return _ffe ;
};return _bdd .writeTheRest (_cab );};func (_gffg *guidAndPicture )importFromReader (_dd *_bc .Reader )error {_dfbd :=_f .NewBuffer ([]byte {});if _ ,_bea :=_cb .CopyN (_dfbd ,_dd ,int64 (_abe ));_bea !=nil {return _bea ;};_eba :=_dfbd .Bytes ();for _cagf :=0;
_cagf < _abe ;_cagf ++{if _eba [_cagf ]!=_faff [_cagf ]{return _e .Errorf ("\u0049\u006e\u0076\u0061\u006c\u0069d\u0020\u0047\u0055\u0049\u0044\u0020\u0076\u0061\u006c\u0075\u0065\u0020\u0025v\u0020\u0061\u0074\u0020\u0069\u006e\u0064e\u0078\u0020\u0025\u0076",_eba [_cagf ],_cagf );
};};_gffg ._aaa =_eba ;_gffg ._caga =&stdPicture {};if _faa :=_dd .ReadProperty (&_gffg ._caga ._cbe );_faa !=nil {return _faa ;};if _gffg ._caga ._cbe !=_def {return _e .Errorf ("\u0049\u006e\u0076\u0061li\u0064\u0020\u0070\u0072\u0065\u0061\u006d\u0062\u006c\u0065\u0020\u0025\u0076",_gffg ._caga ._cbe );
};if _dfe :=_dd .ReadProperty (&_gffg ._caga ._agc );_dfe !=nil {return _dfe ;};if _gffg ._caga ._agc !=0{_afc :=_f .NewBuffer ([]byte {});if _ ,_gfc :=_cb .Copy (_afc ,_dd );_gfc !=nil {return _gfc ;};_gffg ._caga ._dag =_afc ;};return nil ;};func _dgcf (_abbc *_bc .Reader )(*SpinButtonControl ,error ){_bgb :=&SpinButtonControl {};
if _bagd :=_bgb .readPropMask (_abbc );_bagd !=nil {return nil ,_bagd ;};if _fdbbf :=_bgb .readDataBlock (_abbc );_fdbbf !=nil {return nil ,_fdbbf ;};if _bgdf :=_bgb .readExtraDataBlock (_abbc );_bgdf !=nil {return nil ,_bgdf ;};if _aab :=_bgb .readStreamDataM (_abbc ,_bgb ._dged ._cdfgg );
_aab !=nil {return nil ,_aab ;};if _gcfd :=_bgb .readTheRest (_abbc );_gcfd !=nil {return nil ,_gcfd ;};return _bgb ,nil ;};var _faff =[]byte {0x04,0x52,0xE3,0x0B,0x91,0x8F,0xCE,0x11,0x9D,0xE3,0,0xAA,0,0x4B,0xB8,0x51};func (_eeb *controlBase )setPictureBytes (_agb []byte ){if _eeb ._caa ._befc ==nil {_eeb ._caa ._befc =&guidAndPicture {};
};_eeb ._caa ._befc .setStdPictureBytes (_agb );};

// SetPosition sets a button position value.
func (_ceec *ScrollBarControl )SetPosition (position int32 ){_ceec ._cgbf ._ebefe =true ;_ceec ._gfcff ._fcbg =position ;};type morphDataExtraDataBlock struct{_dcfa uint32 ;_ceee uint32 ;_fcae string ;_ffcc string ;_cfcc string ;};type scrollBarExtraDataBlock struct{_bcfg uint32 ;
_cadb uint32 ;};func (_ggfd *ImageControl )writeDataBlock (_fbf *_bc .Writer )error {if _ggfd ._gdc ._abd {if _gaa :=_fbf .WriteProperty (_ggfd ._bgcc ._adef );_gaa !=nil {return _gaa ;};};if _ggfd ._gdc ._cad {if _dcd :=_fbf .WriteProperty (_ggfd ._bgcc ._aae );
_dcd !=nil {return _dcd ;};};if _ggfd ._gdc ._gfd {if _aag :=_fbf .WriteProperty (_ggfd ._bgcc ._fef );_aag !=nil {return _aag ;};};if _ggfd ._gdc ._bdc {if _cbg :=_fbf .WriteProperty (_ggfd ._bgcc ._dga );_cbg !=nil {return _cbg ;};};if _ggfd ._gdc ._fcfa {if _bdf :=_fbf .WriteProperty (_ggfd ._bgcc ._gca );
_bdf !=nil {return _bdf ;};};if _ggfd ._gdc ._acac {if _bbb :=_fbf .WriteProperty (_ggfd ._bgcc ._gfcd );_bbb !=nil {return _bbb ;};};if _ggfd ._gdc ._cagae {if _bac :=_fbf .WriteProperty (_ggfd ._bgcc ._efa );_bac !=nil {return _bac ;};};if _ggfd ._gdc ._fbe {if _fegc :=_fbf .WriteProperty (_ggfd ._bgcc ._bda );
_fegc !=nil {return _fegc ;};};if _ggfd ._gdc ._afef {if _afg :=_fbf .WriteProperty (_ggfd ._bgcc ._dbbf );_afg !=nil {return _afg ;};};if _ggfd ._gdc ._cccc {if _dfg :=_fbf .WriteProperty (_ggfd ._bgcc ._aff );_dfg !=nil {return _dfg ;};};return _fbf .AlignLength (4);
};

// GetMax gets a button max value.
func (_eabf *SpinButtonControl )GetMax ()int32 {return _eabf ._cgf ._ecca };type imageDataBlock struct{_adef uint32 ;_aae uint32 ;_fef byte ;_dga uint8 ;_gca byte ;_gfcd byte ;_efa uint16 ;_bda byte ;_dbbf uint32 ;_aff uint16 ;};

// ControlChoice represents an ActiveX control inside a wrapper.
type ControlChoice struct{CheckBox *CheckBoxDataControl ;TextBox *TextBoxDataControl ;ListBox *ListBoxDataControl ;ComboBox *ComboBoxDataControl ;OptionButton *OptionButtonDataControl ;ToggleButton *ToggleButtonDataControl ;Label *LabelControl ;Image *ImageControl ;
SpinButton *SpinButtonControl ;CommandButton *CommandButtonControl ;ScrollBar *ScrollBarControl ;_bec *controlBase ;};

// GetBackColor gets a button text color value for a system palette from a spinButton control.
func (_abadd *SpinButtonControl )GetBackColor ()uint32 {return _abadd ._cgf ._cbb };func (_degc *morphDataControl )writeExtraDataBlock (_dcec *_bc .Writer )error {if _degc ._facb ._fdac {_ddg :=uint64 (_degc ._eaf ._dcfa )<<32|uint64 (_degc ._eaf ._ceee );
if _fecc :=_dcec .WritePropertyNoAlign (_ddg );_fecc !=nil {return _fecc ;};};if _degc ._cdb ._bdcf > 0{if _fbbf :=_dcec .WriteStringProperty (_degc ._eaf ._fcae );_fbbf !=nil {return _fbbf ;};};if _degc ._cdb ._fbfd > 0{if _cagc :=_dcec .WriteStringProperty (_degc ._eaf ._ffcc );
_cagc !=nil {return _cagc ;};};if _degc ._cdb ._ebdg > 0{if _cbdd :=_dcec .WriteStringProperty (_degc ._eaf ._cfcc );_cbdd !=nil {return _cbdd ;};};return nil ;};func (_ead *ImageControl )writePropMask (_bbd *_bc .Writer )error {_dab :=uint32 (0);_dab >>=2;
_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._ccfg );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._abd );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._cad );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._gfd );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._bdc );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._fcfa );
_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._acac );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._cgd );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._cagae );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._fbe );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._bbfb );
_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._afef );_dab =_bc .PushLeftUI32 (_dab ,_ead ._gdc ._cccc );_dab >>=17;return _b .Write (_bbd ,_b .LittleEndian ,_dab );};type morphDataControlStringValue struct{*morphDataControl };type morphDataColumnInfo struct{};


// OptionButtonDataControl is a representation of an option button ActiveX form.
type OptionButtonDataControl struct{*morphDataControlBoolValue };func (_afe *guidAndPicture )setStdPictureBytes (_badb []byte ){if _badb ==nil {return ;};if _afe ._aaa ==nil {_afe ._aaa =_faff ;};if _afe ._caga ==nil {_afe ._caga =&stdPicture {_cbe :_def };
};_afe ._caga ._agc =uint32 (len (_badb ));_afe ._caga ._dag =_f .NewBuffer (_badb );};

// FmPictureSizeMode represents one of the three picture size modes according to MS-OFORMS document.
type FmPictureSizeMode byte ;type imagePropMask struct{_ccfg bool ;_abd bool ;_cad bool ;_gfd bool ;_bdc bool ;_fcfa bool ;_acac bool ;_cgd bool ;_cagae bool ;_fbe bool ;_bbfb bool ;_afef bool ;_cccc bool ;};func _dddd (_dddc *_bc .Reader )(*LabelControl ,error ){_fdbb :=&LabelControl {};
if _cega :=_fdbb .readPropMask (_dddc );_cega !=nil {return nil ,_cega ;};if _egbc :=_fdbb .readDataBlock (_dddc );_egbc !=nil {return nil ,_egbc ;};if _ffc :=_fdbb .readExtraDataBlock (_dddc );_ffc !=nil {return nil ,_ffc ;};if _gdf :=_fdbb .readStreamDataPM (_dddc ,_fdbb ._gbg ._aad ,_fdbb ._gbg ._fgde );
_gdf !=nil {return nil ,_gdf ;};if _bggd :=_fdbb .readTheRest (_dddc );_bggd !=nil {return nil ,_bggd ;};return _fdbb ,nil ;};type commandButtonExtraDataBlock struct{_gdb uint32 ;_ega uint32 ;_gddg string ;};const _dgb =5;

// GetCaption gets a caption string from a commandButton control.
func (_ag *CommandButtonControl )GetCaption ()string {return _ag ._dce ._gddg };

// ScrollBarControl is a representation of a scrollBar ActiveX form.
type ScrollBarControl struct{controlBase ;_cgbf *scrollBarPropMask ;_gfcff *scrollBarDataBlock ;_bega *scrollBarExtraDataBlock ;_bdee *streamData ;};func (_ebff *controlBase )getPictureBytes ()[]byte {return _ebff ._caa ._befc .getStdPictureBytes ()};

// SetForeColor sets a button text color value from a system palette for a scrollBar control.
func (_bffae *ScrollBarControl )SetForeColor (foreColor uint32 ){_bffae ._cgbf ._baef =true ;_bffae ._gfcff ._gfgd =foreColor ;};

// GetPosition gets a button position value.
func (_dcfg *SpinButtonControl )GetPosition ()int32 {return _dcfg ._cgf ._gef };

// SetHeight sets height of the ScrollBar in HIMETRIC (0.01mm)
func (_cceb *ScrollBarControl )SetHeight (height uint32 ){_cceb ._cgbf ._bddf =true ;_cceb ._bega ._cadb =height ;};type stdPicture struct{_cbe uint32 ;_agc uint32 ;_dag *_f .Buffer ;};

// SetWidth sets width of the morphDataControl in HIMETRIC (0.01mm)
func (_acge *morphDataControl )SetWidth (width uint32 ){_acge ._facb ._fdac =true ;_acge ._eaf ._dcfa =width ;};

// Control represents an ActiveX control wrapper.
type Control struct{TargetAttr string ;Ocx *_a .Ocx ;Choice *ControlChoice ;_d string ;_ca uint8 ;_db uint8 ;_cbf uint16 ;};func (_gagc *SpinButtonControl )readExtraDataBlock (_defe *_bc .Reader )error {_gagc ._faee =&spinButtonExtraDataBlock {};if _gagc ._dged ._aedd {var _dgab uint64 ;
if _feag :=_defe .ReadPairProperty (&_dgab );_feag !=nil {return _feag ;};_gagc ._faee ._bbaf =uint32 (_dgab );_gagc ._faee ._bceb =uint32 (_dgab >>32);};return nil ;};func (_ede *guidAndPicture )getStdPictureBytes ()[]byte {if _ede !=nil &&_ede ._caga !=nil &&_ede ._caga ._dag !=nil {return _ede ._caga ._dag .Bytes ();
};return nil ;};const (FmPictureSizeModeClip FmPictureSizeMode =iota ;FmPictureSizeModeStretch ;_ ;FmPictureSizeModeZoom ;);func (_fgg *LabelControl )writeExtraDataBlock (_bbaa *_bc .Writer )error {if _fgg ._egf ._fbfa > 0{if _gdba :=_bbaa .WriteStringProperty (_fgg ._afb ._bagg );
_gdba !=nil {return _gdba ;};};if _fgg ._gbg ._gfa {_cge :=uint64 (_fgg ._afb ._eeccb )<<32|uint64 (_fgg ._afb ._cfd );if _affeg :=_bbaa .WritePropertyNoAlign (_cge );_affeg !=nil {return _affeg ;};};return nil ;};

// SetValue sets a value for a control which value can be represented as boolean (on/off).
func (_defb *morphDataControlBoolValue )SetValue (value bool ){_defb .setValueBool (value )};

// ToggleButtonDataControl is a representation of a toggle button ActiveX form.
type ToggleButtonDataControl struct{*morphDataControlBoolValue };func (_dgce *controlBase )readStreamDataM (_cgaa *_bc .Reader ,_ffff bool )error {_dgce ._caa =&streamData {};if _ffff {_dgce ._caa ._cdac =&guidAndPicture {};if _feef :=_dgce ._caa ._cdac .importFromReader (_cgaa );
_feef !=nil {return _feef ;};};return nil ;};func (_fca *LabelControl )readDataBlock (_afd *_bc .Reader )error {_fca ._egf =&labelDataBlock {};if _fca ._gbg ._fdc {if _gbab :=_afd .ReadProperty (&_fca ._egf ._bdbf );_gbab !=nil {return _gbab ;};};if _fca ._gbg ._fac {if _bgd :=_afd .ReadProperty (&_fca ._egf ._dbe );
_bgd !=nil {return _bgd ;};};if _fca ._gbg ._fabf {if _ebef :=_afd .ReadProperty (&_fca ._egf ._adbc );_ebef !=nil {return _ebef ;};};if _fca ._gbg ._cegg {var _ccfd uint32 ;if _gafe :=_afd .ReadProperty (&_ccfd );_gafe !=nil {return _gafe ;};_fca ._egf ._agfd ,_fca ._egf ._fbfa =_gd (_ccfd );
};if _fca ._gbg ._dcf {if _acgf :=_afd .ReadProperty (&_fca ._egf ._fee );_acgf !=nil {return _acgf ;};};if _fca ._gbg ._gaga {if _edd :=_afd .ReadProperty (&_fca ._egf ._fdf );_edd !=nil {return _edd ;};};if _fca ._gbg ._afbg {if _dfdf :=_afd .ReadProperty (&_fca ._egf ._ggfa );
_dfdf !=nil {return _dfdf ;};};if _fca ._gbg ._dcff {if _gcd :=_afd .ReadProperty (&_fca ._egf ._bcd );_gcd !=nil {return _gcd ;};};if _fca ._gbg ._agbf {if _ecc :=_afd .ReadProperty (&_fca ._egf ._bba );_ecc !=nil {return _ecc ;};};if _fca ._gbg ._aad {if _bccg :=_afd .ReadProperty (&_fca ._egf ._debe );
_bccg !=nil {return _bccg ;};};if _fca ._gbg ._bacg {if _dbacd :=_afd .ReadProperty (&_fca ._egf ._dgg );_dbacd !=nil {return _dbacd ;};};if _fca ._gbg ._fgde {if _cafc :=_afd .ReadProperty (&_fca ._egf ._ggbg );_cafc !=nil {return _cafc ;};};return nil ;
};func (_bdcg *morphDataControl )readDataBlock (_bbaad *_bc .Reader )error {_bdcg ._cdb =&morphDataDataBlock {};if _bdcg ._facb ._effb {if _afcg :=_bbaad .ReadProperty (&_bdcg ._cdb ._gcabc );_afcg !=nil {return _afcg ;};};if _bdcg ._facb ._feb {if _eeef :=_bbaad .ReadProperty (&_bdcg ._cdb ._eabb );
_eeef !=nil {return _eeef ;};};if _bdcg ._facb ._dbd {if _aeec :=_bbaad .ReadProperty (&_bdcg ._cdb ._aaed );_aeec !=nil {return _aeec ;};};if _bdcg ._facb ._aggd {if _aagf :=_bbaad .ReadProperty (&_bdcg ._cdb ._efd );_aagf !=nil {return _aagf ;};};if _bdcg ._facb ._afa {if _agbe :=_bbaad .ReadProperty (&_bdcg ._cdb ._ccbf );
_agbe !=nil {return _agbe ;};};if _bdcg ._facb ._abf {if _ebdf :=_bbaad .ReadProperty (&_bdcg ._cdb ._adbb );_ebdf !=nil {return _ebdf ;};};if _bdcg ._facb ._dafa {if _dee :=_bbaad .ReadProperty (&_bdcg ._cdb ._fad );_dee !=nil {return _dee ;};};if _bdcg ._facb ._fce {if _eda :=_bbaad .ReadProperty (&_bdcg ._cdb ._cecd );
_eda !=nil {return _eda ;};};if _bdcg ._facb ._dggb {if _fgda :=_bbaad .ReadProperty (&_bdcg ._cdb ._bgec );_fgda !=nil {return _fgda ;};};if _bdcg ._facb ._dbbb {if _ecfc :=_bbaad .ReadProperty (&_bdcg ._cdb ._caba );_ecfc !=nil {return _ecfc ;};};if _bdcg ._facb ._aacb {if _dcfd :=_bbaad .ReadProperty (&_bdcg ._cdb ._fgbe );
_dcfd !=nil {return _dcfd ;};};if _bdcg ._facb ._cfc {if _dbee :=_bbaad .ReadProperty (&_bdcg ._cdb ._gdda );_dbee !=nil {return _dbee ;};};if _bdcg ._facb ._ebge {if _egda :=_bbaad .ReadProperty (&_bdcg ._cdb ._fcdd );_egda !=nil {return _egda ;};};if _bdcg ._facb ._beag {if _cfa :=_bbaad .ReadProperty (&_bdcg ._cdb ._gbcd );
_cfa !=nil {return _cfa ;};};if _bdcg ._facb ._ace {if _ceaf :=_bbaad .ReadProperty (&_bdcg ._cdb ._daac );_ceaf !=nil {return _ceaf ;};};if _bdcg ._facb ._cdgb {if _badg :=_bbaad .ReadProperty (&_bdcg ._cdb ._bdda );_badg !=nil {return _badg ;};};if _bdcg ._facb ._bdba {if _bbbc :=_bbaad .ReadProperty (&_bdcg ._cdb ._ccea );
_bbbc !=nil {return _bbbc ;};};if _bdcg ._facb ._ccdc {if _eef :=_bbaad .ReadProperty (&_bdcg ._cdb ._gddb );_eef !=nil {return _eef ;};};if _bdcg ._facb ._fdff {if _eaa :=_bbaad .ReadProperty (&_bdcg ._cdb ._cga );_eaa !=nil {return _eaa ;};};if _bdcg ._facb ._dcg {if _dbda :=_bbaad .ReadProperty (&_bdcg ._cdb ._bfg );
_dbda !=nil {return _dbda ;};};if _bdcg ._facb ._adgg {var _ffg uint32 ;if _dcgd :=_bbaad .ReadProperty (&_ffg );_dcgd !=nil {return _dcgd ;};_bdcg ._cdb ._cfg ,_bdcg ._cdb ._bdcf =_gd (_ffg );};if _bdcg ._facb ._dbbc {var _cada uint32 ;if _cda :=_bbaad .ReadProperty (&_cada );
_cda !=nil {return _cda ;};_bdcg ._cdb ._baae ,_bdcg ._cdb ._fbfd =_gd (_cada );};if _bdcg ._facb ._cce {if _ggab :=_bbaad .ReadProperty (&_bdcg ._cdb ._adf );_ggab !=nil {return _ggab ;};};if _bdcg ._facb ._gage {if _eedc :=_bbaad .ReadProperty (&_bdcg ._cdb ._efdd );
_eedc !=nil {return _eedc ;};};if _bdcg ._facb ._cfbd {if _bee :=_bbaad .ReadProperty (&_bdcg ._cdb ._bdgg );_bee !=nil {return _bee ;};};if _bdcg ._facb ._gbga {if _edg :=_bbaad .ReadProperty (&_bdcg ._cdb ._bggg );_edg !=nil {return _edg ;};};if _bdcg ._facb ._bdbff {if _ggfb :=_bbaad .ReadProperty (&_bdcg ._cdb ._dfgf );
_ggfb !=nil {return _ggfb ;};};if _bdcg ._facb ._efag {if _ebfd :=_bbaad .ReadProperty (&_bdcg ._cdb ._egdf );_ebfd !=nil {return _ebfd ;};};if _bdcg ._facb ._fff {var _deff uint32 ;if _gdbc :=_bbaad .ReadProperty (&_deff );_gdbc !=nil {return _gdbc ;};
_bdcg ._cdb ._gce ,_bdcg ._cdb ._ebdg =_gd (_deff );};return nil ;};const (FmPictureAlignmentTopLeft FmPictureAlignment =iota ;FmPictureAlignmentTopRight ;FmPictureAlignmentCenter ;FmPictureAlignmentBottomLeft ;FmPictureAlignmentBottomRight ;);func (_affb *ImageControl )readDataBlock (_abb *_bc .Reader )error {_affb ._bgcc =&imageDataBlock {};
if _affb ._gdc ._abd {if _ffa :=_abb .ReadProperty (&_affb ._bgcc ._adef );_ffa !=nil {return _ffa ;};};if _affb ._gdc ._cad {if _abad :=_abb .ReadProperty (&_affb ._bgcc ._aae );_abad !=nil {return _abad ;};};if _affb ._gdc ._gfd {if _gbd :=_abb .ReadProperty (&_affb ._bgcc ._fef );
_gbd !=nil {return _gbd ;};};if _affb ._gdc ._bdc {if _fdaa :=_abb .ReadProperty (&_affb ._bgcc ._dga );_fdaa !=nil {return _fdaa ;};};if _affb ._gdc ._fcfa {if _eebb :=_abb .ReadProperty (&_affb ._bgcc ._gca );_eebb !=nil {return _eebb ;};};if _affb ._gdc ._acac {if _fga :=_abb .ReadProperty (&_affb ._bgcc ._gfcd );
_fga !=nil {return _fga ;};};if _affb ._gdc ._cagae {if _agd :=_abb .ReadProperty (&_affb ._bgcc ._efa );_agd !=nil {return _agd ;};};if _affb ._gdc ._fbe {if _feae :=_abb .ReadProperty (&_affb ._bgcc ._bda );_feae !=nil {return _feae ;};};if _affb ._gdc ._afef {if _ggf :=_abb .ReadProperty (&_affb ._bgcc ._dbbf );
_ggf !=nil {return _ggf ;};};if _affb ._gdc ._cccc {if _fec :=_abb .ReadProperty (&_affb ._bgcc ._aff );_fec !=nil {return _fec ;};};return nil ;};

// FmPictureAlignment represents one of the five picture aignments according to MS-OFORMS document.
type FmPictureAlignment byte ;

// SetMax sets a button max value.
func (_add *ScrollBarControl )SetMax (max int32 ){_add ._cgbf ._fdd =true ;_add ._gfcff ._aade =max };

// CommandButtonControl is a representation of a commandButton ActiveX form.
type CommandButtonControl struct{controlBase ;_bb *commandButtonPropMask ;_dec *commandButtonDataBlock ;_dce *commandButtonExtraDataBlock ;_bbc *streamData ;};type commandButtonDataBlock struct{_ceg uint32 ;_cbd uint32 ;_bag uint32 ;_aed uint32 ;_cec bool ;
_gaf uint32 ;_gff uint8 ;_gfg uint16 ;_ade rune ;_dcb uint16 ;};func (_gea *controlBase )readStreamDataPM (_bdead *_bc .Reader ,_afae ,_efbd bool )error {_gea ._caa =&streamData {};if _afae {_gea ._caa ._befc =&guidAndPicture {};if _bbeba :=_gea ._caa ._befc .importFromReader (_bdead );
_bbeba !=nil {return _bbeba ;};};if _efbd {_gea ._caa ._cdac =&guidAndPicture {};if _gebd :=_gea ._caa ._cdac .importFromReader (_bdead );_gebd !=nil {return _gebd ;};};return nil ;};type streamData struct{_cdac *guidAndPicture ;_befc *guidAndPicture ;
};func (_facc *morphDataControl )getValueString ()string {if _facc ._facb ._adgg {return _facc ._eaf ._fcae ;};return "";};

// GetHeight returns height of the SpinButton in HIMETRIC (0.01mm)
func (_ccgf *SpinButtonControl )GetHeight ()uint32 {return _ccgf ._faee ._bbaf };type spinButtonExtraDataBlock struct{_bceb uint32 ;_bbaf uint32 ;};

// SetMin sets a button min value.
func (_deca *ScrollBarControl )SetMin (min int32 ){_deca ._cgbf ._fbgf =true ;_deca ._gfcff ._cgga =min };

// GetMax gets a button max value.
func (_ffgc *ScrollBarControl )GetMax ()int32 {return _ffgc ._gfcff ._aade };

// SetWidth sets width of the ScrollBar in HIMETRIC (0.01mm)
func (_dcbf *ScrollBarControl )SetWidth (width uint32 ){_dcbf ._cgbf ._bddf =true ;_dcbf ._bega ._bcfg =width ;};func _gd (_ccg uint32 )(bool ,uint32 ){if _ccg ==0{return false ,0;};_de :=_ccg >=1<<31;if _de {_ccg -=1<<31;};return _de ,_ccg ;};func (_gagf *ScrollBarControl )readDataBlock (_effd *_bc .Reader )error {_gagf ._gfcff =&scrollBarDataBlock {};
if _gagf ._cgbf ._baef {if _ecgf :=_effd .ReadProperty (&_gagf ._gfcff ._gfgd );_ecgf !=nil {return _ecgf ;};};if _gagf ._cgbf ._acef {if _bfb :=_effd .ReadProperty (&_gagf ._gfcff ._fbc );_bfb !=nil {return _bfb ;};};if _gagf ._cgbf ._gad {if _ccbg :=_effd .ReadProperty (&_gagf ._gfcff ._bbef );
_ccbg !=nil {return _ccbg ;};};if _gagf ._cgbf ._fgef {if _bcfd :=_effd .ReadProperty (&_gagf ._gfcff ._edc );_bcfd !=nil {return _bcfd ;};};if _gagf ._cgbf ._fbgf {if _effg :=_effd .ReadProperty (&_gagf ._gfcff ._cgga );_effg !=nil {return _effg ;};};
if _gagf ._cgbf ._fdd {if _eebbg :=_effd .ReadProperty (&_gagf ._gfcff ._aade );_eebbg !=nil {return _eebbg ;};};if _gagf ._cgbf ._ebefe {if _bbdce :=_effd .ReadProperty (&_gagf ._gfcff ._fcbg );_bbdce !=nil {return _bbdce ;};};if _gagf ._cgbf ._eddd {if _gffd :=_effd .ReadProperty (&_gagf ._gfcff ._dge );
_gffd !=nil {return _gffd ;};};if _gagf ._cgbf ._bab {if _aacbg :=_effd .ReadProperty (&_gagf ._gfcff ._cecb );_aacbg !=nil {return _aacbg ;};};if _gagf ._cgbf ._eebg {if _efaa :=_effd .ReadProperty (&_gagf ._gfcff ._dbg );_efaa !=nil {return _efaa ;};
};if _gagf ._cgbf ._efgc {if _bgcf :=_effd .ReadProperty (&_gagf ._gfcff ._gbcde );_bgcf !=nil {return _bgcf ;};};if _gagf ._cgbf ._eca {if _fddd :=_effd .ReadProperty (&_gagf ._gfcff ._dbag );_fddd !=nil {return _fddd ;};};if _gagf ._cgbf ._bece {if _ecdg :=_effd .ReadProperty (&_gagf ._gfcff ._fbgge );
_ecdg !=nil {return _ecdg ;};};if _gagf ._cgbf ._bcdb {if _fedb :=_effd .ReadProperty (&_gagf ._gfcff ._dccab );_fedb !=nil {return _fedb ;};};if _gagf ._cgbf ._faaa {if _dbfg :=_effd .ReadProperty (&_gagf ._gfcff ._ebb );_dbfg !=nil {return _dbfg ;};};
return nil ;};

// SetCaption sets a caption string for a label control.
func (_cbgg *LabelControl )SetCaption (caption string ){_cbgg ._gbg ._cegg =true ;_cbgg ._egf ._fbfa =uint32 (len (caption ));_cbgg ._afb ._bagg =caption ;};type morphDataColumnInfoPropMask struct{};func (_dae *controlBase )setMouseIconBytes (_acg []byte ){if _dae ._caa ._cdac ==nil {_dae ._caa ._cdac =&guidAndPicture {};
};_dae ._caa ._cdac .setStdPictureBytes (_acg );};func (_bfa *morphDataControl )readPropMask (_cee *_bc .Reader )error {var _cdfg uint64 ;if _fbgg :=_b .Read (_cee ,_b .LittleEndian ,&_cdfg );_fbgg !=nil {return _fbgg ;};_bfa ._facb =&morphDataPropMask {};
_bfa ._facb ._effb ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._feb ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._dbd ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._aggd ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._afa ,_cdfg =_bc .PopRightUI64 (_cdfg );
_bfa ._facb ._abf ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._dafa ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._fce ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._fdac ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._dggb ,_cdfg =_bc .PopRightUI64 (_cdfg );
_bfa ._facb ._dbbb ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._aacb ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._cfc ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._ebge ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._beag ,_cdfg =_bc .PopRightUI64 (_cdfg );
_bfa ._facb ._ace ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._cdgb ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._bdba ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._ccdc ,_cdfg =_bc .PopRightUI64 (_cdfg );_cdfg >>=1;_bfa ._facb ._fdff ,_cdfg =_bc .PopRightUI64 (_cdfg );
_bfa ._facb ._dcg ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._adgg ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._dbbc ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._cce ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._gage ,_cdfg =_bc .PopRightUI64 (_cdfg );
_bfa ._facb ._cfbd ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._gbga ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._bdbff ,_cdfg =_bc .PopRightUI64 (_cdfg );_bfa ._facb ._efag ,_cdfg =_bc .PopRightUI64 (_cdfg );_cdfg >>=1;_cdfg >>=1;_bfa ._facb ._fff ,_cdfg =_bc .PopRightUI64 (_cdfg );
return nil ;};

// SetHeight sets height of the SpinButton in HIMETRIC (0.01mm)
func (_acbf *SpinButtonControl )SetHeight (height uint32 ){_acbf ._dged ._aedd =true ;_acbf ._faee ._bbaf =height ;};func (_gddf *SpinButtonControl )readDataBlock (_bfac *_bc .Reader )error {_gddf ._cgf =&spinButtonDataBlock {};if _gddf ._dged ._gcea {if _fgdd :=_bfac .ReadProperty (&_gddf ._cgf ._caab );
_fgdd !=nil {return _fgdd ;};};if _gddf ._dged ._aafb {if _baff :=_bfac .ReadProperty (&_gddf ._cgf ._cbb );_baff !=nil {return _baff ;};};if _gddf ._dged ._cdge {if _ddf :=_bfac .ReadProperty (&_gddf ._cgf ._egdcc );_ddf !=nil {return _ddf ;};};if _gddf ._dged ._cfde {if _eeca :=_bfac .ReadProperty (&_gddf ._cgf ._deeb );
_eeca !=nil {return _eeca ;};};if _gddf ._dged ._ccae {if _gcag :=_bfac .ReadProperty (&_gddf ._cgf ._ecca );_gcag !=nil {return _gcag ;};};if _gddf ._dged ._accf {if _adfad :=_bfac .ReadProperty (&_gddf ._cgf ._gef );_adfad !=nil {return _adfad ;};};if _gddf ._dged ._bfegb {if _fgfc :=_bfac .ReadProperty (&_gddf ._cgf ._dbfe );
_fgfc !=nil {return _fgfc ;};};if _gddf ._dged ._beaf {if _gafg :=_bfac .ReadProperty (&_gddf ._cgf ._gcac );_gafg !=nil {return _gafg ;};};if _gddf ._dged ._acd {if _baba :=_bfac .ReadProperty (&_gddf ._cgf ._aaaf );_baba !=nil {return _baba ;};};if _gddf ._dged ._bdbd {if _cagb :=_bfac .ReadProperty (&_gddf ._cgf ._edcf );
_cagb !=nil {return _cagb ;};};if _gddf ._dged ._ffcd {if _bdbb :=_bfac .ReadProperty (&_gddf ._cgf ._egcc );_bdbb !=nil {return _bdbb ;};};if _gddf ._dged ._cdfgg {if _ded :=_bfac .ReadProperty (&_gddf ._cgf ._bgee );_ded !=nil {return _ded ;};};if _gddf ._dged ._egad {if _fcebf :=_bfac .ReadProperty (&_gddf ._cgf ._bfd );
_fcebf !=nil {return _fcebf ;};};return nil ;};func (_aba *CommandButtonControl )writeDataBlock (_fegg *_bc .Writer )error {if _aba ._bb ._dbb {if _cdff :=_fegg .WriteProperty (_aba ._dec ._ceg );_cdff !=nil {return _cdff ;};};if _aba ._bb ._daf {if _fcf :=_fegg .WriteProperty (_aba ._dec ._cbd );
_fcf !=nil {return _fcf ;};};if _aba ._bb ._fed {if _fcd :=_fegg .WriteProperty (_aba ._dec ._bag );_fcd !=nil {return _fcd ;};};if _aba ._bb ._feg {_gcf :=_ff (_aba ._dec ._aed ,_aba ._dec ._cec );if _bgc :=_fegg .WriteProperty (_gcf );_bgc !=nil {return _bgc ;
};};if _aba ._bb ._efb {if _cca :=_fegg .WriteProperty (_aba ._dec ._gaf );_cca !=nil {return _cca ;};};if _aba ._bb ._gbb {if _cac :=_fegg .WriteProperty (_aba ._dec ._gff );_cac !=nil {return _cac ;};};if _aba ._bb ._geb {if _cde :=_fegg .WriteProperty (_aba ._dec ._gfg );
_cde !=nil {return _cde ;};};if _aba ._bb ._aegc {if _cafb :=_fegg .WriteProperty (_aba ._dec ._ade );_cafb !=nil {return _cafb ;};};if _aba ._bb ._eecc {if _ebf :=_fegg .WriteProperty (_aba ._dec ._dcb );_ebf !=nil {return _ebf ;};};return _fegg .AlignLength (4);
};

// SetHeight sets height of the CommandButton in HIMETRIC (0.01mm)
func (_ggb *CommandButtonControl )SetHeight (height uint32 ){_ggb ._bb ._ebe =true ;_ggb ._dce ._ega =height ;};

// GetHeight returns height of the CommandButton in HIMETRIC (0.01mm)
func (_eed *CommandButtonControl )GetHeight ()uint32 {return _eed ._dce ._ega };func _bfc (_aac *_bc .Reader )(*morphDataControl ,error ){_cgea :=&morphDataControl {};if _dgga :=_cgea .readPropMask (_aac );_dgga !=nil {return nil ,_dgga ;};if _efed :=_cgea .readDataBlock (_aac );
_efed !=nil {return nil ,_efed ;};if _feca :=_cgea .readExtraDataBlock (_aac );_feca !=nil {return nil ,_feca ;};if _fecb :=_cgea .readStreamDataMP (_aac ,_cgea ._facb ._gbga ,_cgea ._facb ._bdbff );_fecb !=nil {return nil ,_fecb ;};switch _cgea ._cdb ._fad {case _gfb ,_eab :if _ece :=_cgea .readColumnInfo (_aac );
_ece !=nil {return nil ,_ece ;};if _ebd :=_cgea .readColumnInfoPropMask (_aac );_ebd !=nil {return nil ,_ebd ;};if _agba :=_cgea .readColumnInfoDataBlock (_aac );_agba !=nil {return nil ,_agba ;};};if _fggc :=_cgea .readTheRest (_aac );_fggc !=nil {return nil ,_fggc ;
};return _cgea ,nil ;};func (_cgda *morphDataControl )writeColumnInfo (_cgb *_bc .Writer )error {return nil };

// GetValue gets a value from a control which value can be represented as boolean (on/off).
func (_ebc *morphDataControlBoolValue )GetValue ()bool {return _ebc .getValueBool ()};type morphDataPropMask struct{_effb bool ;_feb bool ;_dbd bool ;_aggd bool ;_afa bool ;_abf bool ;_dafa bool ;_fce bool ;_fdac bool ;_dggb bool ;_dbbb bool ;_aacb bool ;
_cfc bool ;_ebge bool ;_beag bool ;_ace bool ;_cdgb bool ;_bdba bool ;_ccdc bool ;_fdff bool ;_dcg bool ;_adgg bool ;_dbbc bool ;_cce bool ;_gage bool ;_cfbd bool ;_gbga bool ;_bdbff bool ;_efag bool ;_fff bool ;};func _gdcf (_ddd *_bc .Reader )(*ImageControl ,error ){_dbcd :=&ImageControl {};
if _edef :=_dbcd .readPropMask (_ddd );_edef !=nil {return nil ,_edef ;};if _dgd :=_dbcd .readDataBlock (_ddd );_dgd !=nil {return nil ,_dgd ;};if _cdcf :=_dbcd .readExtraDataBlock (_ddd );_cdcf !=nil {return nil ,_cdcf ;};if _dgf :=_dbcd .readStreamDataPM (_ddd ,_dbcd ._gdc ._cagae ,_dbcd ._gdc ._cccc );
_dgf !=nil {return nil ,_dgf ;};if _acga :=_dbcd .readTheRest (_ddd );_acga !=nil {return nil ,_acga ;};return _dbcd ,nil ;};func (_dbdf *ScrollBarControl )export (_bfca *_bc .Writer )error {if _egg :=_dbdf .writePropMask (_bfca );_egg !=nil {return _egg ;
};if _abfe :=_dbdf .writeDataBlock (_bfca );_abfe !=nil {return _abfe ;};if _agee :=_dbdf .writeExtraDataBlock (_bfca );_agee !=nil {return _agee ;};_dbdf ._eecd =uint16 (_bfca .Len ()-4);if _daag :=_dbdf .writeStreamDataM (_bfca );_daag !=nil {return _daag ;
};return _dbdf .writeTheRest (_bfca );};func (_eea *guidAndPicture )export (_bdea *_bc .Writer )error {if _ ,_faag :=_cb .Copy (_bdea ,_f .NewBuffer (_eea ._aaa ));_faag !=nil {return _faag ;};if _aegb :=_bdea .WriteProperty (_eea ._caga ._cbe );_aegb !=nil {return _aegb ;
};if _deb :=_bdea .WriteProperty (_eea ._caga ._agc );_deb !=nil {return _deb ;};_ ,_adb :=_cb .Copy (_bdea ,_eea ._caga ._dag );if _adb !=nil {return _adb ;};return nil ;};func (_cdfd *controlBase )readStreamDataMP (_egaf *_bc .Reader ,_dceg ,_dcdb bool )error {_cdfd ._caa =&streamData {};
if _dceg {_cdfd ._caa ._cdac =&guidAndPicture {};if _begc :=_cdfd ._caa ._cdac .importFromReader (_egaf );_begc !=nil {return _begc ;};};if _dcdb {_cdfd ._caa ._befc =&guidAndPicture {};if _bbcc :=_cdfd ._caa ._befc .importFromReader (_egaf );_bbcc !=nil {return _bbcc ;
};};return nil ;};

// GetHeight returns height of the ScrollBar in HIMETRIC (0.01mm)
func (_ecfcd *ScrollBarControl )GetHeight ()uint32 {return _ecfcd ._bega ._cadb };

// GetBackColor gets a button text color value for a system palette from a commandButton control.
func (_acb *CommandButtonControl )GetBackColor ()uint32 {return _acb ._dec ._cbd };type labelPropMask struct{_fdc bool ;_fac bool ;_fabf bool ;_cegg bool ;_dcf bool ;_gfa bool ;_gaga bool ;_afbg bool ;_dcff bool ;_agbf bool ;_aad bool ;_bacg bool ;_fgde bool ;
};func (_bfeg *morphDataControl )writeColumnInfoPropMask (_eeff *_bc .Writer )error {return nil };func (_fcge *morphDataControl )writePropMask (_ccba *_bc .Writer )error {_abda :=uint64 (0);_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._effb );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._feb );
_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._dbd );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._aggd );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._afa );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._abf );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._dafa );
_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._fce );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._fdac );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._dggb );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._dbbb );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._aacb );
_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._cfc );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._ebge );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._beag );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._ace );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._cdgb );
_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._bdba );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._ccdc );_abda >>=1;_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._fdff );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._dcg );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._adgg );
_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._dbbc );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._cce );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._gage );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._cfbd );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._gbga );
_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._bdbff );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._efag );_abda >>=1;_abda =_bc .PushLeftUI64 (_abda ,true );_abda =_bc .PushLeftUI64 (_abda ,_fcge ._facb ._fff );_abda >>=31;return _b .Write (_ccba ,_b .LittleEndian ,_abda );
};type morphDataColumnInfoDataBlock struct{};func (_geda *ScrollBarControl )readPropMask (_gdaa *_bc .Reader )error {var _efddd uint32 ;if _cdfb :=_b .Read (_gdaa ,_b .LittleEndian ,&_efddd );_cdfb !=nil {return _cdfb ;};_geda ._cgbf =&scrollBarPropMask {};
_geda ._cgbf ._baef ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._acef ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._gad ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._bddf ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._fgef ,_efddd =_bc .PopRightUI32 (_efddd );
_geda ._cgbf ._fbgf ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._fdd ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._ebefe ,_efddd =_bc .PopRightUI32 (_efddd );_efddd >>=1;_geda ._cgbf ._eddd ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._bab ,_efddd =_bc .PopRightUI32 (_efddd );
_geda ._cgbf ._eebg ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._efgc ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._eca ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._bece ,_efddd =_bc .PopRightUI32 (_efddd );_geda ._cgbf ._bcdb ,_efddd =_bc .PopRightUI32 (_efddd );
_geda ._cgbf ._faaa ,_efddd =_bc .PopRightUI32 (_efddd );return nil ;};

// ImportFromFile makes a Control from a file in a storage.
func ImportFromFile (storagePath string )(*Control ,error ){_ba ,_bae :=_be .Open (storagePath );if _bae !=nil {return nil ,_bae ;};defer _ba .Close ();_bf ,_bae :=_ac .New (_ba );if _bae !=nil {return nil ,_bae ;};_bd ,_bae :=_fag (_bf );if _bae !=nil {return nil ,_bae ;
};_fc ,_bae :=_bf .GetEntry ("\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0073");if _bae !=nil {return nil ,_bae ;};_bce :=make ([]byte ,_fc .Size );_ ,_bae =_fc .Read (_bce );if _bae !=nil {return nil ,_bae ;};_cd :=&Control {_d :storagePath };_egc ,_bae :=_bc .NewReader (_bce );
if _bae !=nil {return nil ,_bae ;};if _bef :=_b .Read (_egc ,_b .LittleEndian ,&_cd ._ca );_bef !=nil {return nil ,_bef ;};if _fa :=_b .Read (_egc ,_b .LittleEndian ,&_cd ._db );_fa !=nil {return nil ,_fa ;};if _caf :=_b .Read (_egc ,_b .LittleEndian ,&_cd ._cbf );
_caf !=nil {return nil ,_caf ;};switch _bd {case "\u0043\u0068\u0065\u0063\u006b\u0042\u006f\u0078":_ee ,_dba :=_bfc (_egc );if _dba !=nil {return nil ,_dba ;};_ee ._aee =true ;_cd .Choice =&ControlChoice {CheckBox :&CheckBoxDataControl {&morphDataControlBoolValue {_ee }}};
case "\u0054e\u0078\u0074\u0042\u006f\u0078":_bdg ,_ce :=_bfc (_egc );if _ce !=nil {return nil ,_ce ;};_bdg ._aee =true ;_cd .Choice =&ControlChoice {TextBox :&TextBoxDataControl {&morphDataControlStringValue {_bdg }}};case "\u0043\u006f\u006d\u0062\u006f\u0042\u006f\u0078":_cag ,_ae :=_bfc (_egc );
if _ae !=nil {return nil ,_ae ;};_cag ._aee =true ;_cd .Choice =&ControlChoice {ComboBox :&ComboBoxDataControl {&morphDataControlStringValue {_cag }}};case "\u004ci\u0073\u0074\u0042\u006f\u0078":_g ,_ea :=_bfc (_egc );if _ea !=nil {return nil ,_ea ;};
_g ._aee =true ;_cd .Choice =&ControlChoice {ListBox :&ListBoxDataControl {&morphDataControlStringValue {_g }}};case "\u004f\u0070\u0074i\u006f\u006e\u0042\u0075\u0074\u0074\u006f\u006e":_fab ,_dbac :=_bfc (_egc );if _dbac !=nil {return nil ,_dbac ;};_fab ._aee =true ;
_cd .Choice =&ControlChoice {OptionButton :&OptionButtonDataControl {&morphDataControlBoolValue {_fab }}};case "\u0054\u006f\u0067g\u006c\u0065\u0042\u0075\u0074\u0074\u006f\u006e":_ab ,_bde :=_bfc (_egc );if _bde !=nil {return nil ,_bde ;};_ab ._aee =true ;
_cd .Choice =&ControlChoice {ToggleButton :&ToggleButtonDataControl {&morphDataControlBoolValue {_ab }}};case "\u004c\u0061\u0062e\u006c":_dbad ,_bfe :=_dddd (_egc );if _bfe !=nil {return nil ,_bfe ;};_cd .Choice =&ControlChoice {Label :_dbad };case "\u0053\u0070\u0069\u006e\u0042\u0075\u0074\u0074\u006f\u006e":_fb ,_cg :=_dgcf (_egc );
if _cg !=nil {return nil ,_cg ;};_cd .Choice =&ControlChoice {SpinButton :_fb };case "\u0043\u006f\u006d\u006d\u0061\u006e\u0064\u0042\u0075\u0074\u0074\u006f\u006e":_dc ,_cc :=_baf (_egc );if _cc !=nil {return nil ,_cc ;};_cd .Choice =&ControlChoice {CommandButton :_dc };
case "\u0053c\u0072\u006f\u006c\u006c\u0042\u0061r":_eb ,_gc :=_egea (_egc );if _gc !=nil {return nil ,_gc ;};_cd .Choice =&ControlChoice {ScrollBar :_eb };default:_aa :=&controlBase {};if _ceb :=_aa .readTheRest (_egc );_ceb !=nil {return nil ,_ceb ;};
_cd .Choice =&ControlChoice {_bec :_aa };};return _cd ,nil ;};func (_deeg *morphDataControl )writeColumnInfoDataBlock (_bfgd *_bc .Writer )error {return nil };

// SetPosition sets a button position value.
func (_egba *SpinButtonControl )SetPosition (position int32 ){_egba ._dged ._accf =true ;_egba ._cgf ._gef =position ;};

// GetWidth returns width of the morphDataControl in HIMETRIC (0.01mm)
func (_cfe *morphDataControl )GetWidth ()uint32 {return _cfe ._eaf ._dcfa };type spinButtonDataBlock struct{_caab uint32 ;_cbb uint32 ;_egdcc uint32 ;_deeb int32 ;_ecca int32 ;_gef int32 ;_dbfe int32 ;_gcac int32 ;_aaaf int32 ;_edcf uint32 ;_egcc uint32 ;
_bgee uint16 ;_bfd uint8 ;};type morphDataDataBlock struct{_gcabc uint32 ;_eabb uint32 ;_aaed uint32 ;_efd uint32 ;_ccbf byte ;_adbb byte ;_fad byte ;_cecd byte ;_bgec rune ;_caba uint32 ;_fgbe uint16 ;_gdda int16 ;_fcdd int16 ;_gbcd uint16 ;_daac uint16 ;
_bdda uint8 ;_ccea uint8 ;_gddb uint8 ;_cga uint8 ;_bfg uint8 ;_bdcf uint32 ;_cfg bool ;_fbfd uint32 ;_baae bool ;_adf uint32 ;_efdd uint32 ;_bdgg uint32 ;_bggg uint16 ;_dfgf uint16 ;_egdf rune ;_ebdg uint32 ;_gce bool ;};func (_bgcb *LabelControl )writeDataBlock (_ccd *_bc .Writer )error {if _bgcb ._gbg ._fdc {if _daaf :=_ccd .WriteProperty (_bgcb ._egf ._bdbf );
_daaf !=nil {return _daaf ;};};if _bgcb ._gbg ._fac {if _efe :=_ccd .WriteProperty (_bgcb ._egf ._dbe );_efe !=nil {return _efe ;};};if _bgcb ._gbg ._fabf {if _fge :=_ccd .WriteProperty (_bgcb ._egf ._adbc );_fge !=nil {return _fge ;};};if _bgcb ._gbg ._cegg {_dfab :=_ff (_bgcb ._egf ._fbfa ,_bgcb ._egf ._agfd );
if _dbab :=_ccd .WriteProperty (_dfab );_dbab !=nil {return _dbab ;};};if _bgcb ._gbg ._dcf {if _ccfgc :=_ccd .WriteProperty (_bgcb ._egf ._fee );_ccfgc !=nil {return _ccfgc ;};};if _bgcb ._gbg ._gaga {if _debee :=_ccd .WriteProperty (_bgcb ._egf ._fdf );
_debee !=nil {return _debee ;};};if _bgcb ._gbg ._afbg {if _efec :=_ccd .WriteProperty (_bgcb ._egf ._ggfa );_efec !=nil {return _efec ;};};if _bgcb ._gbg ._dcff {if _dfbg :=_ccd .WriteProperty (_bgcb ._egf ._bcd );_dfbg !=nil {return _dfbg ;};};if _bgcb ._gbg ._agbf {if _cfb :=_ccd .WriteProperty (_bgcb ._egf ._bba );
_cfb !=nil {return _cfb ;};};if _bgcb ._gbg ._aad {if _ada :=_ccd .WriteProperty (_bgcb ._egf ._debe );_ada !=nil {return _ada ;};};if _bgcb ._gbg ._bacg {if _afcc :=_ccd .WriteProperty (_bgcb ._egf ._dgg );_afcc !=nil {return _afcc ;};};if _bgcb ._gbg ._fgde {if _adae :=_ccd .WriteProperty (_bgcb ._egf ._ggbg );
_adae !=nil {return _adae ;};};return _ccd .AlignLength (4);};var _abe =len (_faff );

// SetCaption sets a caption string for a morph control.
func (_fbeb *morphDataControl )SetCaption (caption string ){if _fbeb ._aee {_fbeb ._facb ._dbbc =true ;_fbeb ._cdb ._fbfd =uint32 (len (caption ));_fbeb ._eaf ._ffcc =caption ;};};type scrollBarPropMask struct{_baef bool ;_acef bool ;_gad bool ;_fgef bool ;
_bddf bool ;_fbgf bool ;_fdd bool ;_ebefe bool ;_eddd bool ;_bab bool ;_eebg bool ;_efgc bool ;_eca bool ;_bece bool ;_bcdb bool ;_faaa bool ;};

// TextBoxDataControl is a representation of a text box ActiveX form.
type TextBoxDataControl struct{*morphDataControlStringValue };

// SetWidth sets width of the Label in HIMETRIC (0.01mm)
func (_baa *LabelControl )SetWidth (width uint32 ){_baa ._gbg ._gfa =true ;_baa ._afb ._eeccb =width };func _ff (_dac uint32 ,_bcg bool )uint32 {if _dac ==0{return 0;};if _bcg {_dac |=1<<31;};return _dac ;};

// GetWidth returns width of the SpinButton in HIMETRIC (0.01mm)
func (_fbebf *SpinButtonControl )GetWidth ()uint32 {return _fbebf ._faee ._bceb };func _egea (_abae *_bc .Reader )(*ScrollBarControl ,error ){_efbgc :=&ScrollBarControl {};if _adfa :=_efbgc .readPropMask (_abae );_adfa !=nil {return nil ,_adfa ;};if _ffbe :=_efbgc .readDataBlock (_abae );
_ffbe !=nil {return nil ,_ffbe ;};if _gceb :=_efbgc .readExtraDataBlock (_abae );_gceb !=nil {return nil ,_gceb ;};if _fceb :=_efbgc .readStreamDataM (_abae ,_efbgc ._cgbf ._faaa );_fceb !=nil {return nil ,_fceb ;};if _cbgc :=_efbgc .readTheRest (_abae );
_cbgc !=nil {return nil ,_cbgc ;};return _efbgc ,nil ;};

// GetBackColor gets a button text color value for a system palette from a scrollBar control.
func (_aedg *ScrollBarControl )GetBackColor ()uint32 {return _aedg ._gfcff ._fbc };func (_cadab *morphDataControl )readColumnInfoDataBlock (_efc *_bc .Reader )error {return nil };const _def uint32 =0x0000746C;

// SetBackColor sets a button text color value from a system palette for a scrollBar control.
func (_fbee *ScrollBarControl )SetBackColor (backColor uint32 ){_fbee ._cgbf ._acef =true ;_fbee ._gfcff ._fbc =backColor ;};

// SetHeight sets height of the Label in HIMETRIC (0.01mm)
func (_bcc *LabelControl )SetHeight (height uint32 ){_bcc ._gbg ._gfa =true ;_bcc ._afb ._cfd =height };

// SetForeColor sets a button text color value from a system palette for a spinButton control.
func (_fgf *SpinButtonControl )SetForeColor (foreColor uint32 ){_fgf ._dged ._gcea =true ;_fgf ._cgf ._caab =foreColor ;};

// ExportToByteArray makes a byte array from a control as it is stored in .bin files.
func (_ef *Control )ExportToByteArray ()([]byte ,error ){_gg ,_da :=_be .Open (_ef ._d );if _da !=nil {return nil ,_da ;};defer _gg .Close ();_fe ,_da :=_ac .New (_gg );if _da !=nil {return nil ,_da ;};_eae :=_bc .NewWriter ();if _gga :=_b .Write (_eae ,_b .LittleEndian ,&_ef ._ca );
_gga !=nil {return nil ,_gga ;};if _cf :=_b .Write (_eae ,_b .LittleEndian ,&_ef ._db );_cf !=nil {return nil ,_cf ;};if _cdg :=_b .Write (_eae ,_b .LittleEndian ,uint16 (0));_cdg !=nil {return nil ,_cdg ;};var _fea error ;if _fd :=_ef .Choice ;_fd !=nil {if _fd .CheckBox !=nil {_fea =_fd .CheckBox .export (_eae );
}else if _fd .TextBox !=nil {_fea =_fd .TextBox .export (_eae );}else if _fd .ComboBox !=nil {_fea =_fd .ComboBox .export (_eae );}else if _fd .ListBox !=nil {_fea =_fd .ListBox .export (_eae );}else if _fd .OptionButton !=nil {_fea =_fd .OptionButton .export (_eae );
}else if _fd .ToggleButton !=nil {_fea =_fd .ToggleButton .export (_eae );}else if _fd .Label !=nil {_fea =_fd .Label .export (_eae );}else if _fd .SpinButton !=nil {_fea =_fd .SpinButton .export (_eae );}else if _fd .CommandButton !=nil {_fea =_fd .CommandButton .export (_eae );
}else if _fd .ScrollBar !=nil {_fea =_fd .ScrollBar .export (_eae );}else {_fea =_fd ._bec .writeTheRest (_eae );};};if _fea !=nil {return nil ,_fea ;};if _fdg :=_eae .WriteByteAt (byte (_ef ._cbf ),2);_fdg !=nil {return nil ,_fdg ;};if _df :=_eae .WriteByteAt (byte (_ef ._cbf >>8),3);
_df !=nil {return nil ,_df ;};_aea ,_da :=_fe .GetEntry ("\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0073");if _da !=nil {return nil ,_da ;};if _ge :=_aea .SetEntryContent (_eae .Bytes ());_ge !=nil {return nil ,_ge ;};return _fe .Export ();};

// SetHeight sets height of the morphDataControl in HIMETRIC (0.01mm)
func (_dcea *morphDataControl )SetHeight (height uint32 ){_dcea ._facb ._fdac =true ;_dcea ._eaf ._ceee =height ;};func (_beg *morphDataControl )setValueBool (_ebaa bool ){_beg ._facb ._adgg =true ;_beg ._cdb ._bdcf =1;_beg ._cdb ._cfg =true ;_bffa :="\u0030";
if _ebaa {_bffa ="\u0031";};_beg ._eaf ._fcae =_bffa ;};func (_beab *SpinButtonControl )writeExtraDataBlock (_ddbc *_bc .Writer )error {if _beab ._dged ._aedd {_aaec :=uint64 (_beab ._faee ._bceb )<<32|uint64 (_beab ._faee ._bbaf );if _bacb :=_ddbc .WritePropertyNoAlign (_aaec );
_bacb !=nil {return _bacb ;};};return nil ;};

// ComboBoxDataControl is a representation of a combo box ActiveX form.
type ComboBoxDataControl struct{*morphDataControlStringValue };

// GetWidth returns width of the ScrollBar in HIMETRIC (0.01mm)
func (_gbf *ScrollBarControl )GetWidth ()uint32 {return _gbf ._bega ._bcfg };func (_agg *controlBase )getMouseIconBytes ()[]byte {return _agg ._caa ._cdac .getStdPictureBytes ()};

// GetCaption gets a caption string from a label control.
func (_fbg *LabelControl )GetCaption ()string {return _fbg ._afb ._bagg };func (_ggc *morphDataControl )readColumnInfo (_dfcc *_bc .Reader )error {return nil };func _fag (_gf *_ac .Reader )(string ,error ){_fcb ,_gb :=_gf .GetEntry ("\u0043o\u006d\u0070\u004f\u0062\u006a");
if _gb !=nil {return "",_gb ;};_gba :=make ([]byte ,_fcb .Size );_ ,_gb =_fcb .Read (_gba );if _gb !=nil {return "",_gb ;};_gdd :=_f .Split (_gba ,[]byte ("\u002e"));if len (_gdd )< 2{return "",_eg .New ("\u0055\u006e\u006bn\u006f\u0077\u006e\u0020\u0066\u006f\u0072\u006d");
};return string (_gdd [len (_gdd )-2]),nil ;};type controlBase struct{_eecd uint16 ;_aee bool ;_caa *streamData ;_cefd []byte ;};const _agga =1;func (_dbcf *LabelControl )readExtraDataBlock (_degb *_bc .Reader )error {_dbcf ._afb =&labelExtraDataBlock {};
if _dbcf ._egf ._fbfa > 0{_cdffa ,_eead :=_degb .ReadStringProperty (_dbcf ._egf ._fbfa );if _eead !=nil {return _eead ;};_dbcf ._afb ._bagg =_cdffa ;};if _dbcf ._gbg ._gfa {var _ceag uint64 ;if _ecgg :=_degb .ReadPairProperty (&_ceag );_ecgg !=nil {return _ecgg ;
};_dbcf ._afb ._cfd =uint32 (_ceag );_dbcf ._afb ._eeccb =uint32 (_ceag >>32);};return nil ;};func (_acf *ScrollBarControl )writeExtraDataBlock (_fgag *_bc .Writer )error {if _acf ._cgbf ._bddf {_dcdd :=uint64 (_acf ._bega ._bcfg )<<32|uint64 (_acf ._bega ._cadb );
if _cadc :=_fgag .WritePropertyNoAlign (_dcdd );_cadc !=nil {return _cadc ;};};return nil ;};type spinButtonPropMask struct{_gcea bool ;_aafb bool ;_cdge bool ;_aedd bool ;_cfde bool ;_ccae bool ;_accf bool ;_bfegb bool ;_beaf bool ;_acd bool ;_bdbd bool ;
_ffcd bool ;_cdfgg bool ;_egad bool ;};

// CheckBoxDataControl is a representation of a check box ActiveX form.
type CheckBoxDataControl struct{*morphDataControlBoolValue };

// GetPosition gets a button position value.
func (_ecb *ScrollBarControl )GetPosition ()int32 {return _ecb ._gfcff ._fcbg };

// SetBackColor sets a button text color value from a system palette for a label control.
func (_decd *LabelControl )SetBackColor (backColor uint32 ){_decd ._gbg ._fac =true ;_decd ._egf ._dbe =backColor ;};func (_abdc *SpinButtonControl )export (_affeb *_bc .Writer )error {if _efde :=_abdc .writePropMask (_affeb );_efde !=nil {return _efde ;
};if _dfdb :=_abdc .writeDataBlock (_affeb );_dfdb !=nil {return _dfdb ;};if _afeb :=_abdc .writeExtraDataBlock (_affeb );_afeb !=nil {return _afeb ;};_abdc ._eecd =uint16 (_affeb .Len ()-4);if _dgbe :=_abdc .writeStreamDataM (_affeb );_dgbe !=nil {return _dgbe ;
};return _abdc .writeTheRest (_affeb );};func (_gbfa *ScrollBarControl )writePropMask (_aebf *_bc .Writer )error {_fafb :=uint32 (0);_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._baef );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._acef );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._gad );
_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._bddf );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._fgef );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._fbgf );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._fdd );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._ebefe );
_fafb >>=1;_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._eddd );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._bab );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._eebg );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._efgc );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._eca );
_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._bece );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._bcdb );_fafb =_bc .PushLeftUI32 (_fafb ,_gbfa ._cgbf ._faaa );_fafb >>=15;return _b .Write (_aebf ,_b .LittleEndian ,_fafb );};type scrollBarDataBlock struct{_gfgd uint32 ;
_fbc uint32 ;_bbef uint32 ;_edc uint8 ;_cgga int32 ;_aade int32 ;_fcbg int32 ;_dge int32 ;_cecb int32 ;_dbg int32 ;_gbcde int32 ;_dbag uint32 ;_fbgge uint32 ;_dccab uint32 ;_ebb uint16 ;};func (_ffccd *SpinButtonControl )readPropMask (_fbed *_bc .Reader )error {var _efdf uint32 ;
if _baacc :=_b .Read (_fbed ,_b .LittleEndian ,&_efdf );_baacc !=nil {return _baacc ;};_ffccd ._dged =&spinButtonPropMask {};_ffccd ._dged ._gcea ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._aafb ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._cdge ,_efdf =_bc .PopRightUI32 (_efdf );
_ffccd ._dged ._aedd ,_efdf =_bc .PopRightUI32 (_efdf );_efdf >>=1;_ffccd ._dged ._cfde ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._ccae ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._accf ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._bfegb ,_efdf =_bc .PopRightUI32 (_efdf );
_ffccd ._dged ._beaf ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._acd ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._bdbd ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._ffcd ,_efdf =_bc .PopRightUI32 (_efdf );_ffccd ._dged ._cdfgg ,_efdf =_bc .PopRightUI32 (_efdf );
_ffccd ._dged ._egad ,_efdf =_bc .PopRightUI32 (_efdf );return nil ;};func _baf (_aeb *_bc .Reader )(*CommandButtonControl ,error ){_dca :=&CommandButtonControl {};if _cef :=_dca .readPropMask (_aeb );_cef !=nil {return nil ,_cef ;};if _cebc :=_dca .readDataBlock (_aeb );
_cebc !=nil {return nil ,_cebc ;};if _aeg :=_dca .readExtraDataBlock (_aeb );_aeg !=nil {return nil ,_aeg ;};if _ec :=_dca .readStreamDataPM (_aeb ,_dca ._bb ._geb ,_dca ._bb ._eecc );_ec !=nil {return nil ,_ec ;};if _ecg :=_dca .readTheRest (_aeb );_ecg !=nil {return nil ,_ecg ;
};return _dca ,nil ;};type labelDataBlock struct{_bdbf uint32 ;_dbe uint32 ;_adbc uint32 ;_fbfa uint32 ;_agfd bool ;_fee uint32 ;_fdf uint8 ;_ggfa uint32 ;_bcd uint16 ;_bba uint16 ;_debe uint16 ;_dgg rune ;_ggbg uint16 ;};

// SetMin sets a button min value.
func (_gdg *SpinButtonControl )SetMin (min int32 ){_gdg ._dged ._cfde =true ;_gdg ._cgf ._deeb =min };

// SetForeColor sets a button text color value from a system palette for a label control.
func (_agbgf *LabelControl )SetForeColor (foreColor uint32 ){_agbgf ._gbg ._fdc =true ;_agbgf ._egf ._bdbf =foreColor ;};

// SpinButtonControl is a representation of a spinButton ActiveX form.
type SpinButtonControl struct{controlBase ;_dged *spinButtonPropMask ;_cgf *spinButtonDataBlock ;_faee *spinButtonExtraDataBlock ;_cfda *streamData ;};

// SetForeColor sets a button text color value from a system palette for a commandButton control.
func (_ga *CommandButtonControl )SetForeColor (foreColor uint32 ){_ga ._bb ._dbb =true ;_ga ._dec ._ceg =foreColor ;};

// GetWidth returns width of the Label in HIMETRIC (0.01mm)
func (_bdac *LabelControl )GetWidth ()uint32 {return _bdac ._afb ._eeccb };func (_cgdf *LabelControl )readPropMask (_cgg *_bc .Reader )error {var _eee uint32 ;if _bff :=_b .Read (_cgg ,_b .LittleEndian ,&_eee );_bff !=nil {return _bff ;};_cgdf ._gbg =&labelPropMask {};
_cgdf ._gbg ._fdc ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._fac ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._fabf ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._cegg ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._dcf ,_eee =_bc .PopRightUI32 (_eee );
_cgdf ._gbg ._gfa ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._gaga ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._afbg ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._dcff ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._agbf ,_eee =_bc .PopRightUI32 (_eee );
_cgdf ._gbg ._aad ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._bacg ,_eee =_bc .PopRightUI32 (_eee );_cgdf ._gbg ._fgde ,_eee =_bc .PopRightUI32 (_eee );return nil ;};func (_bdb *LabelControl )export (_cba *_bc .Writer )error {if _baea :=_bdb .writePropMask (_cba );
_baea !=nil {return _baea ;};if _dcc :=_bdb .writeDataBlock (_cba );_dcc !=nil {return _dcc ;};if _gcab :=_bdb .writeExtraDataBlock (_cba );_gcab !=nil {return _gcab ;};_bdb ._eecd =uint16 (_cba .Len ()-4);if _deg :=_bdb .writeStreamDataPM (_cba );_deg !=nil {return _deg ;
};return _bdb .writeTheRest (_cba );};func (_fbb *controlBase )readTheRest (_ccb *_bc .Reader )error {_egd :=_f .NewBuffer ([]byte {});_ ,_ed :=_cb .Copy (_egd ,_ccb );if _ed !=nil {return _ed ;};_fbb ._cefd =_egd .Bytes ();return nil ;};func (_cdd *morphDataControl )readColumnInfoPropMask (_ceab *_bc .Reader )error {return nil };


// SetBackColor sets a button text color value from a system palette for a commandButton control.
func (_ad *CommandButtonControl )SetBackColor (backColor uint32 ){_ad ._bb ._daf =true ;_ad ._dec ._cbd =backColor ;};func (_ddb *ImageControl )readExtraDataBlock (_fdb *_bc .Reader )error {_ddb ._baed =&imageExtraDataBlock {};if _ddb ._gdc ._cgd {var _fgd uint64 ;
if _bca :=_fdb .ReadPairProperty (&_fgd );_bca !=nil {return _bca ;};_ddb ._baed ._bbe =uint32 (_fgd );_ddb ._baed ._dea =uint32 (_fgd >>32);};return nil ;};func (_cdc *CommandButtonControl )writePropMask (_ecd *_bc .Writer )error {_cdf :=uint32 (0);_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._dbb );
_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._daf );_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._fed );_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._feg );_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._efb );_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._ebe );_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._gbb );
_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._geb );_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._aegc );_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._aaf );_cdf =_bc .PushLeftUI32 (_cdf ,_cdc ._bb ._eecc );_cdf >>=21;return _b .Write (_ecd ,_b .LittleEndian ,_cdf );
};func (_eace *SpinButtonControl )writePropMask (_dfac *_bc .Writer )error {_ebgb :=uint32 (0);_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._gcea );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._aafb );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._cdge );
_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._aedd );_ebgb >>=1;_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._cfde );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._ccae );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._accf );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._bfegb );
_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._beaf );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._acd );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._bdbd );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._ffcd );_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._cdfgg );
_ebgb =_bc .PushLeftUI32 (_ebgb ,_eace ._dged ._egad );_ebgb >>=17;return _b .Write (_dfac ,_b .LittleEndian ,_ebgb );};type labelExtraDataBlock struct{_eeccb uint32 ;_cfd uint32 ;_bagg string ;};