//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package axcontrol ;import (_gd "bytes";_f "encoding/binary";_d "errors";_a "fmt";_c "github.com/unidoc/unioffice/v2/common/tempstorage";_ab "github.com/unidoc/unioffice/v2/internal/mscfb";_dg "github.com/unidoc/unioffice/v2/internal/mscfb/rw";_db "github.com/unidoc/unioffice/v2/schema/schemas.microsoft.com/office/activeX";
_af "io";);func _agd (_be *_ab .Reader )(string ,error ){_dfg ,_gbc :=_be .GetEntry ("\u0043o\u006d\u0070\u004f\u0062\u006a");if _gbc !=nil {return "",_gbc ;};_adb :=make ([]byte ,_dfg .Size );_ ,_gbc =_dfg .Read (_adb );if _gbc !=nil {return "",_gbc ;
};_fed :=_gd .Split (_adb ,[]byte ("\u002e"));if len (_fed )< 2{return "",_d .New ("\u0055\u006e\u006bn\u006f\u0077\u006e\u0020\u0066\u006f\u0072\u006d");};return string (_fed [len (_fed )-2]),nil ;};type commandButtonPropMask struct{_ef bool ;_agb bool ;
_bee bool ;_gga bool ;_efe bool ;_eaa bool ;_cefe bool ;_fcc bool ;_gdb bool ;_add bool ;_bf bool ;};func (_cfae *LabelControl )writeExtraDataBlock (_ffg *_dg .Writer )error {if _cfae ._cdfe ._eag > 0{if _bbde :=_ffg .WriteStringProperty (_cfae ._fea ._gdbf );
_bbde !=nil {return _bbde ;};};if _cfae ._agf ._decae {_gfaf :=uint64 (_cfae ._fea ._cae )<<32|uint64 (_cfae ._fea ._ffc );if _fcca :=_ffg .WritePropertyNoAlign (_gfaf );_fcca !=nil {return _fcca ;};};return nil ;};

// SetHeight sets height of the Label in HIMETRIC (0.01mm)
func (_cdgg *LabelControl )SetHeight (height uint32 ){_cdgg ._agf ._decae =true ;_cdgg ._fea ._ffc =height ;};

// SetHeight sets height of the SpinButton in HIMETRIC (0.01mm)
func (_caef *SpinButtonControl )SetHeight (height uint32 ){_caef ._acfa ._eeeg =true ;_caef ._afdg ._bbcb =height ;};

// CommandButtonControl is a representation of a commandButton ActiveX form.
type CommandButtonControl struct{controlBase ;_baac *commandButtonPropMask ;_bef *commandButtonDataBlock ;_de *commandButtonExtraDataBlock ;_dd *streamData ;};

// ComboBoxDataControl is a representation of a combo box ActiveX form.
type ComboBoxDataControl struct{*morphDataControlStringValue };

// OptionButtonDataControl is a representation of an option button ActiveX form.
type OptionButtonDataControl struct{*morphDataControlBoolValue };

// GetWidth returns width of the CommandButton in HIMETRIC (0.01mm)
func (_age *CommandButtonControl )GetWidth ()uint32 {return _age ._de ._eaaa };func (_cdea *morphDataControl )readColumnInfoPropMask (_cee *_dg .Reader )error {return nil };type morphDataExtraDataBlock struct{_eff uint32 ;_gdcgd uint32 ;_ccad string ;_cdc string ;
_ggcd string ;};

// ControlChoice represents an ActiveX control inside a wrapper.
type ControlChoice struct{CheckBox *CheckBoxDataControl ;TextBox *TextBoxDataControl ;ListBox *ListBoxDataControl ;ComboBox *ComboBoxDataControl ;OptionButton *OptionButtonDataControl ;ToggleButton *ToggleButtonDataControl ;Label *LabelControl ;Image *ImageControl ;
SpinButton *SpinButtonControl ;CommandButton *CommandButtonControl ;ScrollBar *ScrollBarControl ;_b *controlBase ;};const (FmPictureSizeModeClip FmPictureSizeMode =iota ;FmPictureSizeModeStretch ;_ ;FmPictureSizeModeZoom ;);func (_bfbe *SpinButtonControl )writePropMask (_cead *_dg .Writer )error {_dagf :=uint32 (0);
_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._abeb );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._aadb );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._agaa );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._eeeg );_dagf >>=1;_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._dcg );
_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._gbe );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._cfag );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._egc );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._edgf );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._cced );
_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._aeaf );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._bde );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._eefa );_dagf =_dg .PushLeftUI32 (_dagf ,_bfbe ._acfa ._fdcb );_dagf >>=17;return _f .Write (_cead ,_f .LittleEndian ,_dagf );
};func (_dgg *morphDataControl )writeExtraDataBlock (_agbe *_dg .Writer )error {if _dgg ._dca ._bge {_bbba :=uint64 (_dgg ._gef ._eff )<<32|uint64 (_dgg ._gef ._gdcgd );if _feb :=_agbe .WritePropertyNoAlign (_bbba );_feb !=nil {return _feb ;};};if _dgg ._ebca ._afee > 0{if _deae :=_agbe .WriteStringProperty (_dgg ._gef ._ccad );
_deae !=nil {return _deae ;};};if _dgg ._ebca ._bcag > 0{if _efa :=_agbe .WriteStringProperty (_dgg ._gef ._cdc );_efa !=nil {return _efa ;};};if _dgg ._ebca ._aced > 0{if _befe :=_agbe .WriteStringProperty (_dgg ._gef ._ggcd );_befe !=nil {return _befe ;
};};return nil ;};func _bggg (_debg *_dg .Reader )(*morphDataControl ,error ){_bcff :=&morphDataControl {};if _bca :=_bcff .readPropMask (_debg );_bca !=nil {return nil ,_bca ;};if _gefc :=_bcff .readDataBlock (_debg );_gefc !=nil {return nil ,_gefc ;};
if _edf :=_bcff .readExtraDataBlock (_debg );_edf !=nil {return nil ,_edf ;};if _fbe :=_bcff .readStreamDataMP (_debg ,_bcff ._dca ._bdac ,_bcff ._dca ._cbcf );_fbe !=nil {return nil ,_fbe ;};switch _bcff ._ebca ._cacdd {case _cbdd ,_ebcc :if _aaa :=_bcff .readColumnInfo (_debg );
_aaa !=nil {return nil ,_aaa ;};if _ebgf :=_bcff .readColumnInfoPropMask (_debg );_ebgf !=nil {return nil ,_ebgf ;};if _cbgc :=_bcff .readColumnInfoDataBlock (_debg );_cbgc !=nil {return nil ,_cbgc ;};};if _dcac :=_bcff .readTheRest (_debg );_dcac !=nil {return nil ,_dcac ;
};return _bcff ,nil ;};func (_cda *ScrollBarControl )writePropMask (_acdd *_dg .Writer )error {_cbbc :=uint32 (0);_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._dfcac );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._ebgb );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._geba );
_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._bbbeg );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._cdef );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._afaf );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._febf );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._fgbg );
_cbbc >>=1;_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._fbec );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._ffcb );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._fba );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._ffcfd );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._geac );
_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._eba );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._fdc );_cbbc =_dg .PushLeftUI32 (_cbbc ,_cda ._ggcg ._dcace );_cbbc >>=15;return _f .Write (_acdd ,_f .LittleEndian ,_cbbc );};func _ca (_bgb *_dg .Reader )(*CommandButtonControl ,error ){_ea :=&CommandButtonControl {};
if _fgd :=_ea .readPropMask (_bgb );_fgd !=nil {return nil ,_fgd ;};if _da :=_ea .readDataBlock (_bgb );_da !=nil {return nil ,_da ;};if _agda :=_ea .readExtraDataBlock (_bgb );_agda !=nil {return nil ,_agda ;};if _bgbe :=_ea .readStreamDataPM (_bgb ,_ea ._baac ._fcc ,_ea ._baac ._bf );
_bgbe !=nil {return nil ,_bgbe ;};if _gbg :=_ea .readTheRest (_bgb );_gbg !=nil {return nil ,_gbg ;};return _ea ,nil ;};

// GetBackColor gets a button text color value for a system palette from a label control.
func (_cgd *LabelControl )GetBackColor ()uint32 {return _cgd ._cdfe ._afd };

// SetValue sets a value for a control which value can be represented as a string.
func (_dfdb *morphDataControlStringValue )SetValue (value string ){_dfdb .setValueString (value )};

// SetWidth sets width of the morphDataControl in HIMETRIC (0.01mm)
func (_ggfe *morphDataControl )SetWidth (width uint32 ){_ggfe ._dca ._bge =true ;_ggfe ._gef ._eff =width ;};

// ListBoxDataControl is a representation of a list box ActiveX form.
type ListBoxDataControl struct{*morphDataControlStringValue };

// SetCaption sets a caption string for a label control.
func (_deca *LabelControl )SetCaption (caption string ){_deca ._agf ._acd =true ;_deca ._cdfe ._eag =uint32 (len (caption ));_deca ._fea ._gdbf =caption ;};

// SetMax sets a button max value.
func (_bagf *ScrollBarControl )SetMax (max int32 ){_bagf ._ggcg ._febf =true ;_bagf ._cad ._cdecc =max };func (_bacf *controlBase )readStreamDataPM (_ddc *_dg .Reader ,_cdag ,_agfcg bool )error {_bacf ._fccd =&streamData {};if _cdag {_bacf ._fccd ._fffa =&guidAndPicture {};
if _dbcg :=_bacf ._fccd ._fffa .importFromReader (_ddc );_dbcg !=nil {return _dbcg ;};};if _agfcg {_bacf ._fccd ._bdaf =&guidAndPicture {};if _bgfa :=_bacf ._fccd ._bdaf .importFromReader (_ddc );_bgfa !=nil {return _bgfa ;};};return nil ;};

// GetCaption gets a caption string from a label control.
func (_caad *LabelControl )GetCaption ()string {return _caad ._fea ._gdbf };func (_edbg *guidAndPicture )setStdPictureBytes (_adf []byte ){if _adf ==nil {return ;};if _edbg ._cdf ==nil {_edbg ._cdf =_gdab ;};if _edbg ._gfbaa ==nil {_edbg ._gfbaa =&stdPicture {_bbfe :_bcg };
};_edbg ._gfbaa ._efef =uint32 (len (_adf ));_edbg ._gfbaa ._cfc =_gd .NewBuffer (_adf );};

// ImageControl is a representation of an image ActiveX form.
type ImageControl struct{controlBase ;_gcd *imagePropMask ;_ec *imageDataBlock ;_ggbg *imageExtraDataBlock ;_gfbe *streamData ;};const _daac =5;

// GetBackColor gets a button text color value for a system palette from a scrollBar control.
func (_edfb *ScrollBarControl )GetBackColor ()uint32 {return _edfb ._cad ._abdb };func (_fbb *guidAndPicture )importFromReader (_edb *_dg .Reader )error {_dbf :=_gd .NewBuffer ([]byte {});if _ ,_aba :=_af .CopyN (_dbf ,_edb ,int64 (_cea ));_aba !=nil {return _aba ;
};_gfd :=_dbf .Bytes ();for _fcg :=0;_fcg < _cea ;_fcg ++{if _gfd [_fcg ]!=_gdab [_fcg ]{return _a .Errorf ("\u0049\u006e\u0076\u0061\u006c\u0069d\u0020\u0047\u0055\u0049\u0044\u0020\u0076\u0061\u006c\u0075\u0065\u0020\u0025v\u0020\u0061\u0074\u0020\u0069\u006e\u0064e\u0078\u0020\u0025\u0076",_gfd [_fcg ],_fcg );
};};_fbb ._cdf =_gfd ;_fbb ._gfbaa =&stdPicture {};if _cfg :=_edb .ReadProperty (&_fbb ._gfbaa ._bbfe );_cfg !=nil {return _cfg ;};if _fbb ._gfbaa ._bbfe !=_bcg {return _a .Errorf ("\u0049\u006e\u0076\u0061li\u0064\u0020\u0070\u0072\u0065\u0061\u006d\u0062\u006c\u0065\u0020\u0025\u0076",_fbb ._gfbaa ._bbfe );
};if _ged :=_edb .ReadProperty (&_fbb ._gfbaa ._efef );_ged !=nil {return _ged ;};if _fbb ._gfbaa ._efef !=0{_acfb :=_gd .NewBuffer ([]byte {});if _ ,_gded :=_af .Copy (_acfb ,_edb );_gded !=nil {return _gded ;};_fbb ._gfbaa ._cfc =_acfb ;};return nil ;
};const _ggag =4;

// SetPosition sets a button position value.
func (_abcee *ScrollBarControl )SetPosition (position int32 ){_abcee ._ggcg ._fgbg =true ;_abcee ._cad ._fgba =position ;};

// GetMin gets a button min value.
func (_eef *ScrollBarControl )GetMin ()int32 {return _eef ._cad ._faca };type commandButtonDataBlock struct{_ebc uint32 ;_ddg uint32 ;_cf uint32 ;_gbb uint32 ;_cde bool ;_eab uint32 ;_ddb uint8 ;_cfd uint16 ;_adda rune ;_dad uint16 ;};func _aff (_dgb uint32 )(bool ,uint32 ){if _dgb ==0{return false ,0;
};_cce :=_dgb >=1<<31;if _cce {_dgb -=1<<31;};return _cce ,_dgb ;};func (_cfaa *morphDataControl )readPropMask (_gae *_dg .Reader )error {var _caee uint64 ;if _bbbb :=_f .Read (_gae ,_f .LittleEndian ,&_caee );_bbbb !=nil {return _bbbb ;};_cfaa ._dca =&morphDataPropMask {};
_cfaa ._dca ._aaaa ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._bfg ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._aca ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._gaf ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._gegc ,_caee =_dg .PopRightUI64 (_caee );
_cfaa ._dca ._bad ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._abecc ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._gcad ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._bge ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._ggagd ,_caee =_dg .PopRightUI64 (_caee );
_cfaa ._dca ._cfce ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._egd ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._bcac ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._fead ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._bggdd ,_caee =_dg .PopRightUI64 (_caee );
_cfaa ._dca ._eagf ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._bgba ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._bae ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._bcab ,_caee =_dg .PopRightUI64 (_caee );_caee >>=1;_cfaa ._dca ._ffea ,_caee =_dg .PopRightUI64 (_caee );
_cfaa ._dca ._gea ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._gccbe ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._ace ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._ebe ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._gafa ,_caee =_dg .PopRightUI64 (_caee );
_cfaa ._dca ._dafc ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._bdac ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._cbcf ,_caee =_dg .PopRightUI64 (_caee );_cfaa ._dca ._eac ,_caee =_dg .PopRightUI64 (_caee );_caee >>=1;_caee >>=1;_cfaa ._dca ._dccd ,_caee =_dg .PopRightUI64 (_caee );
return nil ;};

// GetForeColor gets a button text color value for a system palette from a spinButton control.
func (_cbbca *SpinButtonControl )GetForeColor ()uint32 {return _cbbca ._cdeab ._geaf };func (_gdgd *ImageControl )export (_daa *_dg .Writer )error {if _gcfa :=_gdgd .writePropMask (_daa );_gcfa !=nil {return _gcfa ;};if _agee :=_gdgd .writeDataBlock (_daa );
_agee !=nil {return _agee ;};if _eaba :=_gdgd .writeExtraDataBlock (_daa );_eaba !=nil {return _eaba ;};_gdgd ._dag =uint16 (_daa .Len ()-4);if _egb :=_gdgd .writeStreamDataPM (_daa );_egb !=nil {return _egb ;};return _gdgd .writeTheRest (_daa );};

// SetWidth sets width of the CommandButton in HIMETRIC (0.01mm)
func (_bed *CommandButtonControl )SetWidth (width uint32 ){_bed ._baac ._eaa =true ;_bed ._de ._eaaa =width ;};type spinButtonExtraDataBlock struct{_acdg uint32 ;_bbcb uint32 ;};func (_cedc *LabelControl )writePropMask (_bgga *_dg .Writer )error {_deab :=uint32 (0);
_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._fffd );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._fec );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._bec );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._acd );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._fbfd );
_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._decae );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._dbe );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._cbbe );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._aedbc );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._dea );
_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._fdbe );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._ecb );_deab =_dg .PushLeftUI32 (_deab ,_cedc ._agf ._fadg );_deab >>=19;return _f .Write (_bgga ,_f .LittleEndian ,_deab );};

// GetMin gets a button min value.
func (_cfab *SpinButtonControl )GetMin ()int32 {return _cfab ._cdeab ._afcbc };

// CheckBoxDataControl is a representation of a check box ActiveX form.
type CheckBoxDataControl struct{*morphDataControlBoolValue };

// SetMin sets a button min value.
func (_dafcb *ScrollBarControl )SetMin (min int32 ){_dafcb ._ggcg ._afaf =true ;_dafcb ._cad ._faca =min };

// GetForeColor gets a button text color value for a system palette from a label control.
func (_gddc *LabelControl )GetForeColor ()uint32 {return _gddc ._cdfe ._fef };func (_afcb *ImageControl )readPropMask (_ced *_dg .Reader )error {var _efg uint32 ;if _deed :=_f .Read (_ced ,_f .LittleEndian ,&_efg );_deed !=nil {return _deed ;};_afcb ._gcd =&imagePropMask {};
_efg >>=2;_afcb ._gcd ._beg ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._eafd ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._gfa ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._gaa ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._bea ,_efg =_dg .PopRightUI32 (_efg );
_afcb ._gcd ._dade ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._bgfc ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._acb ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._fff ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._dbba ,_efg =_dg .PopRightUI32 (_efg );
_afcb ._gcd ._gdbg ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._eae ,_efg =_dg .PopRightUI32 (_efg );_afcb ._gcd ._faf ,_efg =_dg .PopRightUI32 (_efg );return nil ;};func (_efeb *LabelControl )readPropMask (_baf *_dg .Reader )error {var _bcgb uint32 ;
if _eaaaa :=_f .Read (_baf ,_f .LittleEndian ,&_bcgb );_eaaaa !=nil {return _eaaaa ;};_efeb ._agf =&labelPropMask {};_efeb ._agf ._fffd ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._fec ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._bec ,_bcgb =_dg .PopRightUI32 (_bcgb );
_efeb ._agf ._acd ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._fbfd ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._decae ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._dbe ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._cbbe ,_bcgb =_dg .PopRightUI32 (_bcgb );
_efeb ._agf ._aedbc ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._dea ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._fdbe ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._ecb ,_bcgb =_dg .PopRightUI32 (_bcgb );_efeb ._agf ._fadg ,_bcgb =_dg .PopRightUI32 (_bcgb );
return nil ;};

// GetWidth returns width of the SpinButton in HIMETRIC (0.01mm)
func (_aabe *SpinButtonControl )GetWidth ()uint32 {return _aabe ._afdg ._acdg };type labelDataBlock struct{_fef uint32 ;_afd uint32 ;_deb uint32 ;_eag uint32 ;_dace bool ;_dbef uint32 ;_cdd uint8 ;_gdcb uint32 ;_geb uint16 ;_dedc uint16 ;_eaac uint16 ;
_fda rune ;_faad uint16 ;};func (_fac *ImageControl )readExtraDataBlock (_ada *_dg .Reader )error {_fac ._ggbg =&imageExtraDataBlock {};if _fac ._gcd ._acb {var _fdg uint64 ;if _fcd :=_ada .ReadPairProperty (&_fdg );_fcd !=nil {return _fcd ;};_fac ._ggbg ._bdd =uint32 (_fdg );
_fac ._ggbg ._ddgc =uint32 (_fdg >>32);};return nil ;};

// GetBackColor gets a button text color value for a system palette from a commandButton control.
func (_aea *CommandButtonControl )GetBackColor ()uint32 {return _aea ._bef ._ddg };type imageExtraDataBlock struct{_ddgc uint32 ;_bdd uint32 ;};

// SetPosition sets a button position value.
func (_adbb *SpinButtonControl )SetPosition (position int32 ){_adbb ._acfa ._cfag =true ;_adbb ._cdeab ._cdgd =position ;};func (_efd *ImageControl )writeExtraDataBlock (_fdec *_dg .Writer )error {if _efd ._gcd ._acb {_abce :=uint64 (_efd ._ggbg ._ddgc )<<32|uint64 (_efd ._ggbg ._bdd );
if _dbg :=_fdec .WritePropertyNoAlign (_abce );_dbg !=nil {return _dbg ;};};return nil ;};

// GetHeight returns height of the morphDataControl in HIMETRIC (0.01mm)
func (_ggef *morphDataControl )GetHeight ()uint32 {return _ggef ._gef ._gdcgd };func (_dfa *morphDataControl )readExtraDataBlock (_abdf *_dg .Reader )error {_dfa ._gef =&morphDataExtraDataBlock {};if _dfa ._dca ._bge {var _aaf uint64 ;if _eaabd :=_abdf .ReadPairProperty (&_aaf );
_eaabd !=nil {return _eaabd ;};_dfa ._gef ._gdcgd =uint32 (_aaf );_dfa ._gef ._eff =uint32 (_aaf >>32);};if _dfa ._ebca ._afee > 0{_abga ,_gegb :=_abdf .ReadStringProperty (_dfa ._ebca ._afee );if _gegb !=nil {return _gegb ;};_dfa ._gef ._ccad =_abga ;
};if _dfa ._ebca ._bcag > 0{_bbaa ,_eabe :=_abdf .ReadStringProperty (_dfa ._ebca ._bcag );if _eabe !=nil {return _eabe ;};_dfa ._gef ._cdc =_bbaa ;};if _dfa ._ebca ._aced > 0{_aebf ,_fbfe :=_abdf .ReadStringProperty (_dfa ._ebca ._aced );if _fbfe !=nil {return _fbfe ;
};_dfa ._gef ._ggcd =_aebf ;};return nil ;};func (_efae *morphDataControl )writeColumnInfoDataBlock (_fccdf *_dg .Writer )error {return nil };

// FmPictureSizeMode represents one of the three picture size modes according to MS-OFORMS document.
type FmPictureSizeMode byte ;func (_dbc *CommandButtonControl )export (_dgcc *_dg .Writer )error {if _acg :=_dbc .writePropMask (_dgcc );_acg !=nil {return _acg ;};if _bc :=_dbc .writeDataBlock (_dgcc );_bc !=nil {return _bc ;};if _cbc :=_dbc .writeExtraDataBlock (_dgcc );
_cbc !=nil {return _cbc ;};_dbc ._dag =uint16 (_dgcc .Len ()-4);if _cga :=_dbc .writeStreamDataPM (_dgcc );_cga !=nil {return _cga ;};return _dbc .writeTheRest (_dgcc );};

// GetForeColor gets a button text color value for a system palette from a scrollBar control.
func (_affeg *ScrollBarControl )GetForeColor ()uint32 {return _affeg ._cad ._edgb };

// SetWidth sets width of the SpinButton in HIMETRIC (0.01mm)
func (_dadf *SpinButtonControl )SetWidth (width uint32 ){_dadf ._acfa ._eeeg =true ;_dadf ._afdg ._acdg =width ;};

// SetBackColor sets a button text color value from a system palette for a label control.
func (_eade *LabelControl )SetBackColor (backColor uint32 ){_eade ._agf ._fec =true ;_eade ._cdfe ._afd =backColor ;};type morphDataControlBoolValue struct{*morphDataControl };type scrollBarPropMask struct{_dfcac bool ;_ebgb bool ;_geba bool ;_cdef bool ;
_bbbeg bool ;_afaf bool ;_febf bool ;_fgbg bool ;_fbec bool ;_ffcb bool ;_fba bool ;_ffcfd bool ;_geac bool ;_eba bool ;_fdc bool ;_dcace bool ;};type imageDataBlock struct{_agdf uint32 ;_dbcb uint32 ;_fae byte ;_aedb uint8 ;_gcge byte ;_efee byte ;_cbd uint16 ;
_aeg byte ;_gbd uint32 ;_aadg uint16 ;};type morphDataControl struct{controlBase ;_dca *morphDataPropMask ;_ebca *morphDataDataBlock ;_gef *morphDataExtraDataBlock ;_dgcg *streamData ;_gdaa *morphDataColumnInfo ;_bddf *morphDataColumnInfoPropMask ;_dbaf *morphDataColumnInfoDataBlock ;
};type streamData struct{_bdaf *guidAndPicture ;_fffa *guidAndPicture ;};func (_ggf *CommandButtonControl )readDataBlock (_abc *_dg .Reader )error {_ggf ._bef =&commandButtonDataBlock {};if _ggf ._baac ._ef {if _cac :=_abc .ReadProperty (&_ggf ._bef ._ebc );
_cac !=nil {return _cac ;};};if _ggf ._baac ._agb {if _gdgf :=_abc .ReadProperty (&_ggf ._bef ._ddg );_gdgf !=nil {return _gdgf ;};};if _ggf ._baac ._bee {if _cab :=_abc .ReadProperty (&_ggf ._bef ._cf );_cab !=nil {return _cab ;};};if _ggf ._baac ._gga {var _fd uint32 ;
if _bb :=_abc .ReadProperty (&_fd );_bb !=nil {return _bb ;};_ggf ._bef ._cde ,_ggf ._bef ._gbb =_aff (_fd );};if _ggf ._baac ._efe {if _fde :=_abc .ReadProperty (&_ggf ._bef ._eab );_fde !=nil {return _fde ;};};if _ggf ._baac ._cefe {if _agg :=_abc .ReadProperty (&_ggf ._bef ._ddb );
_agg !=nil {return _agg ;};};if _ggf ._baac ._fcc {if _abfa :=_abc .ReadProperty (&_ggf ._bef ._cfd );_abfa !=nil {return _abfa ;};};if _ggf ._baac ._gdb {if _bbb :=_abc .ReadProperty (&_ggf ._bef ._adda );_bbb !=nil {return _bbb ;};};if _ggf ._baac ._bf {if _gbce :=_abc .ReadProperty (&_ggf ._bef ._dad );
_gbce !=nil {return _gbce ;};};return nil ;};type scrollBarDataBlock struct{_edgb uint32 ;_abdb uint32 ;_cdbe uint32 ;_bcge uint8 ;_faca int32 ;_cdecc int32 ;_fgba int32 ;_dfega int32 ;_bebf int32 ;_agcg int32 ;_gccf int32 ;_eaec uint32 ;_aged uint32 ;
_efaa uint32 ;_aec uint16 ;};func (_ebg *morphDataControl )setValueBool (_gddd bool ){_ebg ._dca ._gccbe =true ;_ebg ._ebca ._afee =1;_ebg ._ebca ._bbc =true ;_ageg :="\u0030";if _gddd {_ageg ="\u0031";};_ebg ._gef ._ccad =_ageg ;};type spinButtonPropMask struct{_abeb bool ;
_aadb bool ;_agaa bool ;_eeeg bool ;_dcg bool ;_gbe bool ;_cfag bool ;_egc bool ;_edgf bool ;_cced bool ;_aeaf bool ;_bde bool ;_eefa bool ;_fdcb bool ;};

// GetMax gets a button max value.
func (_cdebe *ScrollBarControl )GetMax ()int32 {return _cdebe ._cad ._cdecc };func (_eda *controlBase )setPictureBytes (_fgb []byte ){if _eda ._fccd ._fffa ==nil {_eda ._fccd ._fffa =&guidAndPicture {};};_eda ._fccd ._fffa .setStdPictureBytes (_fgb );};
func (_begb *LabelControl )writeDataBlock (_afa *_dg .Writer )error {if _begb ._agf ._fffd {if _daf :=_afa .WriteProperty (_begb ._cdfe ._fef );_daf !=nil {return _daf ;};};if _begb ._agf ._fec {if _bebe :=_afa .WriteProperty (_begb ._cdfe ._afd );_bebe !=nil {return _bebe ;
};};if _begb ._agf ._bec {if _beag :=_afa .WriteProperty (_begb ._cdfe ._deb );_beag !=nil {return _beag ;};};if _begb ._agf ._acd {_adgc :=_cd (_begb ._cdfe ._eag ,_begb ._cdfe ._dace );if _dfd :=_afa .WriteProperty (_adgc );_dfd !=nil {return _dfd ;};
};if _begb ._agf ._fbfd {if _fbg :=_afa .WriteProperty (_begb ._cdfe ._dbef );_fbg !=nil {return _fbg ;};};if _begb ._agf ._dbe {if _gdgdb :=_afa .WriteProperty (_begb ._cdfe ._cdd );_gdgdb !=nil {return _gdgdb ;};};if _begb ._agf ._cbbe {if _geg :=_afa .WriteProperty (_begb ._cdfe ._gdcb );
_geg !=nil {return _geg ;};};if _begb ._agf ._aedbc {if _cefb :=_afa .WriteProperty (_begb ._cdfe ._geb );_cefb !=nil {return _cefb ;};};if _begb ._agf ._dea {if _bcf :=_afa .WriteProperty (_begb ._cdfe ._dedc );_bcf !=nil {return _bcf ;};};if _begb ._agf ._fdbe {if _bebb :=_afa .WriteProperty (_begb ._cdfe ._eaac );
_bebb !=nil {return _bebb ;};};if _begb ._agf ._ecb {if _ggbe :=_afa .WriteProperty (_begb ._cdfe ._fda );_ggbe !=nil {return _ggbe ;};};if _begb ._agf ._fadg {if _cggd :=_afa .WriteProperty (_begb ._cdfe ._faad );_cggd !=nil {return _cggd ;};};return _afa .AlignLength (4);
};type scrollBarExtraDataBlock struct{_cbgcb uint32 ;_bggc uint32 ;};type controlBase struct{_dag uint16 ;_fdb bool ;_fccd *streamData ;_abff []byte ;};

// SetForeColor sets a button text color value from a system palette for a spinButton control.
func (_abfb *SpinButtonControl )SetForeColor (foreColor uint32 ){_abfb ._acfa ._abeb =true ;_abfb ._cdeab ._geaf =foreColor ;};type labelExtraDataBlock struct{_cae uint32 ;_ffc uint32 ;_gdbf string ;};var _gdab =[]byte {0x04,0x52,0xE3,0x0B,0x91,0x8F,0xCE,0x11,0x9D,0xE3,0,0xAA,0,0x4B,0xB8,0x51};
func (_affe *morphDataControl )writeColumnInfoPropMask (_aggde *_dg .Writer )error {return nil };func (_bcfa *SpinButtonControl )readDataBlock (_cgbc *_dg .Reader )error {_bcfa ._cdeab =&spinButtonDataBlock {};if _bcfa ._acfa ._abeb {if _bfe :=_cgbc .ReadProperty (&_bcfa ._cdeab ._geaf );
_bfe !=nil {return _bfe ;};};if _bcfa ._acfa ._aadb {if _adag :=_cgbc .ReadProperty (&_bcfa ._cdeab ._bdf );_adag !=nil {return _adag ;};};if _bcfa ._acfa ._agaa {if _agbacf :=_cgbc .ReadProperty (&_bcfa ._cdeab ._ggcc );_agbacf !=nil {return _agbacf ;
};};if _bcfa ._acfa ._dcg {if _fcaa :=_cgbc .ReadProperty (&_bcfa ._cdeab ._afcbc );_fcaa !=nil {return _fcaa ;};};if _bcfa ._acfa ._gbe {if _gbgd :=_cgbc .ReadProperty (&_bcfa ._cdeab ._gbf );_gbgd !=nil {return _gbgd ;};};if _bcfa ._acfa ._cfag {if _dbeg :=_cgbc .ReadProperty (&_bcfa ._cdeab ._cdgd );
_dbeg !=nil {return _dbeg ;};};if _bcfa ._acfa ._egc {if _gcdg :=_cgbc .ReadProperty (&_bcfa ._cdeab ._bggdb );_gcdg !=nil {return _gcdg ;};};if _bcfa ._acfa ._edgf {if _gcbe :=_cgbc .ReadProperty (&_bcfa ._cdeab ._dfcf );_gcbe !=nil {return _gcbe ;};};
if _bcfa ._acfa ._cced {if _fbabg :=_cgbc .ReadProperty (&_bcfa ._cdeab ._ccfd );_fbabg !=nil {return _fbabg ;};};if _bcfa ._acfa ._aeaf {if _dff :=_cgbc .ReadProperty (&_bcfa ._cdeab ._eeec );_dff !=nil {return _dff ;};};if _bcfa ._acfa ._bde {if _eaff :=_cgbc .ReadProperty (&_bcfa ._cdeab ._bbda );
_eaff !=nil {return _eaff ;};};if _bcfa ._acfa ._eefa {if _dccc :=_cgbc .ReadProperty (&_bcfa ._cdeab ._dfbd );_dccc !=nil {return _dccc ;};};if _bcfa ._acfa ._fdcb {if _fadf :=_cgbc .ReadProperty (&_bcfa ._cdeab ._bcfc );_fadf !=nil {return _fadf ;};};
return nil ;};func (_gff *morphDataControl )getValueBool ()bool {return _gff ._dca ._gccbe &&_gff ._gef ._ccad =="\u0031";};func (_fbc *LabelControl )readDataBlock (_dgfe *_dg .Reader )error {_fbc ._cdfe =&labelDataBlock {};if _fbc ._agf ._fffd {if _bda :=_dgfe .ReadProperty (&_fbc ._cdfe ._fef );
_bda !=nil {return _bda ;};};if _fbc ._agf ._fec {if _egg :=_dgfe .ReadProperty (&_fbc ._cdfe ._afd );_egg !=nil {return _egg ;};};if _fbc ._agf ._bec {if _aeac :=_dgfe .ReadProperty (&_fbc ._cdfe ._deb );_aeac !=nil {return _aeac ;};};if _fbc ._agf ._acd {var _cdb uint32 ;
if _egee :=_dgfe .ReadProperty (&_cdb );_egee !=nil {return _egee ;};_fbc ._cdfe ._dace ,_fbc ._cdfe ._eag =_aff (_cdb );};if _fbc ._agf ._fbfd {if _eeg :=_dgfe .ReadProperty (&_fbc ._cdfe ._dbef );_eeg !=nil {return _eeg ;};};if _fbc ._agf ._dbe {if _eafg :=_dgfe .ReadProperty (&_fbc ._cdfe ._cdd );
_eafg !=nil {return _eafg ;};};if _fbc ._agf ._cbbe {if _cbca :=_dgfe .ReadProperty (&_fbc ._cdfe ._gdcb );_cbca !=nil {return _cbca ;};};if _fbc ._agf ._aedbc {if _gfbf :=_dgfe .ReadProperty (&_fbc ._cdfe ._geb );_gfbf !=nil {return _gfbf ;};};if _fbc ._agf ._dea {if _agge :=_dgfe .ReadProperty (&_fbc ._cdfe ._dedc );
_agge !=nil {return _agge ;};};if _fbc ._agf ._fdbe {if _bdde :=_dgfe .ReadProperty (&_fbc ._cdfe ._eaac );_bdde !=nil {return _bdde ;};};if _fbc ._agf ._ecb {if _afec :=_dgfe .ReadProperty (&_fbc ._cdfe ._fda );_afec !=nil {return _afec ;};};if _fbc ._agf ._fadg {if _gdgdf :=_dgfe .ReadProperty (&_fbc ._cdfe ._faad );
_gdgdf !=nil {return _gdgdf ;};};return nil ;};const _ebcc =3;type morphDataDataBlock struct{_dde uint32 ;_cdbb uint32 ;_fcdd uint32 ;_fafg uint32 ;_gag byte ;_cgac byte ;_cacdd byte ;_bgggc byte ;_feea rune ;_agc uint32 ;_gffa uint16 ;_bgd int16 ;_dgdf int16 ;
_dbd uint16 ;_gdcg uint16 ;_ega uint8 ;_acec uint8 ;_dgda uint8 ;_gbag uint8 ;_beaad uint8 ;_afee uint32 ;_bbc bool ;_bcag uint32 ;_bgc bool ;_debd uint32 ;_ddd uint32 ;_dbdf uint32 ;_gfe uint16 ;_caea uint16 ;_dfdc rune ;_aced uint32 ;_ffcf bool ;};

// SetValue sets a value for a control which value can be represented as boolean (on/off).
func (_babe *morphDataControlBoolValue )SetValue (value bool ){_babe .setValueBool (value )};func _bggb (_aggd *_dg .Reader )(*LabelControl ,error ){_eaaab :=&LabelControl {};if _dcdfg :=_eaaab .readPropMask (_aggd );_dcdfg !=nil {return nil ,_dcdfg ;};
if _acgd :=_eaaab .readDataBlock (_aggd );_acgd !=nil {return nil ,_acgd ;};if _cbae :=_eaaab .readExtraDataBlock (_aggd );_cbae !=nil {return nil ,_cbae ;};if _bdc :=_eaaab .readStreamDataPM (_aggd ,_eaaab ._agf ._fdbe ,_eaaab ._agf ._fadg );_bdc !=nil {return nil ,_bdc ;
};if _fffb :=_eaaab .readTheRest (_aggd );_fffb !=nil {return nil ,_fffb ;};return _eaaab ,nil ;};func (_dbefd *SpinButtonControl )export (_bbbaa *_dg .Writer )error {if _gfg :=_dbefd .writePropMask (_bbbaa );_gfg !=nil {return _gfg ;};if _gaac :=_dbefd .writeDataBlock (_bbbaa );
_gaac !=nil {return _gaac ;};if _fdd :=_dbefd .writeExtraDataBlock (_bbbaa );_fdd !=nil {return _fdd ;};_dbefd ._dag =uint16 (_bbbaa .Len ()-4);if _cfdab :=_dbefd .writeStreamDataM (_bbbaa );_cfdab !=nil {return _cfdab ;};return _dbefd .writeTheRest (_bbbaa );
};

// SpinButtonControl is a representation of a spinButton ActiveX form.
type SpinButtonControl struct{controlBase ;_acfa *spinButtonPropMask ;_cdeab *spinButtonDataBlock ;_afdg *spinButtonExtraDataBlock ;_gdgdbd *streamData ;};func (_edbgd *controlBase )writeStreamDataM (_fag *_dg .Writer )error {if _edbgd ._fccd !=nil {if _edbgd ._fccd ._bdaf !=nil {if _ggd :=_edbgd ._fccd ._bdaf .export (_fag );
_ggd !=nil {return _ggd ;};};};return nil ;};func (_gdabd *SpinButtonControl )readExtraDataBlock (_gcfdc *_dg .Reader )error {_gdabd ._afdg =&spinButtonExtraDataBlock {};if _gdabd ._acfa ._eeeg {var _gfge uint64 ;if _fgca :=_gcfdc .ReadPairProperty (&_gfge );
_fgca !=nil {return _fgca ;};_gdabd ._afdg ._bbcb =uint32 (_gfge );_gdabd ._afdg ._acdg =uint32 (_gfge >>32);};return nil ;};func (_dec *CommandButtonControl )writeExtraDataBlock (_gda *_dg .Writer )error {if _dec ._bef ._gbb > 0{if _fb :=_gda .WriteStringProperty (_dec ._de ._dgd );
_fb !=nil {return _fb ;};};if _dec ._baac ._eaa {_fee :=uint64 (_dec ._de ._eaaa )<<32|uint64 (_dec ._de ._cacd );if _eabd :=_gda .WritePropertyNoAlign (_fee );_eabd !=nil {return _eabd ;};};return nil ;};func (_agce *controlBase )readStreamDataM (_ggca *_dg .Reader ,_fefa bool )error {_agce ._fccd =&streamData {};
if _fefa {_agce ._fccd ._bdaf =&guidAndPicture {};if _fefb :=_agce ._fccd ._bdaf .importFromReader (_ggca );_fefb !=nil {return _fefb ;};};return nil ;};func (_fdf *ScrollBarControl )readDataBlock (_ceca *_dg .Reader )error {_fdf ._cad =&scrollBarDataBlock {};
if _fdf ._ggcg ._dfcac {if _ggga :=_ceca .ReadProperty (&_fdf ._cad ._edgb );_ggga !=nil {return _ggga ;};};if _fdf ._ggcg ._ebgb {if _abceb :=_ceca .ReadProperty (&_fdf ._cad ._abdb );_abceb !=nil {return _abceb ;};};if _fdf ._ggcg ._geba {if _cfgf :=_ceca .ReadProperty (&_fdf ._cad ._cdbe );
_cfgf !=nil {return _cfgf ;};};if _fdf ._ggcg ._cdef {if _geda :=_ceca .ReadProperty (&_fdf ._cad ._bcge );_geda !=nil {return _geda ;};};if _fdf ._ggcg ._afaf {if _cff :=_ceca .ReadProperty (&_fdf ._cad ._faca );_cff !=nil {return _cff ;};};if _fdf ._ggcg ._febf {if _accb :=_ceca .ReadProperty (&_fdf ._cad ._cdecc );
_accb !=nil {return _accb ;};};if _fdf ._ggcg ._fgbg {if _fbfc :=_ceca .ReadProperty (&_fdf ._cad ._fgba );_fbfc !=nil {return _fbfc ;};};if _fdf ._ggcg ._fbec {if _edaf :=_ceca .ReadProperty (&_fdf ._cad ._dfega );_edaf !=nil {return _edaf ;};};if _fdf ._ggcg ._ffcb {if _cgf :=_ceca .ReadProperty (&_fdf ._cad ._bebf );
_cgf !=nil {return _cgf ;};};if _fdf ._ggcg ._fba {if _dacef :=_ceca .ReadProperty (&_fdf ._cad ._agcg );_dacef !=nil {return _dacef ;};};if _fdf ._ggcg ._ffcfd {if _egac :=_ceca .ReadProperty (&_fdf ._cad ._gccf );_egac !=nil {return _egac ;};};if _fdf ._ggcg ._geac {if _bcga :=_ceca .ReadProperty (&_fdf ._cad ._eaec );
_bcga !=nil {return _bcga ;};};if _fdf ._ggcg ._eba {if _dbae :=_ceca .ReadProperty (&_fdf ._cad ._aged );_dbae !=nil {return _dbae ;};};if _fdf ._ggcg ._fdc {if _bcgeg :=_ceca .ReadProperty (&_fdf ._cad ._efaa );_bcgeg !=nil {return _bcgeg ;};};if _fdf ._ggcg ._dcace {if _eaad :=_ceca .ReadProperty (&_fdf ._cad ._aec );
_eaad !=nil {return _eaad ;};};return nil ;};type morphDataPropMask struct{_aaaa bool ;_bfg bool ;_aca bool ;_gaf bool ;_gegc bool ;_bad bool ;_abecc bool ;_gcad bool ;_bge bool ;_ggagd bool ;_cfce bool ;_egd bool ;_bcac bool ;_fead bool ;_bggdd bool ;
_eagf bool ;_bgba bool ;_bae bool ;_bcab bool ;_ffea bool ;_gea bool ;_gccbe bool ;_ace bool ;_ebe bool ;_gafa bool ;_dafc bool ;_bdac bool ;_cbcf bool ;_eac bool ;_dccd bool ;};func (_cba *CommandButtonControl )readPropMask (_aada *_dg .Reader )error {var _bfb uint32 ;
if _eb :=_f .Read (_aada ,_f .LittleEndian ,&_bfb );_eb !=nil {return _eb ;};_cba ._baac =&commandButtonPropMask {};_cba ._baac ._ef ,_bfb =_dg .PopRightUI32 (_bfb );_cba ._baac ._agb ,_bfb =_dg .PopRightUI32 (_bfb );_cba ._baac ._bee ,_bfb =_dg .PopRightUI32 (_bfb );
_cba ._baac ._gga ,_bfb =_dg .PopRightUI32 (_bfb );_cba ._baac ._efe ,_bfb =_dg .PopRightUI32 (_bfb );_cba ._baac ._eaa ,_bfb =_dg .PopRightUI32 (_bfb );_cba ._baac ._cefe ,_bfb =_dg .PopRightUI32 (_bfb );_cba ._baac ._fcc ,_bfb =_dg .PopRightUI32 (_bfb );
_cba ._baac ._gdb ,_bfb =_dg .PopRightUI32 (_bfb );_cba ._baac ._add ,_bfb =_dg .PopRightUI32 (_bfb );_cba ._baac ._bf ,_bfb =_dg .PopRightUI32 (_bfb );return nil ;};func (_ceac *SpinButtonControl )writeExtraDataBlock (_efaaf *_dg .Writer )error {if _ceac ._acfa ._eeeg {_effe :=uint64 (_ceac ._afdg ._acdg )<<32|uint64 (_ceac ._afdg ._bbcb );
if _ebd :=_efaaf .WritePropertyNoAlign (_effe );_ebd !=nil {return _ebd ;};};return nil ;};

// SetWidth sets width of the ScrollBar in HIMETRIC (0.01mm)
func (_cggb *ScrollBarControl )SetWidth (width uint32 ){_cggb ._ggcg ._bbbeg =true ;_cggb ._efb ._cbgcb =width ;};func _agfc (_dae *_dg .Reader )(*ScrollBarControl ,error ){_fggd :=&ScrollBarControl {};if _cdga :=_fggd .readPropMask (_dae );_cdga !=nil {return nil ,_cdga ;
};if _gefa :=_fggd .readDataBlock (_dae );_gefa !=nil {return nil ,_gefa ;};if _dfbe :=_fggd .readExtraDataBlock (_dae );_dfbe !=nil {return nil ,_dfbe ;};if _abfg :=_fggd .readStreamDataM (_dae ,_fggd ._ggcg ._dcace );_abfg !=nil {return nil ,_abfg ;};
if _efad :=_fggd .readTheRest (_dae );_efad !=nil {return nil ,_efad ;};return _fggd ,nil ;};type morphDataColumnInfoPropMask struct{};type morphDataColumnInfo struct{};func (_ffeag *controlBase )readStreamDataMP (_cdca *_dg .Reader ,_dfbb ,_edbd bool )error {_ffeag ._fccd =&streamData {};
if _dfbb {_ffeag ._fccd ._bdaf =&guidAndPicture {};if _cedf :=_ffeag ._fccd ._bdaf .importFromReader (_cdca );_cedf !=nil {return _cedf ;};};if _edbd {_ffeag ._fccd ._fffa =&guidAndPicture {};if _gdad :=_ffeag ._fccd ._fffa .importFromReader (_cdca );_gdad !=nil {return _gdad ;
};};return nil ;};func (_bbcc *morphDataControl )writeColumnInfo (_eaed *_dg .Writer )error {return nil };type commandButtonExtraDataBlock struct{_eaaa uint32 ;_cacd uint32 ;_dgd string ;};

// GetValue gets a value from a control which value can be represented as a string.
func (_abec *morphDataControlStringValue )GetValue ()string {return _abec .getValueString ()};

// ExportToByteArray makes a byte array from a control as it is stored in .bin files.
func (_cg *Control )ExportToByteArray ()([]byte ,error ){_afe ,_gde :=_c .Open (_cg ._gf );if _gde !=nil {return nil ,_gde ;};defer _afe .Close ();_bd ,_gde :=_ab .New (_afe );if _gde !=nil {return nil ,_gde ;};_abf :=_dg .NewWriter ();if _cc :=_f .Write (_abf ,_f .LittleEndian ,&_cg ._dc );
_cc !=nil {return nil ,_cc ;};if _aad :=_f .Write (_abf ,_f .LittleEndian ,&_cg ._cb );_aad !=nil {return nil ,_aad ;};if _ggb :=_f .Write (_abf ,_f .LittleEndian ,uint16 (0));_ggb !=nil {return nil ,_ggb ;};var _bgg error ;if _cgc :=_cg .Choice ;_cgc !=nil {if _cgc .CheckBox !=nil {_bgg =_cgc .CheckBox .export (_abf );
}else if _cgc .TextBox !=nil {_bgg =_cgc .TextBox .export (_abf );}else if _cgc .ComboBox !=nil {_bgg =_cgc .ComboBox .export (_abf );}else if _cgc .ListBox !=nil {_bgg =_cgc .ListBox .export (_abf );}else if _cgc .OptionButton !=nil {_bgg =_cgc .OptionButton .export (_abf );
}else if _cgc .ToggleButton !=nil {_bgg =_cgc .ToggleButton .export (_abf );}else if _cgc .Label !=nil {_bgg =_cgc .Label .export (_abf );}else if _cgc .SpinButton !=nil {_bgg =_cgc .SpinButton .export (_abf );}else if _cgc .CommandButton !=nil {_bgg =_cgc .CommandButton .export (_abf );
}else if _cgc .ScrollBar !=nil {_bgg =_cgc .ScrollBar .export (_abf );}else {_bgg =_cgc ._b .writeTheRest (_abf );};};if _bgg !=nil {return nil ,_bgg ;};if _gcg :=_abf .WriteByteAt (byte (_cg ._dgf ),2);_gcg !=nil {return nil ,_gcg ;};if _fgg :=_abf .WriteByteAt (byte (_cg ._dgf >>8),3);
_fgg !=nil {return nil ,_fgg ;};_ce ,_gde :=_bd .GetEntry ("\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0073");if _gde !=nil {return nil ,_gde ;};if _baa :=_ce .SetEntryContent (_abf .Bytes ());_baa !=nil {return nil ,_baa ;};return _bd .Export ();};

// GetMax gets a button max value.
func (_gdeda *SpinButtonControl )GetMax ()int32 {return _gdeda ._cdeab ._gbf };

// LabelControl is a representation of a label ActiveX form.
type LabelControl struct{controlBase ;_agf *labelPropMask ;_cdfe *labelDataBlock ;_fea *labelExtraDataBlock ;_gdf *streamData ;};

// GetHeight returns height of the Label in HIMETRIC (0.01mm)
func (_gba *LabelControl )GetHeight ()uint32 {return _gba ._fea ._ffc };

// ToggleButtonDataControl is a representation of a toggle button ActiveX form.
type ToggleButtonDataControl struct{*morphDataControlBoolValue };func (_gegd *controlBase )writeStreamDataMP (_agca *_dg .Writer )error {if _gegd ._fccd !=nil {if _gegd ._fccd ._bdaf !=nil {if _faaa :=_gegd ._fccd ._bdaf .export (_agca );_faaa !=nil {return _faaa ;
};};if _gegd ._fccd ._fffa !=nil {if _eec :=_gegd ._fccd ._fffa .export (_agca );_eec !=nil {return _eec ;};};};return nil ;};const _dgdg =6;func (_adcb *morphDataControl )readColumnInfo (_adbd *_dg .Reader )error {return nil };

// SetForeColor sets a button text color value from a system palette for a scrollBar control.
func (_cggc *ScrollBarControl )SetForeColor (foreColor uint32 ){_cggc ._ggcg ._dfcac =true ;_cggc ._cad ._edgb =foreColor ;};

// GetCaption gets a caption string from a morph control.
func (_adgf *morphDataControl )GetCaption ()string {if _adgf ._fdb &&_adgf ._dca ._ace {return _adgf ._gef ._cdc ;};return "";};type stdPicture struct{_bbfe uint32 ;_efef uint32 ;_cfc *_gd .Buffer ;};

// GetCaption gets a caption string from a commandButton control.
func (_dfgd *CommandButtonControl )GetCaption ()string {return _dfgd ._de ._dgd };

// GetWidth returns width of the Label in HIMETRIC (0.01mm)
func (_bbdg *LabelControl )GetWidth ()uint32 {return _bbdg ._fea ._cae };func (_ggg *guidAndPicture )getStdPictureBytes ()[]byte {if _ggg !=nil &&_ggg ._gfbaa !=nil &&_ggg ._gfbaa ._cfc !=nil {return _ggg ._gfbaa ._cfc .Bytes ();};return nil ;};const _bbed =1;
func (_abe *ImageControl )writeDataBlock (_fce *_dg .Writer )error {if _abe ._gcd ._eafd {if _fga :=_fce .WriteProperty (_abe ._ec ._agdf );_fga !=nil {return _fga ;};};if _abe ._gcd ._gfa {if _ded :=_fce .WriteProperty (_abe ._ec ._dbcb );_ded !=nil {return _ded ;
};};if _abe ._gcd ._gaa {if _bab :=_fce .WriteProperty (_abe ._ec ._fae );_bab !=nil {return _bab ;};};if _abe ._gcd ._bea {if _dcdf :=_fce .WriteProperty (_abe ._ec ._aedb );_dcdf !=nil {return _dcdf ;};};if _abe ._gcd ._dade {if _fbf :=_fce .WriteProperty (_abe ._ec ._gcge );
_fbf !=nil {return _fbf ;};};if _abe ._gcd ._bgfc {if _ceg :=_fce .WriteProperty (_abe ._ec ._efee );_ceg !=nil {return _ceg ;};};if _abe ._gcd ._fff {if _cdg :=_fce .WriteProperty (_abe ._ec ._cbd );_cdg !=nil {return _cdg ;};};if _abe ._gcd ._dbba {if _abffg :=_fce .WriteProperty (_abe ._ec ._aeg );
_abffg !=nil {return _abffg ;};};if _abe ._gcd ._eae {if _fgc :=_fce .WriteProperty (_abe ._ec ._gbd );_fgc !=nil {return _fgc ;};};if _abe ._gcd ._faf {if _dba :=_fce .WriteProperty (_abe ._ec ._aadg );_dba !=nil {return _dba ;};};return _fce .AlignLength (4);
};

// SetMin sets a button min value.
func (_bfcb *SpinButtonControl )SetMin (min int32 ){_bfcb ._acfa ._dcg =true ;_bfcb ._cdeab ._afcbc =min };type spinButtonDataBlock struct{_geaf uint32 ;_bdf uint32 ;_ggcc uint32 ;_afcbc int32 ;_gbf int32 ;_cdgd int32 ;_bggdb int32 ;_dfcf int32 ;_ccfd int32 ;
_eeec uint32 ;_bbda uint32 ;_dfbd uint16 ;_bcfc uint8 ;};

// GetHeight returns height of the ScrollBar in HIMETRIC (0.01mm)
func (_edbc *ScrollBarControl )GetHeight ()uint32 {return _edbc ._efb ._bggc };

// GetHeight returns height of the SpinButton in HIMETRIC (0.01mm)
func (_cge *SpinButtonControl )GetHeight ()uint32 {return _cge ._afdg ._bbcb };

// ScrollBarControl is a representation of a scrollBar ActiveX form.
type ScrollBarControl struct{controlBase ;_ggcg *scrollBarPropMask ;_cad *scrollBarDataBlock ;_efb *scrollBarExtraDataBlock ;_feag *streamData ;};func (_fdfe *ScrollBarControl )writeDataBlock (_fca *_dg .Writer )error {if _fdfe ._ggcg ._dfcac {if _cdba :=_fca .WriteProperty (_fdfe ._cad ._edgb );
_cdba !=nil {return _cdba ;};};if _fdfe ._ggcg ._ebgb {if _gad :=_fca .WriteProperty (_fdfe ._cad ._abdb );_gad !=nil {return _gad ;};};if _fdfe ._ggcg ._geba {if _ceab :=_fca .WriteProperty (_fdfe ._cad ._cdbe );_ceab !=nil {return _ceab ;};};if _fdfe ._ggcg ._cdef {if _affc :=_fca .WriteProperty (_fdfe ._cad ._bcge );
_affc !=nil {return _affc ;};};if _fdfe ._ggcg ._afaf {if _ddf :=_fca .WriteProperty (_fdfe ._cad ._faca );_ddf !=nil {return _ddf ;};};if _fdfe ._ggcg ._febf {if _efc :=_fca .WriteProperty (_fdfe ._cad ._cdecc );_efc !=nil {return _efc ;};};if _fdfe ._ggcg ._fgbg {if _egeg :=_fca .WriteProperty (_fdfe ._cad ._fgba );
_egeg !=nil {return _egeg ;};};if _fdfe ._ggcg ._fbec {if _fadbd :=_fca .WriteProperty (_fdfe ._cad ._dfega );_fadbd !=nil {return _fadbd ;};};if _fdfe ._ggcg ._ffcb {if _fbfb :=_fca .WriteProperty (_fdfe ._cad ._bebf );_fbfb !=nil {return _fbfb ;};};if _fdfe ._ggcg ._fba {if _geab :=_fca .WriteProperty (_fdfe ._cad ._agcg );
_geab !=nil {return _geab ;};};if _fdfe ._ggcg ._ffcfd {if _fccc :=_fca .WriteProperty (_fdfe ._cad ._gccf );_fccc !=nil {return _fccc ;};};if _fdfe ._ggcg ._geac {if _dddd :=_fca .WriteProperty (_fdfe ._cad ._eaec );_dddd !=nil {return _dddd ;};};if _fdfe ._ggcg ._eba {if _afafg :=_fca .WriteProperty (_fdfe ._cad ._aged );
_afafg !=nil {return _afafg ;};};if _fdfe ._ggcg ._fdc {if _begg :=_fca .WriteProperty (_fdfe ._cad ._efaa );_begg !=nil {return _begg ;};};if _fdfe ._ggcg ._dcace {if _agbac :=_fca .WriteProperty (_fdfe ._cad ._aec );_agbac !=nil {return _agbac ;};};return _fca .AlignLength (4);
};func (_cggf *controlBase )setMouseIconBytes (_eg []byte ){if _cggf ._fccd ._bdaf ==nil {_cggf ._fccd ._bdaf =&guidAndPicture {};};_cggf ._fccd ._bdaf .setStdPictureBytes (_eg );};func (_fgad *ScrollBarControl )export (_bfc *_dg .Writer )error {if _feg :=_fgad .writePropMask (_bfc );
_feg !=nil {return _feg ;};if _gdfb :=_fgad .writeDataBlock (_bfc );_gdfb !=nil {return _gdfb ;};if _dfeg :=_fgad .writeExtraDataBlock (_bfc );_dfeg !=nil {return _dfeg ;};_fgad ._dag =uint16 (_bfc .Len ()-4);if _bgge :=_fgad .writeStreamDataM (_bfc );
_bgge !=nil {return _bgge ;};return _fgad .writeTheRest (_bfc );};func (_afbf *morphDataControl )writePropMask (_eaaaaf *_dg .Writer )error {_gbba :=uint64 (0);_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._aaaa );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bfg );
_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._aca );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._gaf );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._gegc );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bad );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._abecc );
_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._gcad );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bge );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._ggagd );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._cfce );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._egd );
_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bcac );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._fead );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bggdd );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._eagf );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bgba );
_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bae );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bcab );_gbba >>=1;_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._ffea );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._gea );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._gccbe );
_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._ace );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._ebe );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._gafa );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._dafc );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._bdac );
_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._cbcf );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._eac );_gbba >>=1;_gbba =_dg .PushLeftUI64 (_gbba ,true );_gbba =_dg .PushLeftUI64 (_gbba ,_afbf ._dca ._dccd );_gbba >>=31;return _f .Write (_eaaaaf ,_f .LittleEndian ,_gbba );
};const _cbdd =2;

// SetBackColor sets a button text color value from a system palette for a scrollBar control.
func (_befg *ScrollBarControl )SetBackColor (backColor uint32 ){_befg ._ggcg ._ebgb =true ;_befg ._cad ._abdb =backColor ;};func (_gca *morphDataControl )getValueString ()string {if _gca ._dca ._gccbe {return _gca ._gef ._ccad ;};return "";};func (_bbdc *ScrollBarControl )readPropMask (_dce *_dg .Reader )error {var _dab uint32 ;
if _bac :=_f .Read (_dce ,_f .LittleEndian ,&_dab );_bac !=nil {return _bac ;};_bbdc ._ggcg =&scrollBarPropMask {};_bbdc ._ggcg ._dfcac ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._ebgb ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._geba ,_dab =_dg .PopRightUI32 (_dab );
_bbdc ._ggcg ._bbbeg ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._cdef ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._afaf ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._febf ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._fgbg ,_dab =_dg .PopRightUI32 (_dab );
_dab >>=1;_bbdc ._ggcg ._fbec ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._ffcb ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._fba ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._ffcfd ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._geac ,_dab =_dg .PopRightUI32 (_dab );
_bbdc ._ggcg ._eba ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._fdc ,_dab =_dg .PopRightUI32 (_dab );_bbdc ._ggcg ._dcace ,_dab =_dg .PopRightUI32 (_dab );return nil ;};

// GetPosition gets a button position value.
func (_egdc *SpinButtonControl )GetPosition ()int32 {return _egdc ._cdeab ._cdgd };

// SetWidth sets width of the Label in HIMETRIC (0.01mm)
func (_fgcf *LabelControl )SetWidth (width uint32 ){_fgcf ._agf ._decae =true ;_fgcf ._fea ._cae =width };func (_fadb *LabelControl )readExtraDataBlock (_cdfa *_dg .Reader )error {_fadb ._fea =&labelExtraDataBlock {};if _fadb ._cdfe ._eag > 0{_beaae ,_egga :=_cdfa .ReadStringProperty (_fadb ._cdfe ._eag );
if _egga !=nil {return _egga ;};_fadb ._fea ._gdbf =_beaae ;};if _fadb ._agf ._decae {var _cfa uint64 ;if _gddg :=_cdfa .ReadPairProperty (&_cfa );_gddg !=nil {return _gddg ;};_fadb ._fea ._ffc =uint32 (_cfa );_fadb ._fea ._cae =uint32 (_cfa >>32);};return nil ;
};func (_eacf *SpinButtonControl )readPropMask (_gega *_dg .Reader )error {var _cgca uint32 ;if _abb :=_f .Read (_gega ,_f .LittleEndian ,&_cgca );_abb !=nil {return _abb ;};_eacf ._acfa =&spinButtonPropMask {};_eacf ._acfa ._abeb ,_cgca =_dg .PopRightUI32 (_cgca );
_eacf ._acfa ._aadb ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._agaa ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._eeeg ,_cgca =_dg .PopRightUI32 (_cgca );_cgca >>=1;_eacf ._acfa ._dcg ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._gbe ,_cgca =_dg .PopRightUI32 (_cgca );
_eacf ._acfa ._cfag ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._egc ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._edgf ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._cced ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._aeaf ,_cgca =_dg .PopRightUI32 (_cgca );
_eacf ._acfa ._bde ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._eefa ,_cgca =_dg .PopRightUI32 (_cgca );_eacf ._acfa ._fdcb ,_cgca =_dg .PopRightUI32 (_cgca );return nil ;};func (_cbe *SpinButtonControl )writeDataBlock (_bggaf *_dg .Writer )error {if _cbe ._acfa ._abeb {if _fgae :=_bggaf .WriteProperty (_cbe ._cdeab ._geaf );
_fgae !=nil {return _fgae ;};};if _cbe ._acfa ._aadb {if _gbbgf :=_bggaf .WriteProperty (_cbe ._cdeab ._bdf );_gbbgf !=nil {return _gbbgf ;};};if _cbe ._acfa ._agaa {if _gcfd :=_bggaf .WriteProperty (_cbe ._cdeab ._ggcc );_gcfd !=nil {return _gcfd ;};};
if _cbe ._acfa ._dcg {if _edec :=_bggaf .WriteProperty (_cbe ._cdeab ._afcbc );_edec !=nil {return _edec ;};};if _cbe ._acfa ._gbe {if _fedc :=_bggaf .WriteProperty (_cbe ._cdeab ._gbf );_fedc !=nil {return _fedc ;};};if _cbe ._acfa ._cfag {if _bagd :=_bggaf .WriteProperty (_cbe ._cdeab ._cdgd );
_bagd !=nil {return _bagd ;};};if _cbe ._acfa ._egc {if _ecd :=_bggaf .WriteProperty (_cbe ._cdeab ._bggdb );_ecd !=nil {return _ecd ;};};if _cbe ._acfa ._edgf {if _fbge :=_bggaf .WriteProperty (_cbe ._cdeab ._dfcf );_fbge !=nil {return _fbge ;};};if _cbe ._acfa ._cced {if _agga :=_bggaf .WriteProperty (_cbe ._cdeab ._ccfd );
_agga !=nil {return _agga ;};};if _cbe ._acfa ._aeaf {if _effa :=_bggaf .WriteProperty (_cbe ._cdeab ._eeec );_effa !=nil {return _effa ;};};if _cbe ._acfa ._bde {if _abbd :=_bggaf .WriteProperty (_cbe ._cdeab ._bbda );_abbd !=nil {return _abbd ;};};if _cbe ._acfa ._eefa {if _cfaag :=_bggaf .WriteProperty (_cbe ._cdeab ._dfbd );
_cfaag !=nil {return _cfaag ;};};if _cbe ._acfa ._fdcb {if _bgdf :=_bggaf .WriteProperty (_cbe ._cdeab ._bcfc );_bgdf !=nil {return _bgdf ;};};return _bggaf .AlignLength (4);};

// FmPictureAlignment represents one of the five picture aignments according to MS-OFORMS document.
type FmPictureAlignment byte ;

// GetValue gets a value from a control which value can be represented as boolean (on/off).
func (_aee *morphDataControlBoolValue )GetValue ()bool {return _aee .getValueBool ()};func (_cbg *CommandButtonControl )writeDataBlock (_fcf *_dg .Writer )error {if _cbg ._baac ._ef {if _fab :=_fcf .WriteProperty (_cbg ._bef ._ebc );_fab !=nil {return _fab ;
};};if _cbg ._baac ._agb {if _cca :=_fcf .WriteProperty (_cbg ._bef ._ddg );_cca !=nil {return _cca ;};};if _cbg ._baac ._bee {if _aac :=_fcf .WriteProperty (_cbg ._bef ._cf );_aac !=nil {return _aac ;};};if _cbg ._baac ._gga {_gcf :=_cd (_cbg ._bef ._gbb ,_cbg ._bef ._cde );
if _bbe :=_fcf .WriteProperty (_gcf );_bbe !=nil {return _bbe ;};};if _cbg ._baac ._efe {if _ffe :=_fcf .WriteProperty (_cbg ._bef ._eab );_ffe !=nil {return _ffe ;};};if _cbg ._baac ._cefe {if _gdbc :=_fcf .WriteProperty (_cbg ._bef ._ddb );_gdbc !=nil {return _gdbc ;
};};if _cbg ._baac ._fcc {if _bbd :=_fcf .WriteProperty (_cbg ._bef ._cfd );_bbd !=nil {return _bbd ;};};if _cbg ._baac ._gdb {if _eaf :=_fcf .WriteProperty (_cbg ._bef ._adda );_eaf !=nil {return _eaf ;};};if _cbg ._baac ._bf {if _dac :=_fcf .WriteProperty (_cbg ._bef ._dad );
_dac !=nil {return _dac ;};};return _fcf .AlignLength (4);};func (_dfc *controlBase )readTheRest (_bbf *_dg .Reader )error {_ead :=_gd .NewBuffer ([]byte {});_ ,_ege :=_af .Copy (_ead ,_bbf );if _ege !=nil {return _ege ;};_dfc ._abff =_ead .Bytes ();return nil ;
};func (_eaab *CommandButtonControl )readExtraDataBlock (_cdec *_dg .Reader )error {_eaab ._de =&commandButtonExtraDataBlock {};if _eaab ._bef ._gbb > 0{_eeb ,_ccef :=_cdec .ReadStringProperty (_eaab ._bef ._gbb );if _ccef !=nil {return _ccef ;};_eaab ._de ._dgd =_eeb ;
};if _eaab ._baac ._eaa {var _ffa uint64 ;if _ggc :=_cdec .ReadPairProperty (&_ffa );_ggc !=nil {return _ggc ;};_eaab ._de ._cacd =uint32 (_ffa );_eaab ._de ._eaaa =uint32 (_ffa >>32);};return nil ;};func (_cec *CommandButtonControl )writePropMask (_ge *_dg .Writer )error {_afb :=uint32 (0);
_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._ef );_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._agb );_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._bee );_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._gga );_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._efe );
_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._eaa );_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._cefe );_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._fcc );_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._gdb );_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._add );
_afb =_dg .PushLeftUI32 (_afb ,_cec ._baac ._bf );_afb >>=21;return _f .Write (_ge ,_f .LittleEndian ,_afb );};func _becb (_bdae *_dg .Reader )(*SpinButtonControl ,error ){_ebga :=&SpinButtonControl {};if _adga :=_ebga .readPropMask (_bdae );_adga !=nil {return nil ,_adga ;
};if _feef :=_ebga .readDataBlock (_bdae );_feef !=nil {return nil ,_feef ;};if _dbbc :=_ebga .readExtraDataBlock (_bdae );_dbbc !=nil {return nil ,_dbbc ;};if _fbab :=_ebga .readStreamDataM (_bdae ,_ebga ._acfa ._eefa );_fbab !=nil {return nil ,_fbab ;
};if _dfdg :=_ebga .readTheRest (_bdae );_dfdg !=nil {return nil ,_dfdg ;};return _ebga ,nil ;};

// SetMax sets a button max value.
func (_dge *SpinButtonControl )SetMax (max int32 ){_dge ._acfa ._gbe =true ;_dge ._cdeab ._gbf =max };

// Control represents an ActiveX control wrapper.
type Control struct{TargetAttr string ;Ocx *_db .Ocx ;Choice *ControlChoice ;_gf string ;_dc uint8 ;_cb uint8 ;_dgf uint16 ;};type labelPropMask struct{_fffd bool ;_fec bool ;_bec bool ;_acd bool ;_fbfd bool ;_decae bool ;_dbe bool ;_cbbe bool ;_aedbc bool ;
_dea bool ;_fdbe bool ;_ecb bool ;_fadg bool ;};

// SetForeColor sets a button text color value from a system palette for a label control.
func (_gcee *LabelControl )SetForeColor (foreColor uint32 ){_gcee ._agf ._fffd =true ;_gcee ._cdfe ._fef =foreColor ;};func _ggbge (_cgb *_dg .Reader )(*ImageControl ,error ){_cfda :=&ImageControl {};if _deg :=_cfda .readPropMask (_cgb );_deg !=nil {return nil ,_deg ;
};if _gcgc :=_cfda .readDataBlock (_cgb );_gcgc !=nil {return nil ,_gcgc ;};if _acfd :=_cfda .readExtraDataBlock (_cgb );_acfd !=nil {return nil ,_acfd ;};if _ggfb :=_cfda .readStreamDataPM (_cgb ,_cfda ._gcd ._fff ,_cfda ._gcd ._faf );_ggfb !=nil {return nil ,_ggfb ;
};if _gccb :=_cfda .readTheRest (_cgb );_gccb !=nil {return nil ,_gccb ;};return _cfda ,nil ;};func (_bbfc *LabelControl )export (_ggeb *_dg .Writer )error {if _beaa :=_bbfc .writePropMask (_ggeb );_beaa !=nil {return _beaa ;};if _cfe :=_bbfc .writeDataBlock (_ggeb );
_cfe !=nil {return _cfe ;};if _beb :=_bbfc .writeExtraDataBlock (_ggeb );_beb !=nil {return _beb ;};_bbfc ._dag =uint16 (_ggeb .Len ()-4);if _gfc :=_bbfc .writeStreamDataPM (_ggeb );_gfc !=nil {return _gfc ;};return _bbfc .writeTheRest (_ggeb );};

// SetBackColor sets a button text color value from a system palette for a spinButton control.
func (_ecea *SpinButtonControl )SetBackColor (backColor uint32 ){_ecea ._acfa ._aadb =true ;_ecea ._cdeab ._bdf =backColor ;};

// TextBoxDataControl is a representation of a text box ActiveX form.
type TextBoxDataControl struct{*morphDataControlStringValue };

// GetBackColor gets a button text color value for a system palette from a spinButton control.
func (_ccff *SpinButtonControl )GetBackColor ()uint32 {return _ccff ._cdeab ._bdf };func (_gab *morphDataControl )export (_acdc *_dg .Writer )error {if _fcb :=_gab .writePropMask (_acdc );_fcb !=nil {return _fcb ;};if _cbab :=_gab .writeDataBlock (_acdc );
_cbab !=nil {return _cbab ;};if _eaaca :=_gab .writeExtraDataBlock (_acdc );_eaaca !=nil {return _eaaca ;};_gab ._dag =uint16 (_acdc .Len ()-4);if _bggd :=_gab .writeStreamDataMP (_acdc );_bggd !=nil {return _bggd ;};return _gab .writeTheRest (_acdc );
};type imagePropMask struct{_beg bool ;_eafd bool ;_gfa bool ;_gaa bool ;_bea bool ;_dade bool ;_bgfc bool ;_acb bool ;_fff bool ;_dbba bool ;_gdbg bool ;_eae bool ;_faf bool ;};func (_fgcc *ScrollBarControl )writeExtraDataBlock (_ddfa *_dg .Writer )error {if _fgcc ._ggcg ._bbbeg {_ccfg :=uint64 (_fgcc ._efb ._cbgcb )<<32|uint64 (_fgcc ._efb ._bggc );
if _aggb :=_ddfa .WritePropertyNoAlign (_ccfg );_aggb !=nil {return _aggb ;};};return nil ;};

// SetHeight sets height of the morphDataControl in HIMETRIC (0.01mm)
func (_cfb *morphDataControl )SetHeight (height uint32 ){_cfb ._dca ._bge =true ;_cfb ._gef ._gdcgd =height ;};func (_fcgg *ScrollBarControl )readExtraDataBlock (_eegf *_dg .Reader )error {_fcgg ._efb =&scrollBarExtraDataBlock {};if _fcgg ._ggcg ._bbbeg {var _dgcac uint64 ;
if _deea :=_eegf .ReadPairProperty (&_dgcac );_deea !=nil {return _deea ;};_fcgg ._efb ._bggc =uint32 (_dgcac );_fcgg ._efb ._cbgcb =uint32 (_dgcac >>32);};return nil ;};func (_effc *controlBase )writeStreamDataPM (_debf *_dg .Writer )error {if _effc ._fccd !=nil {if _effc ._fccd ._fffa !=nil {if _aadbc :=_effc ._fccd ._fffa .export (_debf );
_aadbc !=nil {return _aadbc ;};};if _effc ._fccd ._bdaf !=nil {if _gcbf :=_effc ._fccd ._bdaf .export (_debf );_gcbf !=nil {return _gcbf ;};};};return nil ;};func _cd (_dbb uint32 ,_aeb bool )uint32 {if _dbb ==0{return 0;};if _aeb {_dbb |=1<<31;};return _dbb ;
};func (_cdeb *morphDataControl )readColumnInfoDataBlock (_ddee *_dg .Reader )error {return nil };

// GetHeight returns height of the CommandButton in HIMETRIC (0.01mm)
func (_fa *CommandButtonControl )GetHeight ()uint32 {return _fa ._de ._cacd };

// SetHeight sets height of the ScrollBar in HIMETRIC (0.01mm)
func (_aae *ScrollBarControl )SetHeight (height uint32 ){_aae ._ggcg ._bbbeg =true ;_aae ._efb ._bggc =height ;};

// SetCaption sets a caption string for a commandButton control.
func (_gced *CommandButtonControl )SetCaption (caption string ){_gced ._baac ._gga =true ;_gced ._bef ._gbb =uint32 (len (caption ));_gced ._de ._dgd =caption ;};func (_baba *morphDataControl )writeDataBlock (_gaag *_dg .Writer )error {if _baba ._dca ._aaaa {if _efed :=_gaag .WriteProperty (_baba ._ebca ._dde );
_efed !=nil {return _efed ;};};if _baba ._dca ._bfg {if _ggbgec :=_gaag .WriteProperty (_baba ._ebca ._cdbb );_ggbgec !=nil {return _ggbgec ;};};if _baba ._dca ._aca {if _ceaa :=_gaag .WriteProperty (_baba ._ebca ._fcdd );_ceaa !=nil {return _ceaa ;};};
if _baba ._dca ._gaf {if _gfcc :=_gaag .WriteProperty (_baba ._ebca ._fafg );_gfcc !=nil {return _gfcc ;};};if _baba ._dca ._gegc {if _eee :=_gaag .WriteProperty (_baba ._ebca ._gag );_eee !=nil {return _eee ;};};if _baba ._dca ._bad {if _edff :=_gaag .WriteProperty (_baba ._ebca ._cgac );
_edff !=nil {return _edff ;};};if _baba ._dca ._abecc {if _ecec :=_gaag .WriteProperty (_baba ._ebca ._cacdd );_ecec !=nil {return _ecec ;};};if _baba ._dca ._gcad {if _agfd :=_gaag .WriteProperty (_baba ._ebca ._bgggc );_agfd !=nil {return _agfd ;};};
if _baba ._dca ._ggagd {if _edg :=_gaag .WriteProperty (_baba ._ebca ._feea );_edg !=nil {return _edg ;};};if _baba ._dca ._cfce {if _cfcc :=_gaag .WriteProperty (_baba ._ebca ._agc );_cfcc !=nil {return _cfcc ;};};if _baba ._dca ._egd {if _adfg :=_gaag .WriteProperty (_baba ._ebca ._gffa );
_adfg !=nil {return _adfg ;};};if _baba ._dca ._bcac {if _dgcdf :=_gaag .WriteProperty (_baba ._ebca ._bgd );_dgcdf !=nil {return _dgcdf ;};};if _baba ._dca ._fead {if _aeab :=_gaag .WriteProperty (_baba ._ebca ._dgdf );_aeab !=nil {return _aeab ;};};if _baba ._dca ._bggdd {if _dgca :=_gaag .WriteProperty (_baba ._ebca ._dbd );
_dgca !=nil {return _dgca ;};};if _baba ._dca ._eagf {if _ecad :=_gaag .WriteProperty (_baba ._ebca ._gdcg );_ecad !=nil {return _ecad ;};};if _baba ._dca ._bgba {if _acac :=_gaag .WriteProperty (_baba ._ebca ._ega );_acac !=nil {return _acac ;};};if _baba ._dca ._bae {if _aag :=_gaag .WriteProperty (_baba ._ebca ._acec );
_aag !=nil {return _aag ;};};if _baba ._dca ._bcab {if _ebb :=_gaag .WriteProperty (_baba ._ebca ._dgda );_ebb !=nil {return _ebb ;};};if _baba ._dca ._ffea {if _aga :=_gaag .WriteProperty (_baba ._ebca ._gbag );_aga !=nil {return _aga ;};};if _baba ._dca ._gea {if _gee :=_gaag .WriteProperty (_baba ._ebca ._beaad );
_gee !=nil {return _gee ;};};if _baba ._dca ._gccbe {_gdea :=_cd (_baba ._ebca ._afee ,_baba ._ebca ._bbc );if _efda :=_gaag .WriteProperty (_gdea );_efda !=nil {return _efda ;};};if _baba ._dca ._ace {_gbbc :=_cd (_baba ._ebca ._bcag ,_baba ._ebca ._bgc );
if _cfba :=_gaag .WriteProperty (_gbbc );_cfba !=nil {return _cfba ;};};if _baba ._dca ._ebe {if _dfcaf :=_gaag .WriteProperty (_baba ._ebca ._debd );_dfcaf !=nil {return _dfcaf ;};};if _baba ._dca ._gafa {if _acbb :=_gaag .WriteProperty (_baba ._ebca ._ddd );
_acbb !=nil {return _acbb ;};};if _baba ._dca ._dafc {if _edeb :=_gaag .WriteProperty (_baba ._ebca ._dbdf );_edeb !=nil {return _edeb ;};};if _baba ._dca ._bdac {if _aab :=_gaag .WriteProperty (_baba ._ebca ._gfe );_aab !=nil {return _aab ;};};if _baba ._dca ._cbcf {if _gdgc :=_gaag .WriteProperty (_baba ._ebca ._caea );
_gdgc !=nil {return _gdgc ;};};if _baba ._dca ._eac {if _befa :=_gaag .WriteProperty (_baba ._ebca ._dfdc );_befa !=nil {return _befa ;};};if _baba ._dca ._dccd {_fbga :=_cd (_baba ._ebca ._aced ,_baba ._ebca ._ffcf );if _dgbe :=_gaag .WriteProperty (_fbga );
_dgbe !=nil {return _dgbe ;};};return _gaag .AlignLength (4);};

// SetCaption sets a caption string for a morph control.
func (_adaf *morphDataControl )SetCaption (caption string ){if _adaf ._fdb {_adaf ._dca ._ace =true ;_adaf ._ebca ._bcag =uint32 (len (caption ));_adaf ._gef ._cdc =caption ;};};func (_agbag *morphDataControl )setValueString (_efeg string ){_agbag ._dca ._gccbe =true ;
_agbag ._ebca ._afee =uint32 (len (_efeg ));_agbag ._gef ._ccad =_efeg ;};type guidAndPicture struct{_cdf []byte ;_gfbaa *stdPicture ;};

// SetBackColor sets a button text color value from a system palette for a commandButton control.
func (_bag *CommandButtonControl )SetBackColor (backColor uint32 ){_bag ._baac ._agb =true ;_bag ._bef ._ddg =backColor ;};func (_aed *ImageControl )writePropMask (_gbcb *_dg .Writer )error {_dfca :=uint32 (0);_dfca >>=2;_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._beg );
_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._eafd );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._gfa );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._gaa );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._bea );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._dade );
_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._bgfc );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._acb );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._fff );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._dbba );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._gdbg );
_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._eae );_dfca =_dg .PushLeftUI32 (_dfca ,_aed ._gcd ._faf );_dfca >>=17;return _f .Write (_gbcb ,_f .LittleEndian ,_dfca );};func (_dcb *controlBase )getMouseIconBytes ()[]byte {return _dcb ._fccd ._bdaf .getStdPictureBytes ()};
func (_dee *guidAndPicture )export (_daga *_dg .Writer )error {if _ ,_agba :=_af .Copy (_daga ,_gd .NewBuffer (_dee ._cdf ));_agba !=nil {return _agba ;};if _aebd :=_daga .WriteProperty (_dee ._gfbaa ._bbfe );_aebd !=nil {return _aebd ;};if _cbgd :=_daga .WriteProperty (_dee ._gfbaa ._efef );
_cbgd !=nil {return _cbgd ;};_ ,_beff :=_af .Copy (_daga ,_dee ._gfbaa ._cfc );if _beff !=nil {return _beff ;};return nil ;};

// GetWidth returns width of the ScrollBar in HIMETRIC (0.01mm)
func (_fdbb *ScrollBarControl )GetWidth ()uint32 {return _fdbb ._efb ._cbgcb };func (_gbca *controlBase )writeTheRest (_acf *_dg .Writer )error {_ ,_fad :=_acf .Write (_gbca ._abff );return _fad ;};

// ImportFromFile makes a Control from a file in a storage.
func ImportFromFile (storagePath string )(*Control ,error ){_dga ,_ba :=_c .Open (storagePath );if _ba !=nil {return nil ,_ba ;};defer _dga .Close ();_gc ,_ba :=_ab .New (_dga );if _ba !=nil {return nil ,_ba ;};_ad ,_ba :=_agd (_gc );if _ba !=nil {return nil ,_ba ;
};_gfb ,_ba :=_gc .GetEntry ("\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0073");if _ba !=nil {return nil ,_ba ;};_gdg :=make ([]byte ,_gfb .Size );_ ,_ba =_gfb .Read (_gdg );if _ba !=nil {return nil ,_ba ;};_fc :=&Control {_gf :storagePath };_acc ,_ba :=_dg .NewReader (_gdg );
if _ba !=nil {return nil ,_ba ;};if _gg :=_f .Read (_acc ,_f .LittleEndian ,&_fc ._dc );_gg !=nil {return nil ,_gg ;};if _ag :=_f .Read (_acc ,_f .LittleEndian ,&_fc ._cb );_ag !=nil {return nil ,_ag ;};if _bg :=_f .Read (_acc ,_f .LittleEndian ,&_fc ._dgf );
_bg !=nil {return nil ,_bg ;};switch _ad {case "\u0043\u0068\u0065\u0063\u006b\u0042\u006f\u0078":_gce ,_df :=_bggg (_acc );if _df !=nil {return nil ,_df ;};_gce ._fdb =true ;_fc .Choice =&ControlChoice {CheckBox :&CheckBoxDataControl {&morphDataControlBoolValue {_gce }}};
case "\u0054e\u0078\u0074\u0042\u006f\u0078":_dcd ,_gfba :=_bggg (_acc );if _gfba !=nil {return nil ,_gfba ;};_dcd ._fdb =true ;_fc .Choice =&ControlChoice {TextBox :&TextBoxDataControl {&morphDataControlStringValue {_dcd }}};case "\u0043\u006f\u006d\u0062\u006f\u0042\u006f\u0078":_e ,_gcc :=_bggg (_acc );
if _gcc !=nil {return nil ,_gcc ;};_e ._fdb =true ;_fc .Choice =&ControlChoice {ComboBox :&ComboBoxDataControl {&morphDataControlStringValue {_e }}};case "\u004ci\u0073\u0074\u0042\u006f\u0078":_fe ,_ed :=_bggg (_acc );if _ed !=nil {return nil ,_ed ;};
_fe ._fdb =true ;_fc .Choice =&ControlChoice {ListBox :&ListBoxDataControl {&morphDataControlStringValue {_fe }}};case "\u004f\u0070\u0074i\u006f\u006e\u0042\u0075\u0074\u0074\u006f\u006e":_ede ,_ee :=_bggg (_acc );if _ee !=nil {return nil ,_ee ;};_ede ._fdb =true ;
_fc .Choice =&ControlChoice {OptionButton :&OptionButtonDataControl {&morphDataControlBoolValue {_ede }}};case "\u0054\u006f\u0067g\u006c\u0065\u0042\u0075\u0074\u0074\u006f\u006e":_adg ,_dgc :=_bggg (_acc );if _dgc !=nil {return nil ,_dgc ;};_adg ._fdb =true ;
_fc .Choice =&ControlChoice {ToggleButton :&ToggleButtonDataControl {&morphDataControlBoolValue {_adg }}};case "\u004c\u0061\u0062e\u006c":_aa ,_bgf :=_bggb (_acc );if _bgf !=nil {return nil ,_bgf ;};_fc .Choice =&ControlChoice {Label :_aa };case "\u0053\u0070\u0069\u006e\u0042\u0075\u0074\u0074\u006f\u006e":_fg ,_gge :=_becb (_acc );
if _gge !=nil {return nil ,_gge ;};_fc .Choice =&ControlChoice {SpinButton :_fg };case "\u0043\u006f\u006d\u006d\u0061\u006e\u0064\u0042\u0075\u0074\u0074\u006f\u006e":_gb ,_gcb :=_ca (_acc );if _gcb !=nil {return nil ,_gcb ;};_fc .Choice =&ControlChoice {CommandButton :_gb };
case "\u0053c\u0072\u006f\u006c\u006c\u0042\u0061r":_ae ,_ff :=_agfc (_acc );if _ff !=nil {return nil ,_ff ;};_fc .Choice =&ControlChoice {ScrollBar :_ae };default:_dfb :=&controlBase {};if _afc :=_dfb .readTheRest (_acc );_afc !=nil {return nil ,_afc ;
};_fc .Choice =&ControlChoice {_b :_dfb };};return _fc ,nil ;};type morphDataControlStringValue struct{*morphDataControl };

// SetHeight sets height of the CommandButton in HIMETRIC (0.01mm)
func (_aebb *CommandButtonControl )SetHeight (height uint32 ){_aebb ._baac ._eaa =true ;_aebb ._de ._cacd =height ;};var _cea =len (_gdab );func (_becf *morphDataControl )readDataBlock (_dcce *_dg .Reader )error {_becf ._ebca =&morphDataDataBlock {};if _becf ._dca ._aaaa {if _dacd :=_dcce .ReadProperty (&_becf ._ebca ._dde );
_dacd !=nil {return _dacd ;};};if _becf ._dca ._bfg {if _bcad :=_dcce .ReadProperty (&_becf ._ebca ._cdbb );_bcad !=nil {return _bcad ;};};if _becf ._dca ._aca {if _gebb :=_dcce .ReadProperty (&_becf ._ebca ._fcdd );_gebb !=nil {return _gebb ;};};if _becf ._dca ._gaf {if _bbg :=_dcce .ReadProperty (&_becf ._ebca ._fafg );
_bbg !=nil {return _bbg ;};};if _becf ._dca ._gegc {if _bede :=_dcce .ReadProperty (&_becf ._ebca ._gag );_bede !=nil {return _bede ;};};if _becf ._dca ._bad {if _gfde :=_dcce .ReadProperty (&_becf ._ebca ._cgac );_gfde !=nil {return _gfde ;};};if _becf ._dca ._abecc {if _gccd :=_dcce .ReadProperty (&_becf ._ebca ._cacdd );
_gccd !=nil {return _gccd ;};};if _becf ._dca ._gcad {if _adfc :=_dcce .ReadProperty (&_becf ._ebca ._bgggc );_adfc !=nil {return _adfc ;};};if _becf ._dca ._ggagd {if _afdf :=_dcce .ReadProperty (&_becf ._ebca ._feea );_afdf !=nil {return _afdf ;};};if _becf ._dca ._cfce {if _gedc :=_dcce .ReadProperty (&_becf ._ebca ._agc );
_gedc !=nil {return _gedc ;};};if _becf ._dca ._egd {if _eca :=_dcce .ReadProperty (&_becf ._ebca ._gffa );_eca !=nil {return _eca ;};};if _becf ._dca ._bcac {if _eddf :=_dcce .ReadProperty (&_becf ._ebca ._bgd );_eddf !=nil {return _eddf ;};};if _becf ._dca ._fead {if _adgg :=_dcce .ReadProperty (&_becf ._ebca ._dgdf );
_adgg !=nil {return _adgg ;};};if _becf ._dca ._bggdd {if _eged :=_dcce .ReadProperty (&_becf ._ebca ._dbd );_eged !=nil {return _eged ;};};if _becf ._dca ._eagf {if _dfe :=_dcce .ReadProperty (&_becf ._ebca ._gdcg );_dfe !=nil {return _dfe ;};};if _becf ._dca ._bgba {if _cgcg :=_dcce .ReadProperty (&_becf ._ebca ._ega );
_cgcg !=nil {return _cgcg ;};};if _becf ._dca ._bae {if _adcd :=_dcce .ReadProperty (&_becf ._ebca ._acec );_adcd !=nil {return _adcd ;};};if _becf ._dca ._bcab {if _bdb :=_dcce .ReadProperty (&_becf ._ebca ._dgda );_bdb !=nil {return _bdb ;};};if _becf ._dca ._ffea {if _ece :=_dcce .ReadProperty (&_becf ._ebca ._gbag );
_ece !=nil {return _ece ;};};if _becf ._dca ._gea {if _abd :=_dcce .ReadProperty (&_becf ._ebca ._beaad );_abd !=nil {return _abd ;};};if _becf ._dca ._gccbe {var _bgca uint32 ;if _dcbd :=_dcce .ReadProperty (&_bgca );_dcbd !=nil {return _dcbd ;};_becf ._ebca ._bbc ,_becf ._ebca ._afee =_aff (_bgca );
};if _becf ._dca ._ace {var _def uint32 ;if _beeg :=_dcce .ReadProperty (&_def );_beeg !=nil {return _beeg ;};_becf ._ebca ._bgc ,_becf ._ebca ._bcag =_aff (_def );};if _becf ._dca ._ebe {if _dcda :=_dcce .ReadProperty (&_becf ._ebca ._debd );_dcda !=nil {return _dcda ;
};};if _becf ._dca ._gafa {if _dgcd :=_dcce .ReadProperty (&_becf ._ebca ._ddd );_dgcd !=nil {return _dgcd ;};};if _becf ._dca ._dafc {if _gcga :=_dcce .ReadProperty (&_becf ._ebca ._dbdf );_gcga !=nil {return _gcga ;};};if _becf ._dca ._bdac {if _bdg :=_dcce .ReadProperty (&_becf ._ebca ._gfe );
_bdg !=nil {return _bdg ;};};if _becf ._dca ._cbcf {if _acdf :=_dcce .ReadProperty (&_becf ._ebca ._caea );_acdf !=nil {return _acdf ;};};if _becf ._dca ._eac {if _cdbg :=_dcce .ReadProperty (&_becf ._ebca ._dfdc );_cdbg !=nil {return _cdbg ;};};if _becf ._dca ._dccd {var _bgff uint32 ;
if _cbbb :=_dcce .ReadProperty (&_bgff );_cbbb !=nil {return _cbbb ;};_becf ._ebca ._ffcf ,_becf ._ebca ._aced =_aff (_bgff );};return nil ;};

// GetPosition gets a button position value.
func (_agfe *ScrollBarControl )GetPosition ()int32 {return _agfe ._cad ._fgba };

// SetForeColor sets a button text color value from a system palette for a commandButton control.
func (_cef *CommandButtonControl )SetForeColor (foreColor uint32 ){_cef ._baac ._ef =true ;_cef ._bef ._ebc =foreColor ;};

// GetForeColor gets a button text color value for a system palette from a commandButton control.
func (_ga *CommandButtonControl )GetForeColor ()uint32 {return _ga ._bef ._ebc };const (FmPictureAlignmentTopLeft FmPictureAlignment =iota ;FmPictureAlignmentTopRight ;FmPictureAlignmentCenter ;FmPictureAlignmentBottomLeft ;FmPictureAlignmentBottomRight ;
);const _bcg uint32 =0x0000746C;type morphDataColumnInfoDataBlock struct{};func (_gdd *controlBase )getPictureBytes ()[]byte {return _gdd ._fccd ._fffa .getStdPictureBytes ()};func (_acgb *ImageControl )readDataBlock (_ccf *_dg .Reader )error {_acgb ._ec =&imageDataBlock {};
if _acgb ._gcd ._eafd {if _edd :=_ccf .ReadProperty (&_acgb ._ec ._agdf );_edd !=nil {return _edd ;};};if _acgb ._gcd ._gfa {if _gcedf :=_ccf .ReadProperty (&_acgb ._ec ._dbcb );_gcedf !=nil {return _gcedf ;};};if _acgb ._gcd ._gaa {if _dcc :=_ccf .ReadProperty (&_acgb ._ec ._fae );
_dcc !=nil {return _dcc ;};};if _acgb ._gcd ._bea {if _caa :=_ccf .ReadProperty (&_acgb ._ec ._aedb );_caa !=nil {return _caa ;};};if _acgb ._gcd ._dade {if _ffeg :=_ccf .ReadProperty (&_acgb ._ec ._gcge );_ffeg !=nil {return _ffeg ;};};if _acgb ._gcd ._bgfc {if _bbbe :=_ccf .ReadProperty (&_acgb ._ec ._efee );
_bbbe !=nil {return _bbbe ;};};if _acgb ._gcd ._fff {if _bfbb :=_ccf .ReadProperty (&_acgb ._ec ._cbd );_bfbb !=nil {return _bfbb ;};};if _acgb ._gcd ._dbba {if _faa :=_ccf .ReadProperty (&_acgb ._ec ._aeg );_faa !=nil {return _faa ;};};if _acgb ._gcd ._eae {if _bba :=_ccf .ReadProperty (&_acgb ._ec ._gbd );
_bba !=nil {return _bba ;};};if _acgb ._gcd ._faf {if _gbbg :=_ccf .ReadProperty (&_acgb ._ec ._aadg );_gbbg !=nil {return _gbbg ;};};return nil ;};

// GetWidth returns width of the morphDataControl in HIMETRIC (0.01mm)
func (_bebd *morphDataControl )GetWidth ()uint32 {return _bebd ._gef ._eff };