//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package hyperlinkcolor ;import (_cf "encoding/xml";_ce "fmt";_a "github.com/unidoc/unioffice/v2";);type HlinkClr struct{CT_HyperlinkColor };const (ST_HyperlinkColorUnset ST_HyperlinkColor =0;ST_HyperlinkColorHlink ST_HyperlinkColor =1;ST_HyperlinkColorTx ST_HyperlinkColor =2;
);func (_ffe ST_HyperlinkColor )MarshalXML (e *_cf .Encoder ,start _cf .StartElement )error {return e .EncodeElement (_ffe .String (),start );};func NewCT_HyperlinkColor ()*CT_HyperlinkColor {_b :=&CT_HyperlinkColor {};_b .ValAttr =ST_HyperlinkColor (1);
return _b ;};func (_ag *CT_HyperlinkColor )MarshalXML (e *_cf .Encoder ,start _cf .StartElement )error {_ad ,_ab :=_ag .ValAttr .MarshalXMLAttr (_cf .Name {Local :"\u0076\u0061\u006c"});if _ab !=nil {return _ab ;};start .Attr =append (start .Attr ,_ad );
e .EncodeToken (start );e .EncodeToken (_cf .EndElement {Name :start .Name });return nil ;};

// ValidateWithPath validates the CT_HyperlinkColor and its children, prefixing error messages with path
func (_ac *CT_HyperlinkColor )ValidateWithPath (path string )error {if _ac .ValAttr ==ST_HyperlinkColorUnset {return _ce .Errorf ("\u0025\u0073\u002fV\u0061\u006c\u0041\u0074t\u0072\u0020\u0069\u0073\u0020\u0061\u0020m\u0061\u006e\u0064\u0061\u0074\u006f\u0072\u0079\u0020\u0066\u0069\u0065\u006c\u0064",path );
};if _abf :=_ac .ValAttr .ValidateWithPath (path +"\u002f\u0056\u0061\u006c\u0041\u0074\u0074\u0072");_abf !=nil {return _abf ;};return nil ;};type ST_HyperlinkColor byte ;func (_def ST_HyperlinkColor )ValidateWithPath (path string )error {switch _def {case 0,1,2:default:return _ce .Errorf ("\u0025s\u003a\u0020\u006f\u0075t\u0020\u006f\u0066\u0020\u0072a\u006eg\u0065 \u0076\u0061\u006c\u0075\u0065\u0020\u0025d",path ,int (_def ));
};return nil ;};func (_ega *ST_HyperlinkColor )UnmarshalXML (d *_cf .Decoder ,start _cf .StartElement )error {_cfg ,_fgf :=d .Token ();if _fgf !=nil {return _fgf ;};if _fc ,_acb :=_cfg .(_cf .EndElement );_acb &&_fc .Name ==start .Name {*_ega =1;return nil ;
};if _af ,_gf :=_cfg .(_cf .CharData );!_gf {return _ce .Errorf ("\u0065\u0078\u0070\u0065\u0063\u0074\u0065\u0064\u0020\u0063\u0068a\u0072\u0020\u0064\u0061\u0074\u0061\u002c\u0020\u0067\u006ft\u0020\u0025\u0054",_cfg );}else {switch string (_af ){case "":*_ega =0;
case "\u0068\u006c\u0069n\u006b":*_ega =1;case "\u0074\u0078":*_ega =2;};};_cfg ,_fgf =d .Token ();if _fgf !=nil {return _fgf ;};if _gff ,_abc :=_cfg .(_cf .EndElement );_abc &&_gff .Name ==start .Name {return nil ;};return _ce .Errorf ("\u0065\u0078\u0070\u0065c\u0074\u0065\u0064\u0020\u0065\u006e\u0064\u0020\u0065\u006ce\u006de\u006e\u0074\u002c\u0020\u0067\u006f\u0074 \u0025\u0076",_cfg );
};func (_bdd ST_HyperlinkColor )String ()string {switch _bdd {case 0:return "";case 1:return "\u0068\u006c\u0069n\u006b";case 2:return "\u0074\u0078";};return "";};func (_g *HlinkClr )MarshalXML (e *_cf .Encoder ,start _cf .StartElement )error {start .Attr =append (start .Attr ,_cf .Attr {Name :_cf .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068t\u0074\u0070\u003a\u002f\u002f\u0073\u0063he\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d/\u006f\u0066\u0066i\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0038\u002fh\u0079\u0070er\u006c\u0069\u006ek\u0063\u006f\u006c\u006f\u0072"});
start .Attr =append (start .Attr ,_cf .Attr {Name :_cf .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_cf .Attr {Name :_cf .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0068\u006c\u0069\u006e\u006b\u0043\u006c\u0072";return _g .CT_HyperlinkColor .MarshalXML (e ,start );};func (_de ST_HyperlinkColor )Validate ()error {return _de .ValidateWithPath ("")};func (_e *CT_HyperlinkColor )UnmarshalXML (d *_cf .Decoder ,start _cf .StartElement )error {_e .ValAttr =ST_HyperlinkColor (1);
for _ ,_d :=range start .Attr {if _d .Name .Local =="\u0076\u0061\u006c"{_e .ValAttr .UnmarshalXMLAttr (_d );continue ;};};for {_bf ,_eg :=d .Token ();if _eg !=nil {return _ce .Errorf ("\u0070\u0061r\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005f\u0048\u0079\u0070\u0065\u0072\u006c\u0069\u006e\u006b\u0043\u006f\u006c\u006f\u0072: \u0025\u0073",_eg );
};if _db ,_dg :=_bf .(_cf .EndElement );_dg &&_db .Name ==start .Name {break ;};};return nil ;};func (_acf ST_HyperlinkColor )MarshalXMLAttr (name _cf .Name )(_cf .Attr ,error ){_gg :=_cf .Attr {};_gg .Name =name ;switch _acf {case ST_HyperlinkColorUnset :_gg .Value ="";
case ST_HyperlinkColorHlink :_gg .Value ="\u0068\u006c\u0069n\u006b";case ST_HyperlinkColorTx :_gg .Value ="\u0074\u0078";};return _gg ,nil ;};type CT_HyperlinkColor struct{ValAttr ST_HyperlinkColor ;};

// ValidateWithPath validates the HlinkClr and its children, prefixing error messages with path
func (_bfg *HlinkClr )ValidateWithPath (path string )error {if _fba :=_bfg .CT_HyperlinkColor .ValidateWithPath (path );_fba !=nil {return _fba ;};return nil ;};func (_agf *ST_HyperlinkColor )UnmarshalXMLAttr (attr _cf .Attr )error {switch attr .Value {case "":*_agf =0;
case "\u0068\u006c\u0069n\u006b":*_agf =1;case "\u0074\u0078":*_agf =2;};return nil ;};

// Validate validates the CT_HyperlinkColor and its children
func (_cg *CT_HyperlinkColor )Validate ()error {return _cg .ValidateWithPath ("\u0043\u0054\u005f\u0048\u0079\u0070\u0065\u0072\u006c\u0069\u006e\u006bC\u006f\u006c\u006f\u0072");};func (_ff *HlinkClr )UnmarshalXML (d *_cf .Decoder ,start _cf .StartElement )error {_ff .CT_HyperlinkColor =*NewCT_HyperlinkColor ();
for _ ,_cc :=range start .Attr {if _cc .Name .Local =="\u0076\u0061\u006c"{_ff .ValAttr .UnmarshalXMLAttr (_cc );continue ;};};for {_df ,_fb :=d .Token ();if _fb !=nil {return _ce .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0048\u006c\u0069n\u006b\u0043\u006c\u0072: \u0025\u0073",_fb );
};if _eb ,_dgg :=_df .(_cf .EndElement );_dgg &&_eb .Name ==start .Name {break ;};};return nil ;};func NewHlinkClr ()*HlinkClr {_fg :=&HlinkClr {};_fg .CT_HyperlinkColor =*NewCT_HyperlinkColor ();return _fg ;};

// Validate validates the HlinkClr and its children
func (_bd *HlinkClr )Validate ()error {return _bd .ValidateWithPath ("\u0048\u006c\u0069\u006e\u006b\u0043\u006c\u0072");};func init (){_a .RegisterConstructor ("\u0068t\u0074\u0070\u003a\u002f\u002f\u0073\u0063he\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d/\u006f\u0066\u0066i\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0038\u002fh\u0079\u0070er\u006c\u0069\u006ek\u0063\u006f\u006c\u006f\u0072","\u0043\u0054\u005f\u0048\u0079\u0070\u0065\u0072\u006c\u0069\u006e\u006bC\u006f\u006c\u006f\u0072",NewCT_HyperlinkColor );
_a .RegisterConstructor ("\u0068t\u0074\u0070\u003a\u002f\u002f\u0073\u0063he\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d/\u006f\u0066\u0066i\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0038\u002fh\u0079\u0070er\u006c\u0069\u006ek\u0063\u006f\u006c\u006f\u0072","\u0068\u006c\u0069\u006e\u006b\u0043\u006c\u0072",NewHlinkClr );
};