//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package sort ;import (_e "regexp";_ag "sort";_c "strconv";);func MergeSort (array []float64 )[]float64 {if len (array )<=1{_cg :=make ([]float64 ,len (array ));copy (_cg ,array );return _cg ;};_ed :=len (array )/2;_f :=MergeSort (array [:_ed ]);_fa :=MergeSort (array [_ed :]);
_g :=make ([]float64 ,len (array ));_fc :=0;_cc :=0;_gb :=0;for _cc < len (_f )&&_gb < len (_fa ){if _f [_cc ]<=_fa [_gb ]{_g [_fc ]=_f [_cc ];_cc ++;}else {_g [_fc ]=_fa [_gb ];_gb ++;};_fc ++;};for _cc < len (_f ){_g [_fc ]=_f [_cc ];_cc ++;_fc ++;};
for _gb < len (_fa ){_g [_fc ]=_fa [_gb ];_gb ++;_fc ++;};return _g ;};var _fd =_e .MustCompile ("\u0028\\\u0064\u002b\u007c\u005c\u0044\u002b)");type stringSlice []string ;func (_d stringSlice )Len ()int {return len (_d )};func _edb (_gc string )[]string {return _fd .FindAllString (_gc ,-1)};
func NaturalSort (l []string ){_ag .Sort (stringSlice (l ))};func (_ca stringSlice )Swap (a ,b int ){_ca [a ],_ca [b ]=_ca [b ],_ca [a ]};func (_b stringSlice )Less (a ,b int )bool {return NaturalCompare (_b [a ],_b [b ])};func NaturalCompare (a ,b string )bool {_faa :=_edb (a );
_da :=_edb (b );_ea :=len (_faa );_ba :=len (_da );for _bd :=range _faa {if _bd >=_ba {return false ;};_fdg ,_gd :=_c .Atoi (_faa [_bd ]);_gf ,_bg :=_c .Atoi (_da [_bd ]);if _gd ==nil &&_bg ==nil {if _fdg ==_gf {if _bd ==_ea -1{return true ;}else if _bd ==_ba -1{return false ;
};continue ;};return _fdg < _gf ;};if _faa [_bd ]==_da [_bd ]{if _bd ==_ea -1{return true ;}else if _bd ==_ba -1{return false ;};continue ;};return _faa [_bd ]< _da [_bd ];};return false ;};