//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package symex ;import (_g "encoding/xml";_a "fmt";_ad "github.com/unidoc/unioffice/v2";);func (_af *CT_SymEx )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {if _af .FontAttr !=nil {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0073\u003a\u0066\u006f\u006e\u0074"},Value :_a .Sprintf ("\u0025\u0076",*_af .FontAttr )});
};if _af .CharAttr !=nil {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0073\u003a\u0063\u0068\u0061\u0072"},Value :_a .Sprintf ("\u0025\u0076",*_af .CharAttr )});};e .EncodeToken (start );e .EncodeToken (_g .EndElement {Name :start .Name });
return nil ;};

// Validate validates the CT_SymEx and its children
func (_ed *CT_SymEx )Validate ()error {return _ed .ValidateWithPath ("\u0043\u0054\u005f\u0053\u0079\u006d\u0045\u0078");};func (_bd *CT_SymEx )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {for _ ,_f :=range start .Attr {if _f .Name .Local =="\u0066\u006f\u006e\u0074"{_gf :=_f .Value ;
_bd .FontAttr =&_gf ;continue ;};if _f .Name .Local =="\u0063\u0068\u0061\u0072"{_e :=_f .Value ;_bd .CharAttr =&_e ;continue ;};};for {_ag ,_afd :=d .Token ();if _afd !=nil {return _a .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005fS\u0079\u006d\u0045\u0078: \u0025\u0073",_afd );
};if _dd ,_aca :=_ag .(_g .EndElement );_aca &&_dd .Name ==start .Name {break ;};};return nil ;};func NewSymEx ()*SymEx {_eg :=&SymEx {};_eg .CT_SymEx =*NewCT_SymEx ();return _eg };func (_c *SymEx )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0073:\u0073\u0079\u006d\u0045\u0078";return _c .CT_SymEx .MarshalXML (e ,start );};type SymEx struct{CT_SymEx };type CT_SymEx struct{FontAttr *string ;CharAttr *string ;};

// ValidateWithPath validates the SymEx and its children, prefixing error messages with path
func (_cfg *SymEx )ValidateWithPath (path string )error {if _cc :=_cfg .CT_SymEx .ValidateWithPath (path );_cc !=nil {return _cc ;};return nil ;};

// Validate validates the SymEx and its children
func (_daa *SymEx )Validate ()error {return _daa .ValidateWithPath ("\u0053\u0079\u006dE\u0078")};func NewCT_SymEx ()*CT_SymEx {_d :=&CT_SymEx {};return _d };func (_bf *SymEx )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {_bf .CT_SymEx =*NewCT_SymEx ();
for _ ,_ddg :=range start .Attr {if _ddg .Name .Local =="\u0066\u006f\u006e\u0074"{_da :=_ddg .Value ;_bf .FontAttr =&_da ;continue ;};if _ddg .Name .Local =="\u0063\u0068\u0061\u0072"{_df :=_ddg .Value ;_bf .CharAttr =&_df ;continue ;};};for {_gg ,_cf :=d .Token ();
if _cf !=nil {return _a .Errorf ("\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0053\u0079\u006d\u0045x\u003a\u0020\u0025\u0073",_cf );};if _ab ,_aa :=_gg .(_g .EndElement );_aa &&_ab .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the CT_SymEx and its children, prefixing error messages with path
func (_agc *CT_SymEx )ValidateWithPath (path string )error {return nil };func init (){_ad .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078","\u0043\u0054\u005f\u0053\u0079\u006d\u0045\u0078",NewCT_SymEx );
_ad .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078","\u0073\u0079\u006dE\u0078",NewSymEx );
};