//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package decorative ;import (_g "encoding/xml";_c "fmt";_a "github.com/unidoc/unioffice/v2";_d "strconv";);

// Validate validates the CT_Decorative and its children
func (_ad *CT_Decorative )Validate ()error {return _ad .ValidateWithPath ("\u0043\u0054\u005f\u0044\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065");};type Decorative struct{CT_Decorative };func (_dg *CT_Decorative )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {for _ ,_ef :=range start .Attr {if _ef .Name .Local =="\u0076\u0061\u006c"{_eg ,_f :=_d .ParseBool (_ef .Value );
if _f !=nil {return _f ;};_dg .ValAttr =&_eg ;continue ;};};for {_gf ,_ac :=d .Token ();if _ac !=nil {return _c .Errorf ("\u0070a\u0072\u0073\u0069\u006eg\u0020\u0043\u0054\u005f\u0044e\u0063o\u0072a\u0074\u0069\u0076\u0065\u003a\u0020\u0025s",_ac );};
if _ab ,_ff :=_gf .(_g .EndElement );_ff &&_ab .Name ==start .Name {break ;};};return nil ;};func (_be *Decorative )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0037\u002f\u0064\u0065c\u006f\u0072\u0061\u0074\u0069v\u0065"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0064\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065";return _be .CT_Decorative .MarshalXML (e ,start );};

// ValidateWithPath validates the CT_Decorative and its children, prefixing error messages with path
func (_de *CT_Decorative )ValidateWithPath (path string )error {return nil };

// Validate validates the Decorative and its children
func (_bd *Decorative )Validate ()error {return _bd .ValidateWithPath ("\u0044\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065");};

// ValidateWithPath validates the Decorative and its children, prefixing error messages with path
func (_fc *Decorative )ValidateWithPath (path string )error {if _gb :=_fc .CT_Decorative .ValidateWithPath (path );_gb !=nil {return _gb ;};return nil ;};func (_dc *Decorative )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {_dc .CT_Decorative =*NewCT_Decorative ();
for _ ,_bb :=range start .Attr {if _bb .Name .Local =="\u0076\u0061\u006c"{_acg ,_ce :=_d .ParseBool (_bb .Value );if _ce !=nil {return _ce ;};_dc .ValAttr =&_acg ;continue ;};};for {_db ,_eb :=d .Token ();if _eb !=nil {return _c .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0044\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065\u003a\u0020%\u0073",_eb );
};if _bc ,_ec :=_db .(_g .EndElement );_ec &&_bc .Name ==start .Name {break ;};};return nil ;};func (_b *CT_Decorative )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {if _b .ValAttr !=nil {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0076\u0061\u006c"},Value :_c .Sprintf ("\u0025\u0064",_ea (*_b .ValAttr ))});
};e .EncodeToken (start );e .EncodeToken (_g .EndElement {Name :start .Name });return nil ;};func _ea (_ag bool )uint8 {if _ag {return 1;};return 0;};func NewCT_Decorative ()*CT_Decorative {_cg :=&CT_Decorative {};return _cg };type CT_Decorative struct{ValAttr *bool ;
};func NewDecorative ()*Decorative {_ffd :=&Decorative {};_ffd .CT_Decorative =*NewCT_Decorative ();return _ffd ;};func init (){_a .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0037\u002f\u0064\u0065c\u006f\u0072\u0061\u0074\u0069v\u0065","\u0043\u0054\u005f\u0044\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065",NewCT_Decorative );
_a .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0037\u002f\u0064\u0065c\u006f\u0072\u0061\u0074\u0069v\u0065","\u0064\u0065\u0063\u006f\u0072\u0061\u0074\u0069\u0076\u0065",NewDecorative );
};