//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package contentblocks ;import (_d "github.com/unidoc/unioffice/v2/common/logger";_a "github.com/unidoc/unioffice/v2/schema/soo/wml";);func _c (_g []*_a .EG_ContentBlockContent ,_ca func (*_a .EG_ContentBlockContentChoice )bool ,_cd int )bool {if _cd > _dg {_d .Log .Debug ("\u0043o\u006e\u0074e\u006e\u0074\u0042\u006co\u0063\u006b\u0020i\u0074\u0065\u0072\u0061\u0074\u006f\u0072\u0020\u006dax\u0020\u0064\u0065p\u0074\u0068 \u0065\u0078\u0063\u0065\u0065\u0064e\u0064\u003a \u0025\u0064",_cd );
return true ;};for _ ,_ae :=range _g {if _ae ==nil ||_ae .ContentBlockContentChoice ==nil {continue ;};_ee :=_ae .ContentBlockContentChoice ;if _ag :=_ee .Sdt ;_ag !=nil &&_ag .SdtContent !=nil {if !_c (_ag .SdtContent .EG_ContentBlockContent ,_ca ,_cd +1){return false ;
};continue ;};if _bad :=_ee .CustomXml ;_bad !=nil {if !_c (_bad .EG_ContentBlockContent ,_ca ,_cd +1){return false ;};continue ;};if !_ca (_ee ){return false ;};};return true ;};const _dg =50;func Unwrap (cbcs []*_a .EG_ContentBlockContent )[]*_a .EG_ContentBlockContentChoice {var _cf []*_a .EG_ContentBlockContentChoice ;
for _ef :=range Iterate (cbcs ){_cf =append (_cf ,_ef );};return _cf ;};func ForEachParagraph (cbcs []*_a .EG_ContentBlockContent ,fn func (*_a .CT_P )bool ){for _fe :=range Iterate (cbcs ){for _ ,_ecd :=range _fe .P {if !fn (_ecd ){return ;};};};};func HasTables (cbcs []*_a .EG_ContentBlockContent )bool {for _f :=range Iterate (cbcs ){if len (_f .Tbl )> 0{return true ;
};};return false ;};func Iterate (cbcs []*_a .EG_ContentBlockContent )func (_df func (*_a .EG_ContentBlockContentChoice )bool ){return func (_ba func (*_a .EG_ContentBlockContentChoice )bool ){_c (cbcs ,_ba ,0)};};func HasParagraphs (cbcs []*_a .EG_ContentBlockContent )bool {for _gb :=range Iterate (cbcs ){if len (_gb .P )> 0{return true ;
};};return false ;};func CountTables (cbcs []*_a .EG_ContentBlockContent )int {_bb :=0;for _ec :=range Iterate (cbcs ){_bb +=len (_ec .Tbl );};return _bb ;};func CountParagraphs (cbcs []*_a .EG_ContentBlockContent )int {_eb :=0;for _dge :=range Iterate (cbcs ){_eb +=len (_dge .P );
};return _eb ;};func ForEachTable (cbcs []*_a .EG_ContentBlockContent ,fn func (*_a .CT_Tbl )bool ){for _dd :=range Iterate (cbcs ){for _ ,_fg :=range _dd .Tbl {if !fn (_fg ){return ;};};};};