//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package diagram ;import (_a "encoding/xml";_af "fmt";_f "github.com/unidoc/unioffice/v2";_b "github.com/unidoc/unioffice/v2/schema/soo/dml";);

// ValidateWithPath validates the LstStyle and its children, prefixing error messages with path
func (_bgc *LstStyle )ValidateWithPath (path string )error {if _ca :=_bgc .CT_TextListStyle .ValidateWithPath (path );_ca !=nil {return _ca ;};return nil ;};func (_cb *SpPr )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_cb .CT_ShapeProperties =*_b .NewCT_ShapeProperties ();
for {_ec ,_ecg :=d .Token ();if _ecg !=nil {return _af .Errorf ("\u0070\u0061r\u0073\u0069\u006eg\u0020\u0053\u0070\u0050\u0072\u003a\u0020\u0025\u0073",_ecg );};if _ff ,_fa :=_ec .(_a .EndElement );_fa &&_ff .Name ==start .Name {break ;};};return nil ;
};func (_cc *SpPr )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0031\u0032/\u0064\u0069\u0061\u0067\u0072a\u006d"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0073\u0070\u0050\u0072";return _cc .CT_ShapeProperties .MarshalXML (e ,start );};func NewLstStyle ()*LstStyle {_be :=&LstStyle {};_be .CT_TextListStyle =*_b .NewCT_TextListStyle ();return _be ;};func NewSpPr ()*SpPr {_eb :=&SpPr {};
_eb .CT_ShapeProperties =*_b .NewCT_ShapeProperties ();return _eb ;};func (_bg *LstStyle )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_bg .CT_TextListStyle =*_b .NewCT_TextListStyle ();for {_fe ,_g :=d .Token ();if _g !=nil {return _af .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u004c\u0073\u0074S\u0074\u0079\u006c\u0065: \u0025\u0073",_g );
};if _bgb ,_c :=_fe .(_a .EndElement );_c &&_bgb .Name ==start .Name {break ;};};return nil ;};

// Validate validates the SpPr and its children
func (_bgbc *SpPr )Validate ()error {return _bgbc .ValidateWithPath ("\u0053\u0070\u0050\u0072")};

// Validate validates the LstStyle and its children
func (_bgf *LstStyle )Validate ()error {return _bgf .ValidateWithPath ("\u004c\u0073\u0074\u0053\u0074\u0079\u006c\u0065");};type LstStyle struct{_b .CT_TextListStyle };type SpPr struct{_b .CT_ShapeProperties };

// ValidateWithPath validates the SpPr and its children, prefixing error messages with path
func (_ebc *SpPr )ValidateWithPath (path string )error {if _dd :=_ebc .CT_ShapeProperties .ValidateWithPath (path );_dd !=nil {return _dd ;};return nil ;};func (_d *LstStyle )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0031\u0032/\u0064\u0069\u0061\u0067\u0072a\u006d"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u006c\u0073\u0074\u0053\u0074\u0079\u006c\u0065";return _d .CT_TextListStyle .MarshalXML (e ,start );};func init (){_f .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0031\u0032/\u0064\u0069\u0061\u0067\u0072a\u006d","\u0073\u0070\u0050\u0072",NewSpPr );
_f .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0036\u002f\u0031\u0032/\u0064\u0069\u0061\u0067\u0072a\u006d","\u006c\u0073\u0074\u0053\u0074\u0079\u006c\u0065",NewLstStyle );
};