//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package wildcard ;func _dae (_gd ,_aea []rune ,_ce int )int {for len (_aea )> 0{switch _aea [0]{default:if len (_gd )==0{return -1;};if _gd [0]!=_aea [0]{return _dae (_gd [1:],_aea ,_ce +1);};case '?':if len (_gd )==0{return -1;};case '*':if len (_gd )==0{return -1;
};_ge :=_dae (_gd ,_aea [1:],_ce );if _ge !=-1{return _ce ;}else {_ge =_dae (_gd [1:],_aea ,_ce );if _ge !=-1{return _ce ;}else {return -1;};};};_gd =_gd [1:];_aea =_aea [1:];};return _ce ;};func MatchSimple (pattern ,name string )bool {if pattern ==""{return name ==pattern ;
};if pattern =="\u002a"{return true ;};_e :=make ([]rune ,0,len (name ));_bd :=make ([]rune ,0,len (pattern ));for _ ,_db :=range name {_e =append (_e ,_db );};for _ ,_df :=range pattern {_bd =append (_bd ,_df );};_be :=true ;return _ff (_e ,_bd ,_be );
};func _ff (_aeg ,_dc []rune ,_ac bool )bool {for len (_dc )> 0{switch _dc [0]{default:if len (_aeg )==0||_aeg [0]!=_dc [0]{return false ;};case '?':if len (_aeg )==0&&!_ac {return false ;};case '*':return _ff (_aeg ,_dc [1:],_ac )||(len (_aeg )> 0&&_ff (_aeg [1:],_dc ,_ac ));
};_aeg =_aeg [1:];_dc =_dc [1:];};return len (_aeg )==0&&len (_dc )==0;};func Match (pattern ,name string )(_f bool ){if pattern ==""{return name ==pattern ;};if pattern =="\u002a"{return true ;};_fb :=make ([]rune ,0,len (name ));_fe :=make ([]rune ,0,len (pattern ));
for _ ,_a :=range name {_fb =append (_fb ,_a );};for _ ,_ae :=range pattern {_fe =append (_fe ,_ae );};_g :=false ;return _ff (_fb ,_fe ,_g );};func Index (pattern ,name string )(_gc int ){if pattern ==""||pattern =="\u002a"{return 0;};_dd :=make ([]rune ,0,len (name ));
_da :=make ([]rune ,0,len (pattern ));for _ ,_eg :=range name {_dd =append (_dd ,_eg );};for _ ,_gg :=range pattern {_da =append (_da ,_gg );};return _dae (_dd ,_da ,0);};