//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package oembed ;import (_e "encoding/xml";_af "fmt";_b "github.com/unidoc/unioffice/v2";_c "strconv";);type CT_OEmbed struct{OEmbedUrlAttr string ;MediaTypeAttr string ;PicLocksAutoForOEmbedAttr *bool ;};

// ValidateWithPath validates the Oembed and its children, prefixing error messages with path
func (_ce *Oembed )ValidateWithPath (path string )error {if _gcg :=_ce .CT_OEmbed .ValidateWithPath (path );_gcg !=nil {return _gcg ;};return nil ;};

// Validate validates the Oembed and its children
func (_eg *Oembed )Validate ()error {return _eg .ValidateWithPath ("\u004f\u0065\u006d\u0062\u0065\u0064");};func NewCT_OEmbed ()*CT_OEmbed {_f :=&CT_OEmbed {};return _f };func (_afdf *Oembed )MarshalXML (e *_e .Encoder ,start _e .StartElement )error {start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0032\u0030\u002f\u006f\u0065\u006d\u0062\u0065\u0064"});
start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u006f\u0065\u006d\u0062\u0065\u0064";return _afdf .CT_OEmbed .MarshalXML (e ,start );};func (_gcb *Oembed )UnmarshalXML (d *_e .Decoder ,start _e .StartElement )error {_gcb .CT_OEmbed =*NewCT_OEmbed ();for _ ,_dg :=range start .Attr {if _dg .Name .Local =="\u006fE\u006d\u0062\u0065\u0064\u0055\u0072l"{_df :=_dg .Value ;
_gcb .OEmbedUrlAttr =_df ;continue ;};if _dg .Name .Local =="\u006de\u0064\u0069\u0061\u0054\u0079\u0070e"{_aec :=_dg .Value ;_gcb .MediaTypeAttr =_aec ;continue ;};if _dg .Name .Local =="p\u0069\u0063\u004c\u006fck\u0073A\u0075\u0074\u006f\u0046\u006fr\u004f\u0045\u006d\u0062\u0065\u0064"{_faf ,_be :=_c .ParseBool (_dg .Value );
if _be !=nil {return _be ;};_gcb .PicLocksAutoForOEmbedAttr =&_faf ;continue ;};};for {_ca ,_ge :=d .Token ();if _ge !=nil {return _af .Errorf ("\u0070a\u0072s\u0069\u006e\u0067\u0020\u004fe\u006d\u0062e\u0064\u003a\u0020\u0025\u0073",_ge );};if _aef ,_aba :=_ca .(_e .EndElement );
_aba &&_aef .Name ==start .Name {break ;};};return nil ;};func _ga (_dd bool )uint8 {if _dd {return 1;};return 0;};func (_g *CT_OEmbed )UnmarshalXML (d *_e .Decoder ,start _e .StartElement )error {for _ ,_ab :=range start .Attr {if _ab .Name .Local =="\u006fE\u006d\u0062\u0065\u0064\u0055\u0072l"{_fe :=_ab .Value ;
_g .OEmbedUrlAttr =_fe ;continue ;};if _ab .Name .Local =="\u006de\u0064\u0069\u0061\u0054\u0079\u0070e"{_fb :=_ab .Value ;_g .MediaTypeAttr =_fb ;continue ;};if _ab .Name .Local =="p\u0069\u0063\u004c\u006fck\u0073A\u0075\u0074\u006f\u0046\u006fr\u004f\u0045\u006d\u0062\u0065\u0064"{_afd ,_afc :=_c .ParseBool (_ab .Value );
if _afc !=nil {return _afc ;};_g .PicLocksAutoForOEmbedAttr =&_afd ;continue ;};};for {_d ,_gc :=d .Token ();if _gc !=nil {return _af .Errorf ("p\u0061\u0072\u0073\u0069ng\u0020C\u0054\u005f\u004f\u0045\u006db\u0065\u0064\u003a\u0020\u0025\u0073",_gc );
};if _ae ,_ed :=_d .(_e .EndElement );_ed &&_ae .Name ==start .Name {break ;};};return nil ;};func NewOembed ()*Oembed {_aa :=&Oembed {};_aa .CT_OEmbed =*NewCT_OEmbed ();return _aa };

// Validate validates the CT_OEmbed and its children
func (_cd *CT_OEmbed )Validate ()error {return _cd .ValidateWithPath ("\u0043T\u005f\u004f\u0045\u006d\u0062\u0065d");};

// ValidateWithPath validates the CT_OEmbed and its children, prefixing error messages with path
func (_abb *CT_OEmbed )ValidateWithPath (path string )error {return nil };type Oembed struct{CT_OEmbed };func (_fa *CT_OEmbed )MarshalXML (e *_e .Encoder ,start _e .StartElement )error {start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u006fE\u006d\u0062\u0065\u0064\u0055\u0072l"},Value :_af .Sprintf ("\u0025\u0076",_fa .OEmbedUrlAttr )});
start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u006de\u0064\u0069\u0061\u0054\u0079\u0070e"},Value :_af .Sprintf ("\u0025\u0076",_fa .MediaTypeAttr )});if _fa .PicLocksAutoForOEmbedAttr !=nil {start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"p\u0069\u0063\u004c\u006fck\u0073A\u0075\u0074\u006f\u0046\u006fr\u004f\u0045\u006d\u0062\u0065\u0064"},Value :_af .Sprintf ("\u0025\u0064",_ga (*_fa .PicLocksAutoForOEmbedAttr ))});
};e .EncodeToken (start );e .EncodeToken (_e .EndElement {Name :start .Name });return nil ;};func init (){_b .RegisterConstructor ("\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0032\u0030\u002f\u006f\u0065\u006d\u0062\u0065\u0064","\u0043T\u005f\u004f\u0045\u006d\u0062\u0065d",NewCT_OEmbed );
_b .RegisterConstructor ("\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0032\u0030\u002f\u006f\u0065\u006d\u0062\u0065\u0064","\u006f\u0065\u006d\u0062\u0065\u0064",NewOembed );
};