//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package imageformula ;import (_b "encoding/xml";_a "fmt";_d "github.com/unidoc/unioffice/v2";);

// ValidateWithPath validates the ImageFormula and its children, prefixing error messages with path
func (_bd *ImageFormula )ValidateWithPath (path string )error {if _bg :=_bd .CT_ImageFormula .ValidateWithPath (path );_bg !=nil {return _bg ;};return nil ;};func (_dg *ImageFormula )UnmarshalXML (d *_b .Decoder ,start _b .StartElement )error {_dg .CT_ImageFormula =*NewCT_ImageFormula ();
for _ ,_dd :=range start .Attr {if _dd .Name .Local =="\u0066o\u0072\u006d\u0075\u006c\u0061"{_ga :=_dd .Value ;_dg .FormulaAttr =&_ga ;continue ;};};for {_gf ,_ee :=d .Token ();if _ee !=nil {return _a .Errorf ("\u0070a\u0072\u0073\u0069\u006e\u0067\u0020\u0049\u006d\u0061\u0067\u0065F\u006f\u0072\u006d\u0075\u006c\u0061\u003a\u0020\u0025\u0073",_ee );
};if _gag ,_fa :=_gf .(_b .EndElement );_fa &&_gag .Name ==start .Name {break ;};};return nil ;};

// Validate validates the CT_ImageFormula and its children
func (_agd *CT_ImageFormula )Validate ()error {return _agd .ValidateWithPath ("\u0043T\u005fI\u006d\u0061\u0067\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061");};func (_bb *CT_ImageFormula )MarshalXML (e *_b .Encoder ,start _b .StartElement )error {if _bb .FormulaAttr !=nil {start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0066o\u0072\u006d\u0075\u006c\u0061"},Value :_a .Sprintf ("\u0025\u0076",*_bb .FormulaAttr )});
};e .EncodeToken (start );e .EncodeToken (_b .EndElement {Name :start .Name });return nil ;};type CT_ImageFormula struct{FormulaAttr *string ;};

// ValidateWithPath validates the CT_ImageFormula and its children, prefixing error messages with path
func (_ed *CT_ImageFormula )ValidateWithPath (path string )error {return nil };func (_dc *CT_ImageFormula )UnmarshalXML (d *_b .Decoder ,start _b .StartElement )error {for _ ,_fb :=range start .Attr {if _fb .Name .Local =="\u0066o\u0072\u006d\u0075\u006c\u0061"{_e :=_fb .Value ;
_dc .FormulaAttr =&_e ;continue ;};};for {_g ,_eb :=d .Token ();if _eb !=nil {return _a .Errorf ("p\u0061\u0072\u0073\u0069\u006e\u0067 \u0043\u0054\u005f\u0049\u006d\u0061\u0067\u0065\u0046o\u0072\u006d\u0075l\u0061:\u0020\u0025\u0073",_eb );};if _bbg ,_ag :=_g .(_b .EndElement );
_ag &&_bbg .Name ==start .Name {break ;};};return nil ;};type ImageFormula struct{CT_ImageFormula };

// Validate validates the ImageFormula and its children
func (_cc *ImageFormula )Validate ()error {return _cc .ValidateWithPath ("\u0049\u006d\u0061g\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061");};func NewImageFormula ()*ImageFormula {_ba :=&ImageFormula {};_ba .CT_ImageFormula =*NewCT_ImageFormula ();
return _ba ;};func (_aeg *ImageFormula )MarshalXML (e *_b .Encoder ,start _b .StartElement )error {start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"h\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006fm\u002fo\u0066\u0066\u0069\u0063e\u002f\u0064r\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0032\u002f\u0069\u006d\u0061\u0067\u0065\u0066\u006f\u0072\u006d\u0075\u006c\u0061"});
start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_b .Attr {Name :_b .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0069\u006d\u0061g\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061";return _aeg .CT_ImageFormula .MarshalXML (e ,start );};func NewCT_ImageFormula ()*CT_ImageFormula {_ae :=&CT_ImageFormula {};return _ae };func init (){_d .RegisterConstructor ("h\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006fm\u002fo\u0066\u0066\u0069\u0063e\u002f\u0064r\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0032\u002f\u0069\u006d\u0061\u0067\u0065\u0066\u006f\u0072\u006d\u0075\u006c\u0061","\u0043T\u005fI\u006d\u0061\u0067\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061",NewCT_ImageFormula );
_d .RegisterConstructor ("h\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006fm\u002fo\u0066\u0066\u0069\u0063e\u002f\u0064r\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0032\u0032\u002f\u0069\u006d\u0061\u0067\u0065\u0066\u006f\u0072\u006d\u0075\u006c\u0061","\u0069\u006d\u0061g\u0065\u0046\u006f\u0072\u006d\u0075\u006c\u0061",NewImageFormula );
};