//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package cid ;import (_e "encoding/xml";_db "fmt";_dc "github.com/unidoc/unioffice/v2";_cf "github.com/unidoc/unioffice/v2/common/logger";_d "strconv";);

// Validate validates the CommentsIds and its children
func (_ec *CommentsIds )Validate ()error {return _ec .ValidateWithPath ("C\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073");};

// Validate validates the CT_CommentsIds and its children
func (_gf *CT_CommentsIds )Validate ()error {return _gf .ValidateWithPath ("\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073");};type CT_CommentId struct{ParaIdAttr string ;DurableIdAttr string ;};func (_ag *CommentsIds )MarshalXML (e *_e .Encoder ,start _e .StartElement )error {start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064"});
start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0063\u0069d"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064"});
start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0063i\u0064:\u0063\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073";return _ag .CT_CommentsIds .MarshalXML (e ,start );};

// Validate validates the CT_CommentId and its children
func (_dg *CT_CommentId )Validate ()error {return _dg .ValidateWithPath ("\u0043\u0054\u005fC\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064");};type CT_CommentsIds struct{CommentId []*CT_CommentId ;};

// ValidateWithPath validates the CommentsIds and its children, prefixing error messages with path
func (_gb *CommentsIds )ValidateWithPath (path string )error {if _agc :=_gb .CT_CommentsIds .ValidateWithPath (path );_agc !=nil {return _agc ;};return nil ;};

// ValidateWithPath validates the CT_CommentsIds and its children, prefixing error messages with path
func (_dcb *CT_CommentsIds )ValidateWithPath (path string )error {for _adc ,_af :=range _dcb .CommentId {if _feg :=_af .ValidateWithPath (_db .Sprintf ("\u0025\u0073/\u0043\u006f\u006dm\u0065\u006e\u0074\u0049\u0064\u005b\u0025\u0064\u005d",path ,_adc ));
_feg !=nil {return _feg ;};};return nil ;};func (_fe *CT_CommentsIds )MarshalXML (e *_e .Encoder ,start _e .StartElement )error {e .EncodeToken (start );if _fe .CommentId !=nil {_ddg :=_e .StartElement {Name :_e .Name {Local :"\u0063\u0069\u0064\u003a\u0063\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064"}};
for _ ,_eed :=range _fe .CommentId {e .EncodeElement (_eed ,_ddg );};};e .EncodeToken (_e .EndElement {Name :start .Name });return nil ;};func (_da *CT_CommentId )MarshalXML (e *_e .Encoder ,start _e .StartElement )error {start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0063\u0069\u0064\u003a\u0070\u0061\u0072\u0061\u0049\u0064"},Value :_db .Sprintf ("\u0025\u0076",_da .ParaIdAttr )});
start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0063\u0069\u0064\u003a\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064"},Value :_db .Sprintf ("\u0025\u0076",_da .DurableIdAttr )});e .EncodeToken (start );e .EncodeToken (_e .EndElement {Name :start .Name });
return nil ;};func NewDecimaldurableId ()*DecimaldurableId {_gfc :=&DecimaldurableId {};return _gfc };

// Validate validates the DecimaldurableId and its children
func (_agd *DecimaldurableId )Validate ()error {return _agd .ValidateWithPath ("\u0044\u0065c\u0069\u006d\u0061l\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064");};type DecimaldurableId struct{DurableIdAttr *int64 ;};func (_ab *DecimaldurableId )MarshalXML (e *_e .Encoder ,start _e .StartElement )error {if _ab .DurableIdAttr !=nil {start .Attr =append (start .Attr ,_e .Attr {Name :_e .Name {Local :"\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"},Value :_db .Sprintf ("\u0025\u0076",*_ab .DurableIdAttr )});
};start .Name .Local ="c\u0069d\u003a\u0064\u0065\u0063\u0069\u006d\u0061\u006cd\u0075\u0072\u0061\u0062le\u0049\u0064";return nil ;};func (_dba *CommentsIds )UnmarshalXML (d *_e .Decoder ,start _e .StartElement )error {_dba .CT_CommentsIds =*NewCT_CommentsIds ();
_eg :for {_caf ,_gg :=d .Token ();if _gg !=nil {return _gg ;};switch _eac :=_caf .(type ){case _e .StartElement :switch _eac .Name {case _e .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064",Local :"\u0063o\u006d\u006d\u0065\u006e\u0074\u0049d"}:_ed :=NewCT_CommentId ();
if _fad :=d .DecodeElement (_ed ,&_eac );_fad !=nil {return _fad ;};_dba .CommentId =append (_dba .CommentId ,_ed );default:_cf .Log .Debug ("\u0073\u006bi\u0070\u0070\u0069\u006e\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065\u0064\u0020\u0065\u006c\u0065\u006d\u0065\u006e\u0074\u0020\u006f\u006e\u0020\u0043\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073\u0020\u0025\u0076",_eac .Name );
if _cd :=d .Skip ();_cd !=nil {return _cd ;};};case _e .EndElement :break _eg ;case _e .CharData :};};return nil ;};func (_dbb *CT_CommentId )UnmarshalXML (d *_e .Decoder ,start _e .StartElement )error {for _ ,_fb :=range start .Attr {if _fb .Name .Local =="\u0070\u0061\u0072\u0061\u0049\u0064"{_a :=_fb .Value ;
_dbb .ParaIdAttr =_a ;continue ;};if _fb .Name .Local =="\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"{_fg :=_fb .Value ;_dbb .DurableIdAttr =_fg ;continue ;};};for {_ee ,_ef :=d .Token ();if _ef !=nil {return _db .Errorf ("\u0070a\u0072\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005f\u0043\u006fm\u006d\u0065\u006e\u0074\u0049\u0064\u003a\u0020\u0025\u0073",_ef );
};if _ad ,_fga :=_ee .(_e .EndElement );_fga &&_ad .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the CT_CommentId and its children, prefixing error messages with path
func (_add *CT_CommentId )ValidateWithPath (path string )error {return nil };func NewCT_CommentId ()*CT_CommentId {_f :=&CT_CommentId {};return _f };func NewCommentsIds ()*CommentsIds {_ea :=&CommentsIds {};_ea .CT_CommentsIds =*NewCT_CommentsIds ();return _ea ;
};type CommentsIds struct{CT_CommentsIds };func NewCT_CommentsIds ()*CT_CommentsIds {_ae :=&CT_CommentsIds {};return _ae };func (_g *CT_CommentsIds )UnmarshalXML (d *_e .Decoder ,start _e .StartElement )error {_ca :for {_ge ,_cg :=d .Token ();if _cg !=nil {return _cg ;
};switch _eef :=_ge .(type ){case _e .StartElement :switch _eef .Name {case _e .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064",Local :"\u0063o\u006d\u006d\u0065\u006e\u0074\u0049d"}:_gec :=NewCT_CommentId ();
if _cac :=d .DecodeElement (_gec ,&_eef );_cac !=nil {return _cac ;};_g .CommentId =append (_g .CommentId ,_gec );default:_cf .Log .Debug ("\u0073\u006b\u0069\u0070\u0070\u0069n\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065\u0064\u0020\u0065\u006c\u0065\u006d\u0065\u006et\u0020\u006f\u006e\u0020\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006e\u0074s\u0049d\u0073\u0020\u0025\u0076",_eef .Name );
if _fa :=d .Skip ();_fa !=nil {return _fa ;};};case _e .EndElement :break _ca ;case _e .CharData :};};return nil ;};func (_bd *DecimaldurableId )UnmarshalXML (d *_e .Decoder ,start _e .StartElement )error {for _ ,_egf :=range start .Attr {if _egf .Name .Local =="\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"{_cafg ,_gecg :=_d .ParseInt (_egf .Value ,10,64);
if _gecg !=nil {return _gecg ;};_bd .DurableIdAttr =&_cafg ;continue ;};};for {_ga ,_aea :=d .Token ();if _aea !=nil {return _db .Errorf ("\u0070\u0061\u0072\u0073i\u006e\u0067\u0020\u0044\u0065\u0063\u0069\u006d\u0061\u006cd\u0075r\u0061\u0062\u006c\u0065\u0049\u0064\u003a \u0025\u0073",_aea );
};if _cgg ,_efb :=_ga .(_e .EndElement );_efb &&_cgg .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the DecimaldurableId and its children, prefixing error messages with path
func (_agdd *DecimaldurableId )ValidateWithPath (path string )error {return nil };func init (){_dc .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073",NewCT_CommentsIds );
_dc .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0043\u0054\u005fC\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064",NewCT_CommentId );
_dc .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","c\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073",NewCommentsIds );
_dc .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0064\u0065c\u0069\u006d\u0061l\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064",NewDecimaldurableId );
};