//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package cid ;import (_a "encoding/xml";_ag "fmt";_b "github.com/unidoc/unioffice/v2";_g "github.com/unidoc/unioffice/v2/common/logger";_c "strconv";);func (_fe *CommentsIds )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_fe .CT_CommentsIds =*NewCT_CommentsIds ();
_cdb :for {_be ,_ddc :=d .Token ();if _ddc !=nil {return _ddc ;};switch _df :=_be .(type ){case _a .StartElement :switch _df .Name {case _a .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064",Local :"\u0063o\u006d\u006d\u0065\u006e\u0074\u0049d"}:_ee :=NewCT_CommentId ();
if _afa :=d .DecodeElement (_ee ,&_df );_afa !=nil {return _afa ;};_fe .CommentId =append (_fe .CommentId ,_ee );default:_g .Log .Debug ("\u0073\u006bi\u0070\u0070\u0069\u006e\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065\u0064\u0020\u0065\u006c\u0065\u006d\u0065\u006e\u0074\u0020\u006f\u006e\u0020\u0043\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073\u0020\u0025\u0076",_df .Name );
if _fef :=d .Skip ();_fef !=nil {return _fef ;};};case _a .EndElement :break _cdb ;case _a .CharData :};};return nil ;};func (_db *CT_CommentId )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0063\u0069\u0064\u003a\u0070\u0061\u0072\u0061\u0049\u0064"},Value :_ag .Sprintf ("\u0025\u0076",_db .ParaIdAttr )});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0063\u0069\u0064\u003a\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064"},Value :_ag .Sprintf ("\u0025\u0076",_db .DurableIdAttr )});e .EncodeToken (start );e .EncodeToken (_a .EndElement {Name :start .Name });
return nil ;};

// ValidateWithPath validates the CommentsIds and its children, prefixing error messages with path
func (_ac *CommentsIds )ValidateWithPath (path string )error {if _dgd :=_ac .CT_CommentsIds .ValidateWithPath (path );_dgd !=nil {return _dgd ;};return nil ;};type CT_CommentId struct{ParaIdAttr string ;DurableIdAttr string ;};

// Validate validates the CommentsIds and its children
func (_dgc *CommentsIds )Validate ()error {return _dgc .ValidateWithPath ("C\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073");};func (_dg *CT_CommentsIds )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {e .EncodeToken (start );if _dg .CommentId !=nil {_af :=_a .StartElement {Name :_a .Name {Local :"\u0063\u0069\u0064\u003a\u0063\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064"}};
for _ ,_cg :=range _dg .CommentId {e .EncodeElement (_cg ,_af );};};e .EncodeToken (_a .EndElement {Name :start .Name });return nil ;};type CommentsIds struct{CT_CommentsIds };

// Validate validates the CT_CommentId and its children
func (_gb *CT_CommentId )Validate ()error {return _gb .ValidateWithPath ("\u0043\u0054\u005fC\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064");};func (_fa *CT_CommentsIds )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {_dc :for {_eg ,_dd :=d .Token ();
if _dd !=nil {return _dd ;};switch _abg :=_eg .(type ){case _a .StartElement :switch _abg .Name {case _a .Name {Space :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064",Local :"\u0063o\u006d\u006d\u0065\u006e\u0074\u0049d"}:_ef :=NewCT_CommentId ();
if _bg :=d .DecodeElement (_ef ,&_abg );_bg !=nil {return _bg ;};_fa .CommentId =append (_fa .CommentId ,_ef );default:_g .Log .Debug ("\u0073\u006b\u0069\u0070\u0070\u0069n\u0067\u0020\u0075\u006e\u0073\u0075\u0070\u0070\u006f\u0072\u0074\u0065\u0064\u0020\u0065\u006c\u0065\u006d\u0065\u006et\u0020\u006f\u006e\u0020\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006e\u0074s\u0049d\u0073\u0020\u0025\u0076",_abg .Name );
if _bd :=d .Skip ();_bd !=nil {return _bd ;};};case _a .EndElement :break _dc ;case _a .CharData :};};return nil ;};func NewCommentsIds ()*CommentsIds {_cf :=&CommentsIds {};_cf .CT_CommentsIds =*NewCT_CommentsIds ();return _cf ;};func NewDecimaldurableId ()*DecimaldurableId {_gc :=&DecimaldurableId {};
return _gc };

// Validate validates the DecimaldurableId and its children
func (_bc *DecimaldurableId )Validate ()error {return _bc .ValidateWithPath ("\u0044\u0065c\u0069\u006d\u0061l\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064");};func (_f *CT_CommentId )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {for _ ,_ff :=range start .Attr {if _ff .Name .Local =="\u0070\u0061\u0072\u0061\u0049\u0064"{_fg :=_ff .Value ;
_f .ParaIdAttr =_fg ;continue ;};if _ff .Name .Local =="\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"{_cd :=_ff .Value ;_f .DurableIdAttr =_cd ;continue ;};};for {_ce ,_ba :=d .Token ();if _ba !=nil {return _ag .Errorf ("\u0070a\u0072\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005f\u0043\u006fm\u006d\u0065\u006e\u0074\u0049\u0064\u003a\u0020\u0025\u0073",_ba );
};if _cc ,_cea :=_ce .(_a .EndElement );_cea &&_cc .Name ==start .Name {break ;};};return nil ;};func (_cb *DecimaldurableId )UnmarshalXML (d *_a .Decoder ,start _a .StartElement )error {for _ ,_bdf :=range start .Attr {if _bdf .Name .Local =="\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"{_cdba ,_afb :=_c .ParseInt (_bdf .Value ,10,64);
if _afb !=nil {return _afb ;};_cb .DurableIdAttr =&_cdba ;continue ;};};for {_dad ,_cgd :=d .Token ();if _cgd !=nil {return _ag .Errorf ("\u0070\u0061\u0072\u0073i\u006e\u0067\u0020\u0044\u0065\u0063\u0069\u006d\u0061\u006cd\u0075r\u0061\u0062\u006c\u0065\u0049\u0064\u003a \u0025\u0073",_cgd );
};if _aba ,_bec :=_dad .(_a .EndElement );_bec &&_aba .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the CT_CommentsIds and its children, prefixing error messages with path
func (_ga *CT_CommentsIds )ValidateWithPath (path string )error {for _ec ,_ccf :=range _ga .CommentId {if _fc :=_ccf .ValidateWithPath (_ag .Sprintf ("\u0025\u0073/\u0043\u006f\u006dm\u0065\u006e\u0074\u0049\u0064\u005b\u0025\u0064\u005d",path ,_ec ));
_fc !=nil {return _fc ;};};return nil ;};func (_de *DecimaldurableId )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {if _de .DurableIdAttr !=nil {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0064u\u0072\u0061\u0062\u006c\u0065\u0049d"},Value :_ag .Sprintf ("\u0025\u0076",*_de .DurableIdAttr )});
};start .Name .Local ="c\u0069d\u003a\u0064\u0065\u0063\u0069\u006d\u0061\u006cd\u0075\u0072\u0061\u0062le\u0049\u0064";return nil ;};func NewCT_CommentsIds ()*CT_CommentsIds {_ab :=&CT_CommentsIds {};return _ab };func NewCT_CommentId ()*CT_CommentId {_bf :=&CT_CommentId {};
return _bf };

// Validate validates the CT_CommentsIds and its children
func (_dba *CT_CommentsIds )Validate ()error {return _dba .ValidateWithPath ("\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073");};type CT_CommentsIds struct{CommentId []*CT_CommentId ;};func (_dgb *CommentsIds )MarshalXML (e *_a .Encoder ,start _a .StartElement )error {start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0063\u0069d"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_a .Attr {Name :_a .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0063i\u0064:\u0063\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073";return _dgb .CT_CommentsIds .MarshalXML (e ,start );};

// ValidateWithPath validates the DecimaldurableId and its children, prefixing error messages with path
func (_ed *DecimaldurableId )ValidateWithPath (path string )error {return nil };type DecimaldurableId struct{DurableIdAttr *int64 ;};

// ValidateWithPath validates the CT_CommentId and its children, prefixing error messages with path
func (_e *CT_CommentId )ValidateWithPath (path string )error {return nil };func init (){_b .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0043\u0054\u005f\u0043\u006f\u006d\u006d\u0065\u006et\u0073\u0049\u0064\u0073",NewCT_CommentsIds );
_b .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0043\u0054\u005fC\u006f\u006d\u006d\u0065\u006e\u0074\u0049\u0064",NewCT_CommentId );
_b .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","c\u006f\u006d\u006d\u0065\u006e\u0074\u0073\u0049\u0064\u0073",NewCommentsIds );
_b .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0036\u002f\u0077\u006f\u0072\u0064\u006d\u006c\u002f\u0063\u0069\u0064","\u0064\u0065c\u0069\u006d\u0061l\u0064\u0075\u0072\u0061\u0062\u006c\u0065\u0049\u0064",NewDecimaldurableId );
};