//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package utils ;import (_d "bytes";_de "github.com/unidoc/unioffice/v2/document";_e "github.com/unidoc/unioffice/v2/document/convert";_b "github.com/unidoc/unipdf/v4/model";);

// GetNumPages will try to get actual document page count by converting the document to a PDF first
// and then get the actual page count from the PDF result.
//
// WARNING: This method is currently in experimental state as the PDF result might have incorrect page count.
func GetNumPages (d *_de .Document )(int ,error ){var _a _d .Buffer ;_c :=_e .ConvertToPdf (d );if _dee :=_c .Write (&_a );_dee !=nil {return 0,_dee ;};_eg ,_deec :=_b .NewPdfReader (_d .NewReader (_a .Bytes ()));if _deec !=nil {return 0,_deec ;};_def ,_deec :=_eg .GetNumPages ();
if _deec !=nil {return 0,_deec ;};return _def ,nil ;};