//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package chart ;import (_g "encoding/xml";_c "fmt";_ga "github.com/unidoc/unioffice/v2";);func (_ca *Formatcode2 )MarshalXML (e *_g .Encoder ,start _g .StartElement )error {start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069c\u0065\u002f\u0064\u0072\u0061w\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0035\u002f\u0030\u0036\u002f\u0063\u0068\u0061\u0072\u0074"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078\u006d\u006c\u006e\u0073\u003a\u0063\u0068"},Value :"\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069c\u0065\u002f\u0064\u0072\u0061w\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0035\u002f\u0030\u0036\u002f\u0063\u0068\u0061\u0072\u0074"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_g .Attr {Name :_g .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0063\u0068\u003a\u0066\u006f\u0072\u006d\u0061\u0074c\u006f\u0064\u0065\u0032";return e .EncodeElement (_ca .string ,start );};

// Validate validates the Formatcode2 and its children
func (_d *Formatcode2 )Validate ()error {return _d .ValidateWithPath ("F\u006f\u0072\u006d\u0061\u0074\u0063\u006f\u0064\u0065\u0032");};func NewFormatcode2 ()*Formatcode2 {_bb :=&Formatcode2 {};return _bb };type Formatcode2 struct{string };func (_bc *Formatcode2 )UnmarshalXML (d *_g .Decoder ,start _g .StartElement )error {for {_e ,_f :=d .Token ();
if _f !=nil {return _c .Errorf ("\u0070\u0061\u0072si\u006e\u0067\u0020\u0046\u006f\u0072\u006d\u0061\u0074\u0063\u006f\u0064\u0065\u0032\u003a\u0020\u0025\u0073",_f );};if _cc ,_a :=_e .(_g .EndElement );_a &&_cc .Name ==start .Name {break ;};};return nil ;
};

// ValidateWithPath validates the Formatcode2 and its children, prefixing error messages with path
func (_fa *Formatcode2 )ValidateWithPath (path string )error {return nil };func init (){_ga .RegisterConstructor ("\u0068\u0074\u0074\u0070:\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069c\u0065\u002f\u0064\u0072\u0061w\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0035\u002f\u0030\u0036\u002f\u0063\u0068\u0061\u0072\u0074","f\u006f\u0072\u006d\u0061\u0074\u0063\u006f\u0064\u0065\u0032",NewFormatcode2 );
};