//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package algo ;func RepeatString (s string ,cnt int )string {if cnt <=0{return "";};_b :=make ([]byte ,len (s )*cnt );_ce :=[]byte (s );for _cc :=0;_cc < cnt ;_cc ++{copy (_b [_cc :],_ce );};return string (_b );};